#!/usr/bin/env python3
import json

langs = ["en","es","ca","fr","de","it","pt","nl","eu","gl"]

def insert_after(data, anchor, new_keys):
    result = {}
    for k, v in data.items():
        result[k] = v
        if k == anchor:
            for nk, nv in new_keys.items():
                if nk not in result:
                    result[nk] = nv
    return result

NEW = {
    "fas_s1_h2": {
        "en": "Step 1: Open Admin Setup on Your Phone",
        "es": "Paso 1: Abrir la configuración de administrador en tu teléfono",
        "ca": "Pas 1: Obrir la configuració d'administrador al vostre telèfon",
        "fr": "Étape 1 : Ouvrir la configuration administrateur sur votre téléphone",
        "de": "Schritt 1: Admin-Einrichtung auf Ihrem Telefon öffnen",
        "it": "Passo 1: Aprire la configurazione amministratore sul telefono",
        "pt": "Passo 1: Abrir a configuração de administrador no seu telemóvel",
        "nl": "Stap 1: Admin-setup openen op uw telefoon",
        "eu": "1. urratsa: Administratzaile konfigurazioa ireki zure telefonoan",
        "gl": "Paso 1: Abrir a configuración de administrador no teu teléfono",
    },
    "fas_s1_li1": {
        "en": "Install TapAlert on your own phone (you need the app to generate the Magic Link).",
        "es": "Instala TapAlert en tu propio teléfono (necesitas la aplicación para generar el Magic Link).",
        "ca": "Instal·leu TapAlert al vostre propi telèfon (necessiteu l'aplicació per generar el Magic Link).",
        "fr": "Installez TapAlert sur votre propre téléphone (vous avez besoin de l'application pour générer le Magic Link).",
        "de": "Installieren Sie TapAlert auf Ihrem eigenen Telefon (Sie benötigen die App, um den Magic Link zu generieren).",
        "it": "Installa TapAlert sul tuo telefono (hai bisogno dell'app per generare il Magic Link).",
        "pt": "Instale o TapAlert no seu próprio telemóvel (precisa da app para gerar o Magic Link).",
        "nl": "Installeer TapAlert op uw eigen telefoon (u heeft de app nodig om de Magic Link te genereren).",
        "eu": "Instalatu TapAlert zure telefonoan (Magic Link sortzeko aplikazioa behar duzu).",
        "gl": "Instala TapAlert no teu propio teléfono (necesitas a aplicación para xerar o Magic Link).",
    },
    "fas_s1_li2": {
        "en": "Open TapAlert.",
        "es": "Abre TapAlert.",
        "ca": "Obriu TapAlert.",
        "fr": "Ouvrez TapAlert.",
        "de": "Öffnen Sie TapAlert.",
        "it": "Apri TapAlert.",
        "pt": "Abra o TapAlert.",
        "nl": "Open TapAlert.",
        "eu": "Ireki TapAlert.",
        "gl": "Abre TapAlert.",
    },
    "fas_s1_li3": {
        "en": "If you haven't completed onboarding yet, go through the permissions screens. On the last permissions screen, tap \"Set up for someone else\".",
        "es": "Si aún no has completado la configuración inicial, pasa por las pantallas de permisos. En la última pantalla, toca «Configurar para otra persona».",
        "ca": "Si encara no heu completat la configuració inicial, passeu per les pantalles de permisos. A l'última pantalla, toqueu «Configurar per a una altra persona».",
        "fr": "Si vous n'avez pas encore terminé l'intégration, parcourez les écrans d'autorisations. Sur le dernier écran, appuyez sur « Configurer pour quelqu'un d'autre ».",
        "de": "Falls Sie das Onboarding noch nicht abgeschlossen haben, gehen Sie die Berechtigungsbildschirme durch. Tippen Sie auf dem letzten Bildschirm auf \"Für jemand anderen einrichten\".",
        "it": "Se non hai ancora completato l'onboarding, scorri le schermate dei permessi. Nell'ultima schermata, tocca «Configura per qualcun altro».",
        "pt": "Se ainda não concluiu o onboarding, percorra os ecrãs de permissões. No último ecrã, toque em «Configurar para outra pessoa».",
        "nl": "Als u de onboarding nog niet heeft voltooid, doorloop dan de toestemmingsschermen. Tik op het laatste scherm op \"Instellen voor iemand anders\".",
        "eu": "Oraindik onboardinga osatu ez baduzu, baimenaren pantailak egin. Azken pantailan, sakatu \"Beste norbaitzarako konfiguratu\".",
        "gl": "Se aínda non completaches a configuración inicial, pasa polas pantallas de permisos. Na última pantalla, toca «Configurar para outra persoa».",
    },
    "fas_s1_li4": {
        "en": "If TapAlert is already installed and set up, go to Settings → scroll to the very bottom → tap \"Admin Setup / Magic Link\".",
        "es": "Si TapAlert ya está instalado y configurado, ve a Ajustes → desplázate hasta el final → toca «Configuración de administrador / Magic Link».",
        "ca": "Si TapAlert ja està instal·lat i configurat, aneu a Configuració → desplaceu-vos fins al final → toqueu «Configuració d'administrador / Magic Link».",
        "fr": "Si TapAlert est déjà installé et configuré, allez dans Paramètres → faites défiler jusqu'en bas → appuyez sur « Configuration admin / Magic Link ».",
        "de": "Falls TapAlert bereits installiert ist, gehen Sie zu Einstellungen → scrollen Sie ganz nach unten → tippen Sie auf \"Admin-Einrichtung / Magic Link\".",
        "it": "Se TapAlert è già installato, vai su Impostazioni → scorri fino in fondo → tocca «Configurazione admin / Magic Link».",
        "pt": "Se o TapAlert já está instalado, vá a Definições → role até ao fim → toque em «Configuração admin / Magic Link».",
        "nl": "Als TapAlert al geïnstalleerd is, ga naar Instellingen → scroll helemaal naar beneden → tik op \"Admin-setup / Magic Link\".",
        "eu": "TapAlert dagoeneko instalatuta badago, joan Ezarpenak → joan behera → sakatu \"Admin konfigurazioa / Magic Link\".",
        "gl": "Se TapAlert xa está instalado, vai a Axustes → desprázate ata o final → toca «Configuración de administrador / Magic Link».",
    },
    "fas_s1_p2": {
        "en": "The Admin Setup screen will open. Scroll through the sections — you'll fill each one in the steps below.",
        "es": "Se abrirá la pantalla de configuración de administrador. Desplázate por las secciones: las irás completando en los pasos siguientes.",
        "ca": "S'obrirà la pantalla de configuració d'administrador. Desplaceu-vos per les seccions: les anireu completant als passos següents.",
        "fr": "L'écran de configuration administrateur s'ouvrira. Faites défiler les sections — vous les remplirez dans les étapes suivantes.",
        "de": "Der Admin-Einrichtungsbildschirm öffnet sich. Scrollen Sie durch die Abschnitte — Sie füllen jeden in den folgenden Schritten aus.",
        "it": "Si aprirà la schermata di configurazione amministratore. Scorri le sezioni — le compilerai nei passaggi seguenti.",
        "pt": "O ecrã de configuração de administrador abrirá. Percorra as secções — preencherá cada uma nos passos seguintes.",
        "nl": "Het admin-instellingsscherm wordt geopend. Scroll door de secties — u vult elke sectie in bij de stappen hieronder.",
        "eu": "Admin konfigurazio pantaila irekiko da. Ibili sekzioen artean — beheko urratseetan bakoitza beteko duzu.",
        "gl": "Abrirase a pantalla de configuración de administrador. Desprázate polas seccións: completaraas nos pasos seguintes.",
    },
    "fas_s2_h2": {
        "en": "Step 2: Enter the Senior's Name",
        "es": "Paso 2: Introducir el nombre de la persona mayor",
        "ca": "Pas 2: Introduir el nom de la persona gran",
        "fr": "Étape 2 : Saisir le prénom du senior",
        "de": "Schritt 2: Den Namen des Seniors eingeben",
        "it": "Passo 2: Inserire il nome dell'anziano",
        "pt": "Passo 2: Introduzir o nome do idoso",
        "nl": "Stap 2: De naam van de senior invoeren",
        "eu": "2. urratsa: Pertsona helduaren izena sartu",
        "gl": "Paso 2: Introducir o nome da persoa maior",
    },
    "fas_s2_p1": {
        "en": "In the \"User Information\" section at the top of the screen:",
        "es": "En la sección «Información del usuario» en la parte superior de la pantalla:",
        "ca": "A la secció «Informació de l'usuari» a la part superior de la pantalla:",
        "fr": "Dans la section « Informations utilisateur » en haut de l'écran :",
        "de": "Im Abschnitt \"Benutzerinformationen\" oben auf dem Bildschirm:",
        "it": "Nella sezione «Informazioni utente» in cima alla schermata:",
        "pt": "Na secção «Informação do utilizador» no topo do ecrã:",
        "nl": "In het gedeelte \"Gebruikersinformatie\" bovenaan het scherm:",
        "eu": "\"Erabiltzaile informazioa\" atalean, pantailaren goialdean:",
        "gl": "Na sección «Información do usuario» na parte superior da pantalla:",
    },
    "fas_s2_li1": {
        "en": "Senior's Name — Type the senior's first name (e.g., \"Maria\"). This name appears in alert messages so recipients know who sent the alert.",
        "es": "Nombre de la persona mayor — Escribe su nombre de pila (p. ej., «María»). Este nombre aparece en los mensajes de alerta para que los destinatarios sepan quién la envió.",
        "ca": "Nom de la persona gran — Escriviu el seu nom (p. ex., «Maria»). Aquest nom apareix als missatges d'alerta perquè els destinataris sàpiguen qui l'ha enviada.",
        "fr": "Prénom du senior — Tapez son prénom (ex. : «Maria»). Ce nom apparaît dans les messages d'alerte pour que les destinataires sachent qui l'a envoyée.",
        "de": "Name des Seniors — Geben Sie seinen Vornamen ein (z. B. \"Maria\"). Dieser Name erscheint in Alarmnachrichten, damit die Empfänger wissen, wer den Alarm gesendet hat.",
        "it": "Nome dell'anziano — Digita il suo nome (es. «Maria»). Questo nome appare nei messaggi di avviso così i destinatari sanno chi lo ha inviato.",
        "pt": "Nome do idoso — Escreva o seu primeiro nome (ex.: «Maria»). Este nome aparece nas mensagens de alerta para que os destinatários saibam quem a enviou.",
        "nl": "Naam van de senior — Typ zijn/haar voornaam (bijv. \"Maria\"). Deze naam verschijnt in meldingsberichten zodat ontvangers weten wie de melding heeft verzonden.",
        "eu": "Pertsona helduaren izena — Idatzi bere izena (adib., \"Maria\"). Izen hau alerta mezuetan agertuko da hartzaileek nor bidali duen jakiteko.",
        "gl": "Nome da persoa maior — Escribe o seu nome de pila (p. ex., «María»). Este nome aparece nas mensaxes de alerta para que os destinatarios saiban quen a enviou.",
    },
    "fas_s2_tip": {
        "en": "Example: If you type \"Maria\", recipients will receive: \"ALERT from Maria: I need help. Location: …\"",
        "es": "Ejemplo: Si escribes «María», los destinatarios recibirán: «ALERTA de María: Necesito ayuda. Ubicación: …»",
        "ca": "Exemple: Si escriviu «Maria», els destinataris rebran: «ALERTA de Maria: Necessito ajuda. Ubicació: …»",
        "fr": "Exemple : Si vous tapez «Maria», les destinataires recevront : «ALERTE de Maria : J'ai besoin d'aide. Localisation : …»",
        "de": "Beispiel: Wenn Sie \"Maria\" eingeben, erhalten Empfänger: \"ALARM von Maria: Ich brauche Hilfe. Standort: …\"",
        "it": "Esempio: Se digiti «Maria», i destinatari ricevono: «AVVISO da Maria: Ho bisogno di aiuto. Posizione: …»",
        "pt": "Exemplo: Se escrever «Maria», os destinatários recebem: «ALERTA de Maria: Preciso de ajuda. Localização: …»",
        "nl": "Voorbeeld: Als u \"Maria\" typt, ontvangen ontvangers: \"MELDING van Maria: Ik heb hulp nodig. Locatie: …\"",
        "eu": "Adibidea: \"Maria\" idazten baduzu, hartzaileek jasoko dute: \"ALERTA Maria-rengandik: Laguntza behar dut. Kokapena: …\"",
        "gl": "Exemplo: Se escribes «María», os destinatarios recibirán: «ALERTA de María: Necesito axuda. Localización: …»",
    },
    "fas_s3_h2": {
        "en": "Step 3: Configure SMS Delivery (Twilio)",
        "es": "Paso 3: Configurar el envío de SMS (Twilio)",
        "ca": "Pas 3: Configurar l'enviament de SMS (Twilio)",
        "fr": "Étape 3 : Configurer l'envoi de SMS (Twilio)",
        "de": "Schritt 3: SMS-Versand konfigurieren (Twilio)",
        "it": "Passo 3: Configurare l'invio di SMS (Twilio)",
        "pt": "Passo 3: Configurar o envio de SMS (Twilio)",
        "nl": "Stap 3: Sms-bezorging configureren (Twilio)",
        "eu": "3. urratsa: SMS bidalketa konfiguratu (Twilio)",
        "gl": "Paso 3: Configurar o envío de SMS (Twilio)",
    },
    "fas_s3_optA_h3": {
        "en": "Option A: No Twilio (simplest)",
        "es": "Opción A: Sin Twilio (la más sencilla)",
        "ca": "Opció A: Sense Twilio (la més senzilla)",
        "fr": "Option A : Sans Twilio (la plus simple)",
        "de": "Option A: Ohne Twilio (am einfachsten)",
        "it": "Opzione A: Senza Twilio (la più semplice)",
        "pt": "Opção A: Sem Twilio (a mais simples)",
        "nl": "Optie A: Zonder Twilio (eenvoudigst)",
        "eu": "A aukera: Twilio gabe (sinpleena)",
        "gl": "Opción A: Sen Twilio (a máis sinxela)",
    },
    "fas_s3_optA_p": {
        "en": "Leave the \"Enable Twilio SMS\" toggle off.",
        "es": "Deja el interruptor «Activar SMS de Twilio» desactivado.",
        "ca": "Deixeu el commutador «Activa SMS de Twilio» desactivat.",
        "fr": "Laissez le bouton « Activer les SMS Twilio » désactivé.",
        "de": "Lassen Sie den Schalter \"Twilio SMS aktivieren\" ausgeschaltet.",
        "it": "Lascia il pulsante «Abilita SMS Twilio» disattivato.",
        "pt": "Deixe o botão «Ativar SMS do Twilio» desativado.",
        "nl": "Laat de schakelaar \"Twilio SMS inschakelen\" uit.",
        "eu": "Utzi \"Twilio SMS gaitu\" txandakatzailea itzalita.",
        "gl": "Deixa o interruptor «Activar SMS de Twilio» desactivado.",
    },
    "fas_s3_optA_li1": {
        "en": "On Android, the app sends SMS directly using the phone's SIM card — no Twilio needed.",
        "es": "En Android, la aplicación envía SMS directamente usando la SIM del teléfono, sin necesidad de Twilio.",
        "ca": "A Android, l'aplicació envia SMS directament amb la SIM del telèfon, sense necessitat de Twilio.",
        "fr": "Sur Android, l'application envoie les SMS directement via la carte SIM du téléphone — pas de Twilio nécessaire.",
        "de": "Auf Android sendet die App SMS direkt über die SIM-Karte — kein Twilio erforderlich.",
        "it": "Su Android, l'app invia SMS direttamente tramite la SIM — Twilio non è necessario.",
        "pt": "No Android, a app envia SMS diretamente com o cartão SIM — sem necessidade de Twilio.",
        "nl": "Op Android stuurt de app sms'jes rechtstreeks via de simkaart — geen Twilio nodig.",
        "eu": "Androiden, aplikazioak SMS bidaltzen ditu zuzenean SIM txartela erabiliz — ez da Twilio behar.",
        "gl": "En Android, a aplicación envía SMS directamente usando a SIM do teléfono, sen necesidade de Twilio.",
    },
    "fas_s3_optA_li2": {
        "en": "On iPhone, the app opens the Messages app pre-filled, and the senior taps Send once. Simple but requires one extra step.",
        "es": "En iPhone, la aplicación abre la app Mensajes con el texto ya escrito y la persona mayor toca Enviar una vez. Sencillo pero requiere un paso adicional.",
        "ca": "A l'iPhone, l'aplicació obre l'app Missatges amb el text ja escrit i la persona gran toca Enviar una vegada. Senzill però requereix un pas addicional.",
        "fr": "Sur iPhone, l'application ouvre l'app Messages pré-remplie et le senior appuie sur Envoyer une fois. Simple mais nécessite une étape supplémentaire.",
        "de": "Auf iPhone öffnet die App die Nachrichten-App bereits ausgefüllt, und der Senior tippt einmal auf Senden. Einfach, aber ein zusätzlicher Schritt.",
        "it": "Su iPhone, l'app apre l'app Messaggi già compilata e l'anziano tocca Invia una volta. Semplice ma richiede un passaggio in più.",
        "pt": "No iPhone, a app abre a app Mensagens já preenchida e o idoso toca em Enviar uma vez. Simples mas requer um passo extra.",
        "nl": "Op de iPhone opent de app de Berichten-app vooraf ingevuld en tikt de senior eenmaal op Verzenden. Eenvoudig maar één extra stap.",
        "eu": "iPhonean, aplikazioak Mezuak aplikazioa beteta irekitzen du eta pertsona helduak Bidali behin sakatu behar du. Sinplea baina urrats gehigarri bat.",
        "gl": "No iPhone, a aplicación abre a app Mensaxes xa cuberta e a persoa maior toca Enviar unha vez. Sinxelo pero require un paso adicional.",
    },
    "fas_s3_optB_h3": {
        "en": "Option B: With Twilio (recommended for full automation)",
        "es": "Opción B: Con Twilio (recomendado para automatización completa)",
        "ca": "Opció B: Amb Twilio (recomanat per a l'automatització completa)",
        "fr": "Option B : Avec Twilio (recommandé pour une automatisation complète)",
        "de": "Option B: Mit Twilio (empfohlen für vollständige Automatisierung)",
        "it": "Opzione B: Con Twilio (consigliato per la piena automazione)",
        "pt": "Opção B: Com Twilio (recomendado para automação completa)",
        "nl": "Optie B: Met Twilio (aanbevolen voor volledige automatisering)",
        "eu": "B aukera: Twilio-rekin (automatizazio osoa lortzeko gomendatua)",
        "gl": "Opción B: Con Twilio (recomendado para a automatización completa)",
    },
    "fas_s3_optB_li1": {"en":"Toggle \"Enable Twilio SMS\" to on.","es":"Activa el interruptor «Activar SMS de Twilio».","ca":"Activeu el commutador «Activa SMS de Twilio».","fr":"Activez le bouton « Activer les SMS Twilio ».","de":"Schalten Sie \"Twilio SMS aktivieren\" ein.","it":"Attiva «Abilita SMS Twilio».","pt":"Ative «Ativar SMS do Twilio».","nl":"Zet \"Twilio SMS inschakelen\" aan.","eu":"Piztu \"Twilio SMS gaitu\" txandakatzailea.","gl":"Activa o interruptor «Activar SMS de Twilio»."},
    "fas_s3_optB_li2": {"en":"Enter the Account SID from your Twilio Console (starts with \"AC…\").","es":"Introduce el SID de cuenta de tu consola de Twilio (empieza por «AC…»).","ca":"Introduïu el SID del compte de la consola de Twilio (comença per «AC…»).","fr":"Entrez le SID de compte depuis votre console Twilio (commence par « AC… »).","de":"Geben Sie die Account SID aus Ihrer Twilio-Konsole ein (beginnt mit \"AC…\").","it":"Inserisci l'Account SID dalla console Twilio (inizia con «AC…»).","pt":"Introduza o Account SID da consola Twilio (começa com «AC…»).","nl":"Voer de Account SID in van uw Twilio Console (begint met \"AC…\").","eu":"Sartu zure Twilio kontsola-ko Account SID (\"AC…\"-rekin hasten da).","gl":"Introduce o SID de conta da túa consola de Twilio (comeza por «AC…»)."},
    "fas_s3_optB_li3": {"en":"Enter the Auth Token from your Twilio Console (tap the eye icon to show/hide).","es":"Introduce el Auth Token de tu consola de Twilio (toca el icono de ojo para mostrar/ocultar).","ca":"Introduïu l'Auth Token de la consola de Twilio (toqueu la icona de l'ull per mostrar/ocultar).","fr":"Entrez l'Auth Token depuis votre console Twilio (appuyez sur l'icône oeil pour afficher/masquer).","de":"Geben Sie das Auth Token aus Ihrer Twilio-Konsole ein (Auge-Symbol zum Ein-/Ausblenden).","it":"Inserisci l'Auth Token dalla console Twilio (tocca l'icona occhio per mostrare/nascondere).","pt":"Introduza o Auth Token da consola Twilio (toque no icone de olho para mostrar/ocultar).","nl":"Voer het Auth Token in van uw Twilio Console (tik op het oogpictogram om te tonen/verbergen).","eu":"Sartu zure Twilio kontsola-ko Auth Token (begi ikonoa sakatu erakusteko/ezkutatzeko).","gl":"Introduce o Auth Token da túa consola de Twilio (toca o icono de ollo para mostrar/ocultar)."},
    "fas_s3_optB_li4": {"en":"Choose how to identify the sender:","es":"Elige cómo identificar al remitente:","ca":"Trieu com identificar el remitent:","fr":"Choisissez comment identifier l'expéditeur :","de":"Wählen Sie, wie der Absender identifiziert werden soll:","it":"Scegli come identificare il mittente:","pt":"Escolha como identificar o remetente:","nl":"Kies hoe u de afzender wilt identificeren:","eu":"Aukeratu igorlea nola identifikatu:","gl":"Escolle como identificar o remitente:"},
    "fas_s3_optB_li4a": {"en":"Twilio phone number — Enter the number from Twilio (e.g., +12015551234). Select the correct country flag first.","es":"Número de Twilio — Introduce el número de Twilio (p. ej., +12015551234). Selecciona primero la bandera del país.","ca":"Número de Twilio — Introduïu el número de Twilio (p. ex., +12015551234). Seleccioneu primer la bandera del país.","fr":"Numéro Twilio — Entrez le numéro Twilio (ex. +12015551234). Sélectionnez d'abord le drapeau du pays.","de":"Twilio-Nummer — Geben Sie die Twilio-Nummer ein (z. B. +12015551234). Wählen Sie zuerst die Landesflagge.","it":"Numero Twilio — Inserisci il numero Twilio (es. +12015551234). Seleziona prima la bandiera del paese.","pt":"Numero Twilio — Introduza o numero Twilio (ex. +12015551234). Selecione primeiro a bandeira do pais.","nl":"Twilio-nummer — Voer het Twilio-nummer in (bijv. +12015551234). Selecteer eerst de landvlag.","eu":"Twilio zenbakia — Sartu Twilio zenbakia (adib., +12015551234). Aukeratu lehenik herrialde bandera.","gl":"Número de Twilio — Introduce o número de Twilio (p. ex., +12015551234). Selecciona primeiro a bandeira do país."},
    "fas_s3_optB_li4b": {"en":"Sender Name — Toggle on \"Use Alphanumeric Sender Name\" and type a short name (e.g., \"TapAlert\"). Note: not supported in all countries (e.g., USA).","es":"Nombre del remitente — Activa «Usar nombre alfanumérico» y escribe un nombre corto (p. ej., «TapAlert»). Nota: no disponible en todos los países (p. ej., EE. UU.).","ca":"Nom del remitent — Activeu «Usa nom alfanumèric» i escriviu un nom curt (p. ex., «TapAlert»). Nota: no disponible a tots els països (p. ex., EUA).","fr":"Nom d'expéditeur — Activez «Utiliser un nom alphanumérique» et tapez un nom court (ex. «TapAlert»). Remarque : non pris en charge dans tous les pays (ex. USA).","de":"Absendername — Aktivieren Sie \"Alphanumerischen Absendernamen verwenden\" und geben Sie einen kurzen Namen ein (z. B. \"TapAlert\"). Hinweis: Nicht in allen Ländern unterstützt (z. B. nicht in den USA).","it":"Nome mittente — Attiva «Usa nome alfanumerico» e digita un nome breve (es. «TapAlert»). Nota: non supportato in tutti i paesi (es. USA).","pt":"Nome remetente — Ative «Usar nome alfanumerico» e escreva um nome curto (ex. «TapAlert»). Nota: nao suportado em todos os paises (ex. EUA).","nl":"Afzendernaam — Zet \"Alfanumerische afzendernaam\" aan en typ een korte naam (bijv. \"TapAlert\"). Let op: niet in alle landen ondersteund (bijv. VS).","eu":"Igorle izena — Piztu \"Igorle izen alfanumerikoa\" eta idatzi izen labur bat (adib., \"TapAlert\"). Oharra: ez da herrialde guztietan onartzen (adib., EEBB).","gl":"Nome do remitente — Activa «Usar nome alfanumérico» e escribe un nome curto (p. ex., «TapAlert»). Nota: non dispoñible en todos os países (p. ex., EE. UU.)."},
    "fas_s3_optB_li5": {"en":"Your phone number — Enter your own number. The app sends a test SMS to confirm Twilio is working before generating the link.","es":"Tu número — Introduce tu propio número. La aplicación envía un SMS de prueba para confirmar que Twilio funciona antes de generar el enlace.","ca":"El vostre número — Introduïu el vostre propi número. L'aplicació envia un SMS de prova per confirmar que Twilio funciona abans de generar l'enllaç.","fr":"Votre numéro — Entrez votre propre numéro. L'application envoie un SMS de test pour confirmer que Twilio fonctionne avant de générer le lien.","de":"Ihre Nummer — Geben Sie Ihre eigene Nummer ein. Die App sendet eine Test-SMS, um zu bestätigen, dass Twilio funktioniert.","it":"Il tuo numero — Inserisci il tuo numero. L'app invia un SMS di prova per confermare che Twilio funziona prima di generare il link.","pt":"O seu numero — Introduza o seu numero. A app envia um SMS de teste para confirmar que o Twilio funciona antes de gerar o link.","nl":"Uw nummer — Voer uw eigen nummer in. De app stuurt een test-sms om te bevestigen dat Twilio werkt voordat de link wordt gegenereerd.","eu":"Zure zenbakia — Sartu zure zenbakia. Aplikazioak proba SMS bat bidaliko du esteka sortu aurretik Twilio funtzionatzen duela berresteko.","gl":"O teu número — Introduce o teu propio número. A aplicación envía un SMS de proba para confirmar que Twilio funciona antes de xerar o enlace."},
    "fas_s3_tip": {"en":"Where to find Twilio credentials: Log in at console.twilio.com. Account SID and Auth Token are on the main dashboard. Phone number is under Phone Numbers → Manage → Active Numbers.","es":"Cómo encontrar las credenciales de Twilio: Inicia sesión en console.twilio.com. El Account SID y el Auth Token aparecen en el panel principal. El número está en Números de teléfono → Administrar → Números activos.","ca":"On trobar les credencials de Twilio: Inicieu sessió a console.twilio.com. L'Account SID i el Auth Token es mostren al tauler principal. El número es troba a Números de telèfon → Gestionar → Números actius.","fr":"Où trouver les identifiants Twilio : Connectez-vous sur console.twilio.com. L'Account SID et l'Auth Token sont sur la page principale du tableau de bord. Le numéro est sous Numéros de téléphone → Gérer → Numéros actifs.","de":"Twilio-Zugangsdaten: Melden Sie sich bei console.twilio.com an. Account SID und Auth Token auf der Haupt-Dashboard-Seite. Ihre Nummer unter Telefonnummern → Verwalten → Aktive Nummern.","it":"Dove trovare le credenziali Twilio: Accedi a console.twilio.com. Account SID e Auth Token sono nella dashboard principale. Il numero è sotto Numeri di telefono → Gestisci → Numeri attivi.","pt":"Onde encontrar as credenciais Twilio: Aceda a console.twilio.com. Account SID e Auth Token estao na pagina principal do painel. O numero esta em Numeros de telefone → Gerir → Numeros ativos.","nl":"Waar u Twilio-inloggegevens vindt: Log in op console.twilio.com. Account SID en Auth Token staan op de hoofdpagina van het dashboard. Uw nummer staat onder Telefoonnummers → Beheren → Actieve nummers.","eu":"Twilio kredentzialak non aurkitu: Hasi saioa console.twilio.com-en. Account SID eta Auth Token paneleko orri nagusian. Zure zenbakia Telefono Zenbakiak → Kudeatu → Zenbaki Aktiboak atalean.","gl":"Como atopar as credenciais de Twilio: Inicia sesión en console.twilio.com. O Account SID e o Auth Token aparecen no panel principal. O número está en Números de teléfono → Xestionar → Números activos."},
}

anchor = "fas_s1_p2" if False else "fas_email_req_li2"
for lang in langs:
    path = f"locales/{lang}.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    new_data = insert_after(data, "fas_email_req_li2", {k: v[lang] for k, v in NEW.items()})
    with open(path, "w", encoding="utf-8") as f:
        json.dump(new_data, f, ensure_ascii=False, indent=4)
    print(f"{lang} batch2 ok")
