import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        if k not in en:
            en[k] = v
    for k, v in new_es.items():
        if k not in es:
            es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "ug_title": "User Guide",
    "ug_intro": "This guide explains how to configure and use <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> on your {{ android_table_th2 }} or iOS device.",
    "ug_h2_1": "1. 🛡️ Required Permissions",
    "ug_p1": "Upon first launch, the app will request the following permissions:",
    "ug_li1_1": "<strong>SMS ({{ android_table_th2 }} Only):</strong> Needed to send direct messages from your phone's SIM card.",
    "ug_li1_2": "<strong>{{ ts_li1_5 }}:</strong> Needed to include your GPS coordinates in the alert message.",
    "ug_li1_3": "<strong>Microphone:</strong> Needed if you use the voice recording feature to transcribe your alert message.",
    "ug_li1_4": "<strong>{{ sms_so_li1_2 }}:</strong> Needed to easily select recipients from your phone's address book.",
    "ug_note_1": "<strong>NOTE:</strong> On iOS, <span class=\"notranslate\" translate=\"no\">direct SMS</span> sending is not supported by the system for automated alerts. You {{ ts_em_li5 }} use the <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong> method.",
    "ug_h2_2": "2. 📱 Interface Modes",
    "ug_p2": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> offers two distinct interface modes to suit your needs. You can switch between them in <strong>Settings > Interface Mode</strong>.",
    "ug_h3_1": "<span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\" translate=\"no\">SOS</span> / OK)",
    "ug_p3": "A streamlined interface designed for maximum simplicity and accessibility, ideal for elderly users or high-stress situations.",
    "ug_li2_1": "<strong>Large <span class=\"notranslate\" translate=\"no\">SOS</span> Button:</strong> Instantly starts the countdown for an \"<span class=\"notranslate\" translate=\"no\">SOS</span>, I need help\" alert.",
    "ug_li2_2": "<strong>I'm OK Button:</strong> Quickly sends an \"I'm OK\" status update to reassure contacts.",
    "ug_li2_3": "<strong>Voice Buttons:</strong> Each section h{{ qa_step3_p5 }} dedicated voice{{ phil_sen_li2 }} to record and send an audio transcript along with the <span class=\"notranslate\" translate=\"no\">SOS</span> or OK status.",
    "ug_li2_4": "<strong>Emergency Call Button:</strong> A dedicated{{ phil_sen_li2 }} to immediately call local emergency services (e.g., 112, 911) based on your location.",
    "ug_h3_2": "Report Mode (Tabs)",
    "ug_p4": "The default mode, offering flexibility with multiple message types.",
    "ug_li3_1": "<strong>4 Message Tabs:</strong> Pre-configure different alerts (e.g., \"Medical\", \"Car Trouble\", \"Generic\").",
    "ug_li3_2": "<strong>Customizable Text:</strong> Tap inside the message box to edit content on the fly.",
    "ug_li3_3": "<strong>Voice Transcription:</strong> Use the microphone to dictate a custom message.",
    "ug_h2_3": "3. 📝 Setup Predefined Messages (Report Mode)",
    "ug_p5": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> comes with 4 predefined message slots (tabs) allowing you to quickly switch between different alert scenarios.",
    "ug_h3_3": "{{ sms_ios_li1 }}ing Messages",
    "ug_li4_1": "<strong>{{ ts_loc_li2 }} a Tab:</strong> Tap on one of the numbered tabs (1-3) at the top.",
    "ug_li4_2": "<strong>{{ sms_ios_li1 }} Text:</strong> Tap inside the message box to type your custom alert message (e.g., \"Medical Emergency\", \"Car Trouble\").",
    "ug_li4_3": "<strong>Auto-Save:</strong> Your changes are saved automatically as you type.",
    "ug_li4_4": "<strong>Dictation:</strong> You can also use the dictation icon to dictate your message.",
    "ug_h3_4": "🎙️ Voice Quick Alert Message",
    "ug_p6": "You can use your voice to generate the alert text in real-time. This is useful for describing a specific situation quickly. The message will be saved on the 4th tab.",
    "ug_li5_1": "<strong>Tap the Microphone red{{ phil_sen_li2 }}:</strong> It will start <strong>pulsing</strong> when active.",
    "ug_li5_2": "<strong>Speak your message:</strong> The status bar at the bottom will turn <strong>light orange</strong> and show a sound wave symbol while listening.",
    "ug_li5_3": "<strong>Automatic Update and Instant Send:</strong> After speaking or tapping the microphone{{ phil_sen_li2 }} again, the message text will be updated and the <strong>SEND ALERT</strong> will be triggered immediately. You can also press the <strong>SEND ALERT</strong>{{ phil_sen_li2 }} directly while recording; the app will automatically stop the recording and save and send the transcribed message immediately.",
    "ug_h2_4": "4. 👥 Setup/Managing Recipients",
    "ug_p7": "This is done in the dedicated <strong>Recipients Screen</strong>, accessible from the top bar of the Home Screen:",
    "ug_li6_1": "<strong>Open Recipients:</strong> Tap the <strong>People/Group Icon</strong> (👥) in the top-right toolbar.",
    "ug_li6_2_1": "<strong>Add Number:</strong>",
    "ug_li6_2_2": "Tap the <strong>\"Add\"</strong>{{ phil_sen_li2 }} to manually enter a phone number.",
    "ug_li6_2_3": "Tap the <strong>{{ nav_contact }} Icon</strong> to pick a number directly from your phone's address book.",
    "ug_li6_3": "<strong>Format:</strong> Use the <strong>E.164 international format</strong> (e.g., <code>+34600000000</code>) for best results.",
    "ug_li6_4": "<strong>Remove:</strong> Tap the delete icon next to any number in the list to remove it. You can also \"Delete All\" using the trash bin icon at the top.",
    "ug_tip_1_1": "<strong>TIP: Can't see all your contacts?</strong>",
    "ug_tip_1_2": "<strong>iOS:</strong> If you chose \"{{ ts_loc_li2 }} {{ sms_so_li1_2 }}...\" (Limited Access), the app can only see the few you picked. To fix this, go to <strong>iPhone Settings > {{ table_r2c1 }} & Security > {{ sms_so_li1_2 }} > <span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> and select <strong>\"All {{ sms_so_li1_2 }}\"</strong>.",
    "ug_tip_1_3": "<strong>{{ android_table_th2 }}:</strong> Permissions are \"all-or-nothing\". If you denied access, the picker will be empty. {{ sms_and_li6 }} the app has \"{{ sms_so_li1_2 }}\" permission in your phone's App Settings.",
    "ug_h2_5": "5. ⚙️ Configuration Options",
    "ug_p8": "Access the settings menu via the gear icon ⚙️ to further customize the alert message text and the SMS delivery method.",
    "ug_h3_5": "SMS Sending Methods",
    "ug_p9": "The app supports two ways to send messages:",
    "ug_li7_1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ({{ android_table_th2 }}):</strong> Uses your phone's SIM card. Cost depends on your mobile carrier plan.",
    "ug_li7_2": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS ({{ android_table_th2 }} & iOS):</strong> Uses the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API over the internet (Wi-Fi/Data). {{ feature_reliable }} and required for iOS.",
    "ug_h3_6": "<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> ({{ android_table_th2 }} Only)",
    "ug_p10": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> {{ price_features }} a <strong><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span></strong> system that automatically switches methods if the primary one fails:",
    "ug_li8_1": "<strong>No Signal?</strong> If you try to send a <span class=\"notranslate\" translate=\"no\">Direct SMS</span> but have no cellular coverage (e.g., inside a building), the app will automatically attempt to send via <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Wi-Fi).",
    "ug_li8_2": "<strong>No Data?</strong> If you use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> as primary but are hiking {{ ts_loc_li7 }} 4G/5G, the app will automatically <span class=\"notranslate\" translate=\"no\">fallback</span> to sending a <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span>.",
    "ug_p11": "<strong>To enable:</strong> Go to Settings and turn on <strong>\"<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span>\"</strong>.",
    "ug_h3_7": "Email Redundancy (Wi-Fi <span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span>)",
    "ug_p12": "If you have no cellular signal but are connected to Wi-Fi, <span class=\"notranslate\" translate=\"no\">TapAlert</span> can send your alert via email.",
    "ug_li9_1": "<strong>Setup:</strong> Go to <strong>Settings > Email Redundancy</strong>. For detailed instructions, see <strong>Chapter 6: Configuring Email Redundancy</strong>.",
    "ug_li9_2": "<strong>Automatic <span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span>:</strong> When enabled, the app will attempt to send an email alert if both <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> and <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (cellular) fail.",
    "ug_h3_8": "Trigger Method (Tap vs. Hold)",
    "ug_p13": "Prevent accidental triggers by changing how the alert is activated in <strong>Settings > Trigger Method</strong>:",
    "ug_li10_1": "<strong>Tap to Send (Default):</strong> A single tap on the alert{{ phil_sen_li2 }} triggers the countdown.",
    "ug_li10_2": "<strong>Press & Hold (5s):</strong> You {{ ts_em_li5 }} hold the alert{{ phil_sen_li2 }} for 5 continuous seconds to trigger the countdown. This is recommended to avoid false alarms.",
    "ug_note_2": "<strong>IMPORTANT: iOS Users</strong><br> You {{ ts_em_li5 }} configure a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }}.<br> 👉 <strong>For detailed <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> setup instructions, please see the separate \"<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Guide\" in the Help menu.</strong>",
    "ug_h3_9": "Auto-Start on Launch",
    "ug_p14": "Automatically start the alert countdown immediately when the app opens.",
    "ug_li11_1": "<strong>Useful for:</strong> Creating a physical panic{{ phil_sen_li2 }} (using hardware key remapping) or a quick-launch shortcut.",
    "ug_li11_2": "<strong>Warning:</strong> When enabled, opening the app will always trigger the countdown. You can cancel it during the delay period.",
    "ug_h3_10": "Message {{ ts_li1_5 }}",
    "ug_li12_1": "<strong>Include {{ ts_li1_5 }}:</strong> Append GPS coordinates to the message.",
    "ug_li12_2": "<strong>Include Address:</strong> Attempt to convert coordinates into a human-readable address.",
    "ug_h3_11": "Additional Settings",
    "ug_li13_1": "<strong>Sender Identity:</strong> (<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Only) Choose the name or number that appears as the sender (e.g., \"Alert\" or your specific <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> number).",
    "ug_li13_2": "<strong>Appearance:</strong> Toggle between Light Mode, Dark Mode, or follow System Settings.",
    "ug_li13_3": "<strong>App {{ guide_lang }}:</strong> Manually override the app's language (default: System {{ guide_lang }}).",
    "ug_li13_4": "<strong>Region and formatting:</strong> Set your region to ensure phone numbers are formatted correctly (e.g., auto-adding country codes).",
    "ug_li13_5": "<strong>Notification sound:</strong> Choose the alert sound that plays after a successful message delivery."
}

es_keys = {
    "ug_title": "Gu\u00eda de Usuario",
    "ug_intro": "Esta gu\u00eda explica c\u00f3mo configurar y usar <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> en tu dispositivo {{ android_table_th2 }} o iOS.",
    "ug_h2_1": "1. \ud83d\udee1\ufe0f Permisos Requeridos",
    "ug_p1": "Al iniciarse por primera vez, la aplicaci\u00f3n solicitar\u00e1 los siguientes permisos:",
    "ug_li1_1": "<strong>SMS (Solo {{ android_table_th2 }}):</strong> Necesario para enviar mensajes directos desde la tarjeta SIM de tu tel\u00e9fono.",
    "ug_li1_2": "<strong>{{ ts_li1_5 }}:</strong> Necesario para incluir tus coordenadas GPS en el mensaje de alerta.",
    "ug_li1_3": "<strong>Micr\u00f3fono:</strong> Necesario si usas la funci\u00f3n de grabaci\u00f3n de voz para transcribir tu mensaje de alerta.",
    "ug_li1_4": "<strong>{{ sms_so_li1_2 }}:</strong> Necesario para seleccionar f\u00e1cilmente destinatarios de la libreta de direcciones de tu tel\u00e9fono.",
    "ug_note_1": "<strong>NOTA:</strong> En iOS, el env\u00edo de <span class=\"notranslate\" translate=\"no\">SMS directo</span> no est\u00e1 soportado por el sistema para alertas autom\u00e1ticas. T\u00fa {{ ts_em_li5 }} usar el m\u00e9todo de <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong>.",
    "ug_h2_2": "2. \ud83d\udcf1 Modos de Interfaz",
    "ug_p2": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> ofrece dos modos de interfaz distintos para adaptarse a tus necesidades. Puedes cambiar entre ellos en <strong>Ajustes > Modo de Interfaz</strong>.",
    "ug_h3_1": "<span class=\"notranslate\" translate=\"no\">Modo P\u00e1nico</span> (<span class=\"notranslate\" translate=\"no\">SOS</span> / OK)",
    "ug_p3": "Una interfaz simplificada dise\u00f1ada para m\u00e1xima simplicidad y accesibilidad, ideal para usuarios mayores o situaciones de alto estr\u00e9s.",
    "ug_li2_1": "<strong>Bot\u00f3n <span class=\"notranslate\" translate=\"no\">SOS</span> Grande:</strong> Inicia instant\u00e1neamente la cuenta regresiva para una alerta de \"<span class=\"notranslate\" translate=\"no\">SOS</span>, necesito ayuda\".",
    "ug_li2_2": "<strong>Bot\u00f3n Estoy OK:</strong> Env\u00eda r\u00e1pidamente una actualizaci\u00f3n de estado de \"Estoy OK\" para tranquilizar a los contactos.",
    "ug_li2_3": "<strong>Botones de Voz:</strong> Cada secci\u00f3n tiene un bot\u00f3n dedicado de voz para grabar y enviar una transcripci\u00f3n de audio junto con el estado de <span class=\"notranslate\" translate=\"no\">SOS</span> u OK.",
    "ug_li2_4": "<strong>Bot\u00f3n de Llamada de Emergencia:</strong> Un bot\u00f3n dedicado para llamar inmediatamente a los servicios de emergencia locales (ej., 112, 911) bas\u00e1ndose en tu ubicaci\u00f3n.",
    "ug_h3_2": "Modo Reporte (Pesta\u00f1as)",
    "ug_p4": "El modo predeterminado, ofreciendo flexibilidad con m\u00faltiples tipos de mensajes.",
    "ug_li3_1": "<strong>4 Pesta\u00f1as de Mensajes:</strong> Preconfigura diferentes alertas (ej., \"M\u00e9dico\", \"Problema con el auto\", \"Gen\u00e9rico\").",
    "ug_li3_2": "<strong>Texto Personalizable:</strong> Toca dentro de la caja de mensaje para editar el contenido sobre la marcha.",
    "ug_li3_3": "<strong>Transcripci\u00f3n de Voz:</strong> Usa el micr\u00f3fono para dictar un mensaje personalizado.",
    "ug_h2_3": "3. \ud83d\udcdd Configurar Mensajes Predefinidos (Modo Reporte)",
    "ug_p5": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> viene con 4 espacios (pesta\u00f1as) de mensajes predefinidos permiti\u00e9ndote cambiar r\u00e1pidamente entre diferentes escenarios de alerta.",
    "ug_h3_3": "Editando Mensajes",
    "ug_li4_1": "<strong>Selecciona una Pesta\u00f1a:</strong> Toca en una de las pesta\u00f1as numeradas (1-3) en la parte superior.",
    "ug_li4_2": "<strong>Edita el Texto:</strong> Toca dentro de la caja de mensaje para escribir tu mensaje de alerta personalizado (ej., \"Emergencia M\u00e9dica\", \"Problema con el Auto\").",
    "ug_li4_3": "<strong>Autoguardado:</strong> Tus cambios se guardan autom\u00e1ticamente al escribir.",
    "ug_li4_4": "<strong>Dictado:</strong> Tambi\u00e9n puedes usar el icono de dictado para dictar tu mensaje.",
    "ug_h3_4": "\ud83c\udf99\ufe0f Mensaje de Alerta R\u00e1pida por Voz",
    "ug_p6": "Puedes usar tu voz para generar el texto de la alerta en tiempo real. Esto es \u00fatil para describir una situaci\u00f3n espec\u00edfica r\u00e1pidamente. El mensaje se guardar\u00e1 en la cuarta pesta\u00f1a.",
    "ug_li5_1": "<strong>Toca el bot\u00f3n rojo del Micr\u00f3fono:</strong> Comenzar\u00e1 a <strong>pulsar</strong> cuando est\u00e9 activo.",
    "ug_li5_2": "<strong>Habla tu mensaje:</strong> La barra de estado en la parte inferior se volver\u00e1 <strong>naranja claro</strong> y mostrar\u00e1 un s\u00edmbolo de onda de sonido mientras escucha.",
    "ug_li5_3": "<strong>Actualizaci\u00f3n Autom\u00e1tica y Env\u00edo Instant\u00e1neo:</strong> Despu\u00e9s de hablar o tocar el bot\u00f3n del micr\u00f3fono nuevamente, el texto del mensaje se actualizar\u00e1 y se activar\u00e1 el <strong>ENVIAR ALERTA</strong> inmediatamente. Tambi\u00e9n puedes presionar el bot\u00f3n de <strong>ENVIAR ALERTA</strong> directamente mientras grabas; la app detendr\u00e1 autom\u00e1ticamente la grabaci\u00f3n, y guardar\u00e1 y enviar\u00e1 el mensaje transcrito de inmediato.",
    "ug_h2_4": "4. \ud83d\udc65 Configurar/Gestionar Destinatarios",
    "ug_p7": "Esto se hace en la <strong>Pantalla de Destinatarios</strong> dedicada, accesible desde la barra superior de la Pantalla de Inicio:",
    "ug_li6_1": "<strong>Abrir Destinatarios:</strong> Toca el <strong>Icono de Personas/Grupo</strong> (\ud83d\udc65) en la barra de herramientas superior derecha.",
    "ug_li6_2_1": "<strong>A\u00f1adir N\u00famero:</strong>",
    "ug_li6_2_2": "Toca el bot\u00f3n <strong>\"A\u00f1adir\"</strong> para ingresar un n\u00famero de tel\u00e9fono manualmente.",
    "ug_li6_2_3": "Toca el <strong>Icono de Contacto</strong> para elegir un n\u00famero directamente de la libreta de direcciones de tu tel\u00e9fono.",
    "ug_li6_3": "<strong>Formato:</strong> Usa el <strong>formato internacional E.164</strong> (ej., <code>+34600000000</code>) para mejores resultados.",
    "ug_li6_4": "<strong>Eliminar:</strong> Toca el icono de eliminar al lado de cualquier n\u00famero en la lista para quitarlo. Tambi\u00e9n puedes \"Eliminar Todos\" usando el icono de papelera en la parte superior.",
    "ug_tip_1_1": "<strong>CONSEJO: \u00bfNo puedes ver todos tus contactos?</strong>",
    "ug_tip_1_2": "<strong>iOS:</strong> Si elegiste \"Seleccionar Contactos...\" (Acceso Limitado), la app solo puede ver los pocos que elegiste. Para arreglar esto, ve a <strong>Ajustes del iPhone > Privacidad y Seguridad > Contactos > <span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> y selecciona <strong>\"Todos los Contactos\"</strong>.",
    "ug_tip_1_3": "<strong>{{ android_table_th2 }}:</strong> Los permisos son \"todo o nada\". Si denegaste el acceso, el selector estar\u00e1 vac\u00edo. Aseg\u00farate de que la app tenga permiso de \"Contactos\" en los Ajustes de Apps de tu tel\u00e9fono.",
    "ug_h2_5": "5. \u2699\ufe0f Opciones de Configuraci\u00f3n",
    "ug_p8": "Accede al men\u00fa de ajustes mediante el icono de engranaje \u2699\ufe0f para personalizar a\u00fan m\u00e1s el texto del mensaje de alerta y el m\u00e9todo de entrega de SMS.",
    "ug_h3_5": "M\u00e9todos de Env\u00edo de SMS",
    "ug_p9": "La app soporta dos formas de enviar mensajes:",
    "ug_li7_1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ({{ android_table_th2 }}):</strong> Usa la tarjeta SIM de tu tel\u00e9fono. El costo depende de tu plan de operador m\u00f3vil.",
    "ug_li7_2": "<strong>SMS por <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> ({{ android_table_th2 }} e iOS):</strong> Usa la API de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> a trav\u00e9s de internet (Wi-Fi/Datos). Altamente confiable y requerido para iOS.",
    "ug_h3_6": "<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> (Solo {{ android_table_th2 }})",
    "ug_p10": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> cuenta con un sistema de <strong><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span></strong> que cambia autom\u00e1ticamente de m\u00e9todo si el principal falla:",
    "ug_li8_1": "<strong>\u00bfSin Se\u00f1al?</strong> Si intentas enviar un <span class=\"notranslate\" translate=\"no\">SMS Directo</span> pero no tienes cobertura celular (ej., dentro de un edificio), la app intentar\u00e1 autom\u00e1ticamente enviar v\u00eda <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Wi-Fi).",
    "ug_li8_2": "<strong>\u00bfSin Datos?</strong> Si usas <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> como principal pero est\u00e1s de excursi\u00f3n sin 4G/5G, la app autom\u00e1ticamente usar\u00e1 como <span class=\"notranslate\" translate=\"no\">respaldo</span> el env\u00edo de un <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span>.",
    "ug_p11": "<strong>Para habilitar:</strong> Ve a Ajustes y activa <strong>\"<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span>\"</strong>.",
    "ug_h3_7": "Respaldo por Email (Wi-Fi <span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span>)",
    "ug_p12": "Si no tienes se\u00f1al celular pero est\u00e1s conectado a Wi-Fi, <span class=\"notranslate\" translate=\"no\">TapAlert</span> puede enviar tu alerta por correo electr\u00f3nico.",
    "ug_li9_1": "<strong>Configuraci\u00f3n:</strong> Ve a <strong>Ajustes > Respaldo por Email</strong>. Para instrucciones detalladas, consulta el <strong>Cap\u00edtulo 6: Configurando el Respaldo por Email</strong>.",
    "ug_li9_2": "<strong><span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span> Autom\u00e1tica:</strong> Cuando est\u00e1 habilitado, la app intentar\u00e1 enviar una alerta por email si tanto <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> como <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (celular) fallan.",
    "ug_h3_8": "M\u00e9todo de Activaci\u00f3n (Tocar vs. Mantener)",
    "ug_p13": "Previene activaciones accidentales cambiando c\u00f3mo se activa la alerta en <strong>Ajustes > M\u00e9todo de Activaci\u00f3n</strong>:",
    "ug_li10_1": "<strong>Tocar para Enviar (Predeterminado):</strong> Un solo toque en el bot\u00f3n de alerta inicia la cuenta regresiva.",
    "ug_li10_2": "<strong>Presionar y Mantener (5s):</strong> Debes mantener presionado el bot\u00f3n de alerta durante 5 segundos continuos para iniciar la cuenta regresiva. Esto se recomienda para evitar falsas alarmas.",
    "ug_note_2": "<strong>IMPORTANTE: Usuarios de iOS</strong><br> Debes configurar una cuenta de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.<br> \ud83d\udc49 <strong>Para instrucciones detalladas de configuraci\u00f3n de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, por favor consulta la \"Gu\u00eda de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\" separada en el men\u00fa de Ayuda.</strong>",
    "ug_h3_9": "Auto-Inicio al Abrir",
    "ug_p14": "Inicia autom\u00e1ticamente la cuenta regresiva de la alerta inmediatamente cuando la app se abre.",
    "ug_li11_1": "<strong>\u00datil para:</strong> Crear un bot\u00f3n de p\u00e1nico f\u00edsico (usando la reasignaci\u00f3n de teclas de hardware) o un acceso directo de inicio r\u00e1pido.",
    "ug_li11_2": "<strong>Advertencia:</strong> Cuando est\u00e1 habilitado, abrir la app siempre activar\u00e1 la cuenta regresiva. Puedes cancelarla durante el per\u00edodo de retraso.",
    "ug_h3_10": "{{ ts_li1_5 }} del Mensaje",
    "ug_li12_1": "<strong>Incluir {{ ts_li1_5 }}:</strong> Agrega coordenadas GPS al mensaje.",
    "ug_li12_2": "<strong>Incluir Direcci\u00f3n:</strong> Intenta convertir las coordenadas en una direcci\u00f3n legible para humanos.",
    "ug_h3_11": "Ajustes Adicionales",
    "ug_li13_1": "<strong>Identidad del Remitente:</strong> (Solo <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>) Elige el nombre o n\u00famero que aparece como remitente (ej., \"Alerta\" o tu n\u00famero de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> espec\u00edfico).",
    "ug_li13_2": "<strong>Apariencia:</strong> Cambia entre Modo Claro, Modo Oscuro, o sigue los Ajustes del Sistema.",
    "ug_li13_3": "<strong>Idioma de la App:</strong> Anula manualmente el idioma de la app (predeterminado: Idioma del Sistema).",
    "ug_li13_4": "<strong>Regi\u00f3n y formato:</strong> Establece tu regi\u00f3n para asegurar que los n\u00fameros de tel\u00e9fono teng\u00e1n el formato correcto (ej., auto-agregar c\u00f3digos de pa\u00eds).",
    "ug_li13_5": "<strong>Sonido de notificaci\u00f3n:</strong> Elige el sonido de alerta que se reproduce despu\u00e9s de una entrega de mensaje exitosa."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<title>TapAlert - User Guide</title>", "<title>TapAlert - {{ ug_title }}</title>"),
    ("<h1 class=\"guide-title\">User Guide: <span class=\"notranslate\" translate=\"no\">TapAlert</span></h1>", "<h1 class=\"guide-title\">{{ ug_title }}: <span class=\"notranslate\" translate=\"no\">TapAlert</span></h1>"),
    ("<p class=\"guide-intro\">This guide explains how to configure and use <strong><span class=\"notranslate\"\n                    translate=\"no\">TapAlert</span></strong> on your {{ android_table_th2 }} or\n            iOS device.</p>", "<p class=\"guide-intro\">{{ ug_intro }}</p>"),

    ("<h2>1. 🛡️ Required Permissions</h2>", "<h2>{{ ug_h2_1 }}</h2>"),
    ("<p>Upon first launch, the app will request the following permissions:</p>", "<p>{{ ug_p1 }}</p>"),
    ("<li><strong>SMS ({{ android_table_th2 }} Only):</strong> Needed to send direct messages from your phone's SIM card.</li>", "<li>{{ ug_li1_1 }}</li>"),
    ("<li><strong>{{ ts_li1_5 }}:</strong> Needed to include your GPS coordinates in the alert message.</li>", "<li>{{ ug_li1_2 }}</li>"),
    ("<li><strong>Microphone:</strong> Needed if you use the voice recording feature to transcribe your alert\n                    message.</li>", "<li>{{ ug_li1_3 }}</li>"),
    ("<li><strong>{{ sms_so_li1_2 }}:</strong> Needed to easily select recipients from your phone's address book.</li>", "<li>{{ ug_li1_4 }}</li>"),
    ("<strong>NOTE:</strong> On iOS, <span class=\"notranslate\" translate=\"no\">direct SMS</span> sending is not\n                supported by the system for automated alerts.\n                You {{ ts_em_li5 }} use the <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong> method.", "{{ ug_note_1 }}"),

    ("<h2>2. 📱 Interface Modes</h2>", "<h2>{{ ug_h2_2 }}</h2>"),
    ("<p><span class=\"notranslate\" translate=\"no\">TapAlert</span> offers two distinct interface modes to suit your\n                needs. You can switch between them in\n                <strong>Settings > Interface Mode</strong>.\n            </p>", "<p>{{ ug_p2 }}</p>"),
    ("<h3><span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\"\n                    translate=\"no\">SOS</span> / OK)</h3>", "<h3>{{ ug_h3_1 }}</h3>"),
    ("<p>A streamlined interface designed for maximum simplicity and accessibility, ideal for elderly users or\n                high-stress situations.</p>", "<p>{{ ug_p3 }}</p>"),
    ("<li><strong>Large <span class=\"notranslate\" translate=\"no\">SOS</span> Button:</strong> Instantly starts\n                    the countdown for an \"<span class=\"notranslate\" translate=\"no\">SOS</span>, I need help\" alert.\n                </li>", "<li>{{ ug_li2_1 }}</li>"),
    ("<li><strong>I'm OK Button:</strong> Quickly sends an \"I'm OK\" status update to reassure contacts.</li>", "<li>{{ ug_li2_2 }}</li>"),
    ("<li><strong>Voice Buttons:</strong> Each section h{{ qa_step3_p5 }} dedicated voice{{ phil_sen_li2 }} to record and send an\n                    audio transcript along with the <span class=\"notranslate\" translate=\"no\">SOS</span> or OK status.\n                </li>", "<li>{{ ug_li2_3 }}</li>"),
    ("<li><strong>Emergency Call Button:</strong> A dedicated{{ phil_sen_li2 }} to immediately call local emergency\n                    services (e.g., 112, 911) based on your location.</li>", "<li>{{ ug_li2_4 }}</li>"),
    ("<h3>Report Mode (Tabs)</h3>", "<h3>{{ ug_h3_2 }}</h3>"),
    ("<p>The default mode, offering flexibility with multiple message types.</p>", "<p>{{ ug_p4 }}</p>"),
    ("<li><strong>4 Message Tabs:</strong> Pre-configure different alerts (e.g., \"Medical\", \"Car Trouble\",\n                    \"Generic\").</li>", "<li>{{ ug_li3_1 }}</li>"),
    ("<li><strong>Customizable Text:</strong> Tap inside the message box to edit content on the fly.</li>", "<li>{{ ug_li3_2 }}</li>"),
    ("<li><strong>Voice Transcription:</strong> Use the microphone to dictate a custom message.</li>", "<li>{{ ug_li3_3 }}</li>"),

    ("<h2>3. 📝 Setup Predefined Messages (Report Mode)</h2>", "<h2>{{ ug_h2_3 }}</h2>"),
    ("<p><span class=\"notranslate\" translate=\"no\">TapAlert</span> comes with 4 predefined message slots (tabs)\n                allowing you to quickly switch between different\n                alert scenarios.</p>", "<p>{{ ug_p5 }}</p>"),
    ("<h3>{{ sms_ios_li1 }}ing Messages</h3>", "<h3>{{ ug_h3_3 }}</h3>"),
    ("<li><strong>{{ ts_loc_li2 }} a Tab:</strong> Tap on one of the numbered tabs (1-3) at the top.</li>", "<li>{{ ug_li4_1 }}</li>"),
    ("<li><strong>{{ sms_ios_li1 }} Text:</strong> Tap inside the message box to type your custom alert message (e.g.,\n                    \"Medical Emergency\", \"Car Trouble\").</li>", "<li>{{ ug_li4_2 }}</li>"),
    ("<li><strong>Auto-Save:</strong> Your changes are saved automatically as you type.</li>", "<li>{{ ug_li4_3 }}</li>"),
    ("<li><strong>Dictation:</strong> You can also use the dictation icon to dictate your message.</li>", "<li>{{ ug_li4_4 }}</li>"),
    ("<h3>🎙️ Voice Quick Alert Message</h3>", "<h3>{{ ug_h3_4 }}</h3>"),
    ("<p>You can use your voice to generate the alert text in real-time. This is useful for describing a specific\n                situation quickly. The message will be saved on the 4th tab.</p>", "<p>{{ ug_p6 }}</p>"),
    ("<li><strong>Tap the Microphone red{{ phil_sen_li2 }}:</strong> It will start <strong>pulsing</strong> when active.\n                </li>", "<li>{{ ug_li5_1 }}</li>"),
    ("<li><strong>Speak your message:</strong> The status bar at the bottom will turn <strong>light\n                        orange</strong> and show a sound wave symbol while listening.</li>", "<li>{{ ug_li5_2 }}</li>"),
    ("<li><strong>Automatic Update and Instant Send:</strong> After speaking or tapping the microphone{{ phil_sen_li2 }}\n                    again, the message text will be updated and the <strong>SEND ALERT</strong> will be triggered\n                    immediately. You can also press the <strong>SEND ALERT</strong>{{ phil_sen_li2 }} directly while recording; the\n                    app will automatically stop the recording and save and send the transcribed message immediately.\n                </li>", "<li>{{ ug_li5_3 }}</li>"),

    ("<h2>4. 👥 Setup/Managing Recipients</h2>", "<h2>{{ ug_h2_4 }}</h2>"),
    ("<p>This is done in the dedicated <strong>Recipients Screen</strong>, accessible from the top bar of the Home\n                Screen:</p>", "<p>{{ ug_p7 }}</p>"),
    ("<li><strong>Open Recipients:</strong> Tap the <strong>People/Group Icon</strong> (👥) in the top-right\n                    toolbar.</li>", "<li>{{ ug_li6_1 }}</li>"),
    ("<li><strong>Add Number:</strong>\n                    <ul>\n                        <li>Tap the <strong>\"Add\"</strong>{{ phil_sen_li2 }} to manually enter a phone number.</li>\n                        <li>Tap the <strong>{{ nav_contact }} Icon</strong> to pick a number directly from your phone's address\n                            book.</li>\n                    </ul>\n                </li>", "<li>{{ ug_li6_2_1 }}\n                    <ul>\n                        <li>{{ ug_li6_2_2 }}</li>\n                        <li>{{ ug_li6_2_3 }}</li>\n                    </ul>\n                </li>"),
    ("<li><strong>Format:</strong> Use the <strong>E.164 international format</strong> (e.g.,\n                    <code>+34600000000</code>) for best results.\n                </li>", "<li>{{ ug_li6_3 }}</li>"),
    ("<li><strong>Remove:</strong> Tap the delete icon next to any number in the list to remove it. You can\n                    also \"Delete All\" using the trash bin icon at the top.</li>", "<li>{{ ug_li6_4 }}</li>"),
    ("<strong>TIP: Can't see all your contacts?</strong>", "{{ ug_tip_1_1 }}"),
    ("<li><strong>iOS:</strong> If you chose \"{{ ts_loc_li2 }} {{ sms_so_li1_2 }}...\" (Limited Access), the app can only see\n                        the few you picked. To fix this, go to <strong>iPhone Settings > {{ table_r2c1 }} & Security > {{ sms_so_li1_2 }} >\n                            <span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> and select <strong>\"All\n                            {{ sms_so_li1_2 }}\"</strong>.</li>", "<li>{{ ug_tip_1_2 }}</li>"),
    ("<li><strong>{{ android_table_th2 }}:</strong> Permissions are \"all-or-nothing\". If you denied access, the picker\n                        will be empty. {{ sms_and_li6 }} the app has \"{{ sms_so_li1_2 }}\" permission in your phone's App Settings.</li>", "<li>{{ ug_tip_1_3 }}</li>"),

    ("<h2>5. ⚙️ Configuration Options</h2>", "<h2>{{ ug_h2_5 }}</h2>"),
    ("<p>Access the settings menu via the gear icon ⚙️ to further customize the alert message text and the SMS\n                delivery method.</p>", "<p>{{ ug_p8 }}</p>"),
    ("<h3>SMS Sending Methods</h3>", "<h3>{{ ug_h3_5 }}</h3>"),
    ("<p>The app supports two ways to send messages:</p>", "<p>{{ ug_p9 }}</p>"),
    ("<li><strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ({{ android_table_th2 }}):</strong> Uses your\n                    phone's SIM card. Cost depends on your mobile\n                    carrier plan.</li>", "<li>{{ ug_li7_1 }}</li>"),
    ("<li><strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS ({{ android_table_th2 }} & iOS):</strong> Uses\n                    the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API over the internet (Wi-Fi/Data).\n                    {{ feature_reliable }} and required for iOS.</li>", "<li>{{ ug_li7_2 }}</li>"),
    ("<h3><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> ({{ android_table_th2 }} Only)</h3>", "<h3>{{ ug_h3_6 }}</h3>"),
    ("<p><span class=\"notranslate\" translate=\"no\">TapAlert</span> {{ price_features }} a <strong><span class=\"notranslate\"\n                        translate=\"no\">{{ phil_red_title }}</span></strong> system that automatically switches methods if\n                the\n                primary one fails:</p>", "<p>{{ ug_p10 }}</p>"),
    ("<li><strong>No Signal?</strong> If you try to send a <span class=\"notranslate\" translate=\"no\">Direct\n                        SMS</span> but have no cellular coverage (e.g.,\n                    inside a building), the app will automatically attempt to send via <span class=\"notranslate\"\n                        translate=\"no\">{{ term_twilio }}</span> (Wi-Fi).</li>", "<li>{{ ug_li8_1 }}</li>"),
    ("<li><strong>No Data?</strong> If you use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> as\n                    primary but are hiking {{ ts_loc_li7 }} 4G/5G, the app will\n                    automatically <span class=\"notranslate\" translate=\"no\">fallback</span> to sending a <span\n                        class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span>.</li>", "<li>{{ ug_li8_2 }}</li>"),
    ("<p><strong>To enable:</strong> Go to Settings and turn on <strong>\"<span class=\"notranslate\"\n                        translate=\"no\">{{ phil_red_title }}</span>\"</strong>.</p>", "<p>{{ ug_p11 }}</p>"),
    ("<h3>Email Redundancy (Wi-Fi <span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span>)</h3>", "<h3>{{ ug_h3_7 }}</h3>"),
    ("<p>If you have no cellular signal but are connected to Wi-Fi, <span class=\"notranslate\"\n                    translate=\"no\">TapAlert</span> can send your alert via email.</p>", "<p>{{ ug_p12 }}</p>"),
    ("<li><strong>Setup:</strong> Go to <strong>Settings > Email Redundancy</strong>. For detailed\n                    instructions, see <strong>Chapter 6: Configuring Email Redundancy</strong>.</li>", "<li>{{ ug_li9_1 }}</li>"),
    ("<li><strong>Automatic <span class=\"notranslate\" translate=\"no\">{{ plat_int_2 }}</span>:</strong> When enabled,\n                    the app will attempt to send an email alert if\n                    both <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> and <span class=\"notranslate\"\n                        translate=\"no\">{{ term_twilio }}</span> (cellular) fail.</li>", "<li>{{ ug_li9_2 }}</li>"),
    ("<h3>Trigger Method (Tap vs. Hold)</h3>", "<h3>{{ ug_h3_8 }}</h3>"),
    ("<p>Prevent accidental triggers by changing how the alert is activated in <strong>Settings > Trigger\n                    Method</strong>:</p>", "<p>{{ ug_p13 }}</p>"),
    ("<li><strong>Tap to Send (Default):</strong> A single tap on the alert{{ phil_sen_li2 }} triggers the countdown.\n                </li>", "<li>{{ ug_li10_1 }}</li>"),
    ("<li><strong>Press & Hold (5s):</strong> You {{ ts_em_li5 }} hold the alert{{ phil_sen_li2 }} for 5 continuous seconds to\n                    trigger the countdown. This is recommended to avoid false alarms.</li>", "<li>{{ ug_li10_2 }}</li>"),
    ("<strong>IMPORTANT: iOS Users</strong><br>\n                You {{ ts_em_li5 }} configure a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }}.<br>\n                👉 <strong>For detailed <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> setup instructions,\n                    please see the separate \"<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Guide\" in the Help\n                    menu.</strong>", "{{ ug_note_2 }}"),
    ("<h3>Auto-Start on Launch</h3>", "<h3>{{ ug_h3_9 }}</h3>"),
    ("<p>Automatically start the alert countdown immediately when the app opens.</p>", "<p>{{ ug_p14 }}</p>"),
    ("<li><strong>Useful for:</strong> Creating a physical panic{{ phil_sen_li2 }} (using hardware key remapping) or a\n                    quick-launch shortcut.</li>", "<li>{{ ug_li11_1 }}</li>"),
    ("<li><strong>Warning:</strong> When enabled, opening the app will always trigger the countdown. You can\n                    cancel it during the delay period.</li>", "<li>{{ ug_li11_2 }}</li>"),
    ("<h3>Message {{ ts_li1_5 }}</h3>", "<h3>{{ ug_h3_10 }}</h3>"),
    ("<li><strong>Include {{ ts_li1_5 }}:</strong> Append GPS coordinates to the message.</li>", "<li>{{ ug_li12_1 }}</li>"),
    ("<li><strong>Include Address:</strong> Attempt to convert coordinates into a human-readable address.</li>", "<li>{{ ug_li12_2 }}</li>"),
    ("<h3>Additional Settings</h3>", "<h3>{{ ug_h3_11 }}</h3>"),
    ("<li><strong>Sender Identity:</strong> (<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Only)\n                    Choose the name or number that appears as the sender\n                    (e.g., \"Alert\" or your specific <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> number).</li>", "<li>{{ ug_li13_1 }}</li>"),
    ("<li><strong>Appearance:</strong> Toggle between Light Mode, Dark Mode, or follow System Settings.</li>", "<li>{{ ug_li13_2 }}</li>"),
    ("<li><strong>App {{ guide_lang }}:</strong> Manually override the app's language (default: System {{ guide_lang }}).</li>", "<li>{{ ug_li13_3 }}</li>"),
    ("<li><strong>Region and formatting:</strong> Set your region to ensure phone numbers are formatted\n                    correctly (e.g., auto-adding country codes).</li>", "<li>{{ ug_li13_4 }}</li>"),
    ("<li><strong>Notification sound:</strong> Choose the alert sound that plays after a successful message\n                    delivery.</li>", "<li>{{ ug_li13_5 }}</li>")
]

replace_in_file('src/user_guide.html', replacements)
print("Updated user_guide.html (part 1)")
