import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        en[k] = v
    for k, v in new_es.items():
        es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "trouble_p1": "This guide covers common issues and solutions for <span class=\"notranslate\" translate=\"no\">TapAlert</span> on both {{ android_table_th2 }} and iOS.",
    "trouble_toc_h": "Jump to Section:",
    "trouble_toc_1": "1. SMS Issues",
    "trouble_toc_2": "2. Email Issues",
    "trouble_toc_3": "3. {{ ts_li1_5 }} Issues",
    "trouble_toc_4": "4. Connectivity",
    "trouble_toc_5": "5. Check-in Timer",
    "trouble_toc_6": "6. Voice-to-Text",
    "trouble_toc_7": "7. {{ sms_so_li1_2 }}",
    "trouble_toc_8": "8. Purchases",
    "trouble_toc_9": "9. Widgets",
    "trouble_toc_10": "10. {{ sms_and_li2 }}",
    "trouble_toc_11": "11. App Behavior",
    "trouble_toc_12": "12. iOS Specific",
    "trouble_toc_13": "13. {{ android_table_th2 }} Specific",
    "trouble_toc_14": "14. General Tips",
    "trouble_h2_1": "1. SMS Sending Issues",
    "trouble_h3_1_1": "1.1 <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> Not Sending ({{ android_table_th2 }})",
    "trouble_p_1_1": "<strong>Symptom:</strong> You tap \"Send Alert\" but the SMS fails. The alert history shows an error for one or more recipients.",
    "trouble_li_1_1_1": "<strong>No cellular signal:</strong> Check the status bar. The Status page in the app shows your current cellular status.",
    "trouble_li_1_1_2": "<strong>No SIM card:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> requires a working SIM card. Check SIM status on the Status page.",
    "trouble_li_1_1_3": "<strong>Permissions:</strong> {{ sms_and_li6 }} <strong>SMS</strong> permission is allowed in phone settings.",
    "trouble_li_1_1_4": "<strong>Invalid format:</strong> Use international format with country code (e.g., +34600123456).",
    "trouble_h3_1_2": "1.2 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS Not Sending",
    "trouble_p_1_2": "<strong>Symptom:</strong> Alert fails with a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> error message.",
    "trouble_li_1_2_1": "<strong>Internet required:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> needs Wi-Fi or cellular data.",
    "trouble_li_1_2_2": "<strong>Credentials:</strong> Verify Account SID, Auth Token, and <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> phone number in Settings.",
    "trouble_li_1_2_3": "<strong>Trial limitations:</strong> Trial {{ qa_step3_p4 }}s can only send to {{ ts_tw_li7 }} phone numbers.",
    "trouble_li_1_2_4": "<strong>Balance:</strong> Check your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} balance.",
    "trouble_h3_1_3": "1.3 iOS SMS Composer Issues",
    "trouble_p_1_3": "<strong>Symptom:</strong> On iPhone, the SMS composer opens but the message doesn't get delivered.",
    "trouble_li_1_3_1": "<strong>Signal:</strong> The Messages app needs cellular signal (or WiFi Calling if active).",
    "trouble_li_1_3_2": "<strong>Cancellation:</strong> If you tap Cancel in the composer, the alert is cancelled.",
    "trouble_li_1_3_3": "<strong>Invalid number:</strong> iOS will queue the message and fail silently. Check the Messages app for red exclamation marks.",
    "trouble_h2_2": "2. Email Redundancy Issues",
    "trouble_h3_2_1": "2.1 Email Test Fails",
    "trouble_li_2_1_1": "<strong>SMTP Settings:</strong> Verify host and port (Gmail/iCloud use 587).",
    "trouble_li_2_1_2": "<strong>App Password:</strong> Most providers require an <strong>App Password</strong> if 2FA is enabled.",
    "trouble_li_2_1_3": "<strong>Internet:</strong> Email requires an active data connection.",
    "trouble_h2_3": "3. {{ ts_li1_5 }} Issues",
    "trouble_h3_3_1": "3.1 {{ ts_li1_5 }} Missing in Alert",
    "trouble_li_3_1_1": "<strong>Permissions:</strong> {{ sms_and_li6 }} {{ ts_li1_5 }} permission is set to \"While Using\" or \"Always\".",
    "trouble_li_3_1_2": "<strong>GPS Disabled:</strong> Verify phone location services are turned on.",
    "trouble_li_3_1_3": "<strong>Reception:</strong> Indoors or dense areas may cause a GPS timeout.",
    "trouble_h2_4": "4. Connectivity and Status",
    "trouble_h3_4_2": "4.2 Shield Icon Meanings",
    "trouble_li_4_2_1": "<strong>Green:</strong> Ready for reliable SMS/<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> delivery.",
    "trouble_li_4_2_2": "<strong>Orange:</strong> Uncertain. WiFi only, no <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. WiFi Calling might work.",
    "trouble_li_4_2_3": "<strong>Red:</strong> Disconnected. Both cellular and WiFi are off.",
    "trouble_h2_5": "5. Check-in Timer Issues",
    "trouble_h3_5_1": "5.1 Timer Doesn't Fire",
    "trouble_li_5_1_1": "<strong>App Closed:</strong> Avoid force-closing the app. On iOS, you {{ ts_em_li5 }} tap the notification to trigger.",
    "trouble_li_5_1_2": "<strong>Battery Optimization:</strong> Set <span class=\"notranslate\" translate=\"no\">TapAlert</span> to \"Unrestricted\" in {{ android_table_th2 }} battery settings.",
    "trouble_li_5_1_3": "<strong>{{ sms_and_li2 }}:</strong> {{ sms_and_li6 }} notification permissions are granted.",
    "trouble_h2_6": "6. Voice-to-Text Issues",
    "trouble_h3_6_1": "6.1 Voice Recognition Not Working",
    "trouble_li_6_1_1": "<strong>Permissions:</strong> {{ sms_and_li6 }} <strong>Microphone</strong> and <strong>Speech Recognition</strong> (iOS) permissions are granted.",
    "trouble_li_6_1_2": "<strong>Internet:</strong> Most recognition engines require an active connection for processing.",
    "trouble_li_6_1_3": "<strong>Wrong {{ guide_lang }}:</strong> The recognition uses the app's current language setting. Check **Settings > {{ guide_lang }}**.",
    "trouble_h2_7": "7. {{ sms_so_li1_2 }} and Recipients Issues",
    "trouble_h3_7_1": "7.1 Cannot See {{ sms_so_li1_2 }}",
    "trouble_li_7_1_1": "<strong>iOS Limited Access:</strong> If you previously chose \"{{ ts_loc_li2 }} {{ sms_so_li1_2 }}...\", go to **Settings > {{ table_r2c1 }} & Security > {{ sms_so_li1_2 }} > <span class=\"notranslate\" translate=\"no\">TapAlert</span>** and change to **\"All {{ sms_so_li1_2 }}\"**.",
    "trouble_li_7_1_2": "<strong>{{ android_table_th2 }} Permissions:</strong> {{ sms_and_li6 }} **{{ sms_so_li1_2 }}** permission is set to \"Allow\" in system settings.",
    "trouble_li_7_1_3": "<strong>Format:</strong> {{ sms_and_li6 }} numbers include the country code with a **+** prefix.",
    "trouble_h2_8": "8. In-App Purchase Issues",
    "trouble_h3_8_2": "8.2 Purchased But Still Shows {{ price_free_title }}",
    "trouble_li_8_2_1": "<strong>Restore Purchases:</strong> In the Upgrade screen, tap the **Restore**{{ phil_sen_li2 }} to re-validate your purchase with the store.",
    "trouble_li_8_2_2": "<strong>Same Account:</strong> {{ sms_and_li6 }} you're signed in with the same store {{ qa_step3_p4 }} used for the original purchase.",
    "trouble_h2_9": "9. Widget Issues ({{ android_table_th2 }})",
    "trouble_h3_9_1": "9.1 Widget Not Appearing",
    "trouble_li_9_1_1": "<strong>Manual Add:</strong> Try adding the widget from **Settings > Widget > Add** within the app if it doesn't appear in the system widget picker.",
    "trouble_li_9_1_2": "<strong>Battery Optimization:</strong> Aggressive optimization may prevent the widget from launching the app correctly.",
    "trouble_h2_10": "10. Notification Issues",
    "trouble_h3_10_2": "10.2 Recipients Not Noticing Calls/SMS",
    "trouble_li_10_2_1": "<strong>iPhone:</strong> Have recipients enable **{{ sms_so_bypass }}** for your contact number.",
    "trouble_li_10_2_2": "<strong>{{ android_table_th2 }}:</strong> Have recipients set notification priority to **{{ sms_and_li4 }}** or **{{ sms_and_li5 }}** for your messages.",
    "trouble_h2_11": "11. App Behavior Issues",
    "trouble_h3_11_1": "11.1 Alert Fires Immediately on Open",
    "trouble_p_11_1": "Go to **Settings** and disable **\"Auto-Start on Launch\"**. This feature is intended for physical panic{{ phil_sen_li2 }}s.",
    "trouble_h2_12": "12. iOS-Specific Issues",
    "trouble_h3_12_1": "12.1 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> vs. {{ term_ios_messages }}",
    "trouble_li_12_1_1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Automatic):</strong> Silent background sending, requires internet.",
    "trouble_li_12_1_2": "<strong>{{ term_ios_messages }} (Manual):</strong> Requires you to tap Send in the composer, works via cellular.",
    "trouble_h2_13": "13. {{ android_table_th2 }}-Specific Issues",
    "trouble_h3_13_1": "13.1 Battery Optimization",
    "trouble_p_13_1": "Some manufacturers (Xiaomi, Samsung, Huawei) require manual steps to prevent the app from being killed in the background. Check your phone's battery settings for **\"No restrictions\"**.",
    "trouble_h2_14": "14. General Tips",
    "trouble_h4_14_1": "✅ Before an Emergency",
    "trouble_li_14_1": "Send a test alert to verify setup.",
    "trouble_li_14_2": "Check the Status page for connectivity.",
    "trouble_li_14_3": "{{ sms_and_li6 }} all permissions are granted."
}

es_keys = {
    "trouble_p1": "Esta gu&iacute;a cubre problemas comunes y soluciones para <span class=\"notranslate\" translate=\"no\">TapAlert</span> tanto en {{ android_table_th2 }} como en iOS.",
    "trouble_toc_h": "Saltar a la Secci&oacute;n:",
    "trouble_toc_1": "1. Problemas de SMS",
    "trouble_toc_2": "2. Problemas de Email",
    "trouble_toc_3": "3. Problemas de {{ ts_li1_5 }}",
    "trouble_toc_4": "4. Conectividad",
    "trouble_toc_5": "5. Temporizador",
    "trouble_toc_6": "6. Voz a Texto",
    "trouble_toc_7": "7. {{ sms_so_li1_2 }}",
    "trouble_toc_8": "8. Compras",
    "trouble_toc_9": "9. Widgets",
    "trouble_toc_10": "10. {{ sms_and_li2 }}",
    "trouble_toc_11": "11. Comportamiento de App",
    "trouble_toc_12": "12. Espec&iacute;fico de iOS",
    "trouble_toc_13": "13. Espec&iacute;fico de {{ android_table_th2 }}",
    "trouble_toc_14": "14. Consejos Generales",
    "trouble_h2_1": "1. Problemas al Enviar SMS",
    "trouble_h3_1_1": "1.1 <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> No Env&iacute;a ({{ android_table_th2 }})",
    "trouble_p_1_1": "<strong>S&iacute;ntoma:</strong> Tocas \"Enviar Alerta\" pero el SMS falla. El historial de alertas muestra un error para uno o m&aacute;s destinatarios.",
    "trouble_li_1_1_1": "<strong>Sin se&ntilde;al celular:</strong> Revisa la barra de estado. La p&aacute;gina de Estado en la app muestra tu estado celular actual.",
    "trouble_li_1_1_2": "<strong>Sin tarjeta SIM:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> requiere una tarjeta SIM funcional. Revisa el estado de la SIM en la p&aacute;gina de Estado.",
    "trouble_li_1_1_3": "<strong>Permisos:</strong> {{ sms_and_li6 }} que el permiso de <strong>SMS</strong> est&eacute; permitido en los ajustes del tel&eacute;fono.",
    "trouble_li_1_1_4": "<strong>Formato inv&aacute;lido:</strong> Usa el formato internacional con c&oacute;digo de pa&iacute;s (ej. +34600123456).",
    "trouble_h3_1_2": "1.2 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS No Env&iacute;a",
    "trouble_p_1_2": "<strong>S&iacute;ntoma:</strong> La alerta falla con un mensaje de error de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.",
    "trouble_li_1_2_1": "<strong>Internet requerido:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> necesita Wi-Fi o datos celulares.",
    "trouble_li_1_2_2": "<strong>Credenciales:</strong> Verifica el Account SID, el Auth Token y el n&uacute;mero de tel&eacute;fono de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> en los Ajustes.",
    "trouble_li_1_2_3": "<strong>Limitaciones de prueba:</strong> Las {{ qa_step3_p4 }}s de prueba s&oacute;lo pueden enviar a n&uacute;meros {{ ts_tw_li7 }}.",
    "trouble_li_1_2_4": "<strong>Saldo:</strong> Revisa el saldo de tu {{ qa_step3_p4 }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.",
    "trouble_h3_1_3": "1.3 Problemas con el Redactor SMS en iOS",
    "trouble_p_1_3": "<strong>S&iacute;ntoma:</strong> En iPhone, el redactor de SMS se abre pero el mensaje no se entrega.",
    "trouble_li_1_3_1": "<strong>Se&ntilde;al:</strong> La aplicaci&oacute;n de Mensajes necesita se&ntilde;al celular (o llamadas por WiFi si est&aacute; activo).",
    "trouble_li_1_3_2": "<strong>Cancelaci&oacute;n:</strong> Si tocas Cancelar en el redactor, la alerta se cancela.",
    "trouble_li_1_3_3": "<strong>N&uacute;mero inv&aacute;lido:</strong> iOS pondr&aacute; el mensaje en cola y fallar&aacute; silenciosamente. Revisa la aplicaci&oacute;n de Mensajes en busca de marcas de exclamaci&oacute;n rojas.",
    "trouble_h2_2": "2. Problemas con Email como Respaldo",
    "trouble_h3_2_1": "2.1 Falla la Prueba de Email",
    "trouble_li_2_1_1": "<strong>Ajustes SMTP:</strong> Verifica el host y puerto (Gmail/iCloud usan 587).",
    "trouble_li_2_1_2": "<strong>Contrase&ntilde;a de App:</strong> La mayor&iacute;a de proveedores requieren una <strong>Contrase&ntilde;a de App</strong> si la verificaci&oacute;n en dos pasos est&aacute; habilitada.",
    "trouble_li_2_1_3": "<strong>Internet:</strong> El correo electr&oacute;nico requiere una conexi&oacute;n de datos activa.",
    "trouble_h2_3": "3. Problemas con la {{ ts_li1_5 }}",
    "trouble_h3_3_1": "3.1 La {{ ts_li1_5 }} Falta en la Alerta",
    "trouble_li_3_1_1": "<strong>Permisos:</strong> {{ sms_and_li6 }} el permiso de {{ ts_li1_5 }} a \"Mientras la usas\" o \"Siempre\".",
    "trouble_li_3_1_2": "<strong>GPS Desactivado:</strong> Verifica que los servicios de ubicaci&oacute;n de tu tel&eacute;fono est&eacute;n encendidos.",
    "trouble_li_3_1_3": "<strong>Recepci&oacute;n:</strong> En interiores o &aacute;reas densas podr&iacute;an causar un tiempo de espera excedido en el GPS.",
    "trouble_h2_4": "4. Conectividad y Estado",
    "trouble_h3_4_2": "4.2 Significado del Icono de Escudo",
    "trouble_li_4_2_1": "<strong>Verde:</strong> Listo para un env&iacute;o confiable v&iacute;a SMS/<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.",
    "trouble_li_4_2_2": "<strong>Naranja:</strong> Incierto. S&oacute;lo Wi-Fi, sin <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. Llamadas v&iacute;a Wi-Fi podr&iacute;a funcionar.",
    "trouble_li_4_2_3": "<strong>Rojo:</strong> Desconectado. Tanto celular como Wi-Fi est&aacute;n apagados.",
    "trouble_h2_5": "5. Problemas con el Temporizador",
    "trouble_h3_5_1": "5.1 El Temporizador no se Activa",
    "trouble_li_5_1_1": "<strong>Aplicaci&oacute;n Cerrada:</strong> Evita forzar el cierre de la aplicaci&oacute;n. En iOS, t&uacute; {{ ts_em_li5 }} tocar la notificaci&oacute;n para activarla.",
    "trouble_li_5_1_2": "<strong>Optimizaci&oacute;n de Bater&iacute;a:</strong> Pon <span class=\"notranslate\" translate=\"no\">TapAlert</span> en modo \"Sin restricciones\" en los ajustes de la bater&iacute;a de {{ android_table_th2 }}.",
    "trouble_li_5_1_3": "<strong>{{ sms_and_li2 }}:</strong> {{ sms_and_li6 }} que los permisos est&eacute;n concedidos.",
    "trouble_h2_6": "6. Problemas con Voz a Texto",
    "trouble_h3_6_1": "6.1 El Reconocimiento de Voz No Funciona",
    "trouble_li_6_1_1": "<strong>Permisos:</strong> {{ sms_and_li6 }} se hayan concedido los permisos de <strong>Micr&oacute;fono</strong> y <strong>Reconocimiento de Voz</strong> (iOS).",
    "trouble_li_6_1_2": "<strong>Internet:</strong> La mayor&iacute;a de mecanismos de reconocimiento requieren conexi&oacute;n activa a datos.",
    "trouble_li_6_1_3": "<strong>Idioma Equivocado:</strong> El reconocimiento usa la configuraci&oacute;n del idioma actual de la app. Revisa **Configuraci&oacute;n > {{ guide_lang }}**.",
    "trouble_h2_7": "7. Problemas con {{ sms_so_li1_2 }}",
    "trouble_h3_7_1": "7.1 No Puedo Ver Mis Contactos",
    "trouble_li_7_1_1": "<strong>Acceso Limitado de iOS:</strong> Si elegiste \"Seleccionar Contactos...\" anteriormente, ve a **Ajustes > {{ table_r2c1 }} y Seguridad > Contactos > <span class=\"notranslate\" translate=\"no\">TapAlert</span>** y cambia a **\"Todos los Contactos\"**.",
    "trouble_li_7_1_2": "<strong>Permisos de {{ android_table_th2 }}:</strong> {{ sms_and_li6 }} de que el permiso de **{{ sms_so_li1_2 }}** est&eacute; \"Permitido\" en los ajustes de sistema.",
    "trouble_li_7_1_3": "<strong>Formato:</strong> {{ sms_and_li6 }} que los n&uacute;meros incluyan el c&oacute;digo del pa&iacute;s con el prefijo **+**.",
    "trouble_h2_8": "8. Problemas con Compras",
    "trouble_h3_8_2": "8.2 Comprado pero a&uacute;n se ve {{ price_free_title }}",
    "trouble_li_8_2_1": "<strong>Restaurar Compras:</strong> En la secci&oacute;n para ascender de categor&iacute;a, toca el bot&oacute;n **Restaurar** para volver a validar tu compra.",
    "trouble_li_8_2_2": "<strong>Misma Cuenta:</strong> {{ sms_and_li6 }} que la sesi&oacute;n iniciada sea por el respectivo usuario que la cre&oacute;.",
    "trouble_h2_9": "9. Problemas de Widget ({{ android_table_th2 }})",
    "trouble_h3_9_1": "9.1 El Widget No Aparece",
    "trouble_li_9_1_1": "<strong>A&ntilde;adir Manualmente:</strong> Intenta a&ntilde;adir el widget desde **Ajustes > Widget > A&ntilde;adir** dentro de la aplicaci&oacute;n si no aparece en el selector.",
    "trouble_li_9_1_2": "<strong>Optimizaci&oacute;n de la Bater&iacute;a:</strong> La intervenci&oacute;n del sistema estricto impedir&aacute; su despliegue.",
    "trouble_h2_10": "10. Problemas de {{ sms_and_li2 }}",
    "trouble_h3_10_2": "10.2 Los Destinatarios No Notan Llamadas/SMS",
    "trouble_li_10_2_1": "<strong>iPhone:</strong> P&iacute;dele a los destinatarios que habiliten **{{ sms_so_bypass }}** en tus notificaciones.",
    "trouble_li_10_2_2": "<strong>{{ android_table_th2 }}:</strong> Que los destinatarios configuren la prioridad a **Alta** para tus mensajes.",
    "trouble_h2_11": "11. Problemas de Comportamiento de la App",
    "trouble_h3_11_1": "11.1 La Alerta se Activa Inmediatamente al Abrirla",
    "trouble_p_11_1": "Ve a **Ajustes** y deshabilita **\"Auto-Empezar al Iniciar\"**. Esta funci&oacute;n est&aacute; pensada para hardware externo.",
    "trouble_h2_12": "12. Problemas de iOS",
    "trouble_h3_12_1": "12.1 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> vs. Mensajes de iOS",
    "trouble_li_12_1_1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Autom&aacute;tico):</strong> Manda mensajes de fondo, necesita internet.",
    "trouble_li_12_1_2": "<strong>Mensajes (Manual):</strong> Exige t&uacute; env&iacute;o interponi&eacute;ndose, depende del celular.",
    "trouble_h2_13": "13. Problemas de {{ android_table_th2 }}",
    "trouble_h3_13_1": "13.1 Optimizaci&oacute;n de Bater&iacute;a",
    "trouble_p_13_1": "Algunos fabricantes (Xiaomi, Samsung) impiden el trabajo en segundo plano. Config&uacute;ralo sin restricciones.",
    "trouble_h2_14": "14. Consejos Generales",
    "trouble_h4_14_1": "✅ Antes de una Emergencia",
    "trouble_li_14_1": "Env&iacute;a una alerta de prueba.",
    "trouble_li_14_2": "Revisa el estado de conexi&oacute;n.",
    "trouble_li_14_3": "{{ sms_and_li6 }} habilitados permisos de locaci&oacute;n."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<p>This guide covers common issues and solutions for <span class=\"notranslate\" translate=\"no\">TapAlert</span> on both {{ android_table_th2 }} and iOS.</p>", "<p>{{ trouble_p1 }}</p>"),
    ("<h4>Jump to Section:</h4>", "<h4>{{ trouble_toc_h }}</h4>"),
    ("<li><a href=\"#sms\">1. SMS Issues</a></li>", "<li><a href=\"#sms\">{{ trouble_toc_1 }}</a></li>"),
    ("<li><a href=\"#email\">2. Email Issues</a></li>", "<li><a href=\"#email\">{{ trouble_toc_2 }}</a></li>"),
    ("<li><a href=\"#location\">3. {{ ts_li1_5 }} Issues</a></li>", "<li><a href=\"#location\">{{ trouble_toc_3 }}</a></li>"),
    ("<li><a href=\"#connectivity\">4. Connectivity</a></li>", "<li><a href=\"#connectivity\">{{ trouble_toc_4 }}</a></li>"),
    ("<li><a href=\"#timer\">5. Check-in Timer</a></li>", "<li><a href=\"#timer\">{{ trouble_toc_5 }}</a></li>"),
    ("<li><a href=\"#voice\">6. Voice-to-Text</a></li>", "<li><a href=\"#voice\">{{ trouble_toc_6 }}</a></li>"),
    ("<li><a href=\"#contacts\">7. {{ sms_so_li1_2 }}</a></li>", "<li><a href=\"#contacts\">{{ trouble_toc_7 }}</a></li>"),
    ("<li><a href=\"#purchase\">8. Purchases</a></li>", "<li><a href=\"#purchase\">{{ trouble_toc_8 }}</a></li>"),
    ("<li><a href=\"#widget\">9. Widgets</a></li>", "<li><a href=\"#widget\">{{ trouble_toc_9 }}</a></li>"),
    ("<li><a href=\"#notifications\">10. {{ sms_and_li2 }}</a></li>", "<li><a href=\"#notifications\">{{ trouble_toc_10 }}</a></li>"),
    ("<li><a href=\"#behavior\">11. App Behavior</a></li>", "<li><a href=\"#behavior\">{{ trouble_toc_11 }}</a></li>"),
    ("<li><a href=\"#ios\">12. iOS Specific</a></li>", "<li><a href=\"#ios\">{{ trouble_toc_12 }}</a></li>"),
    ("<li><a href=\"#android\">13. {{ android_table_th2 }} Specific</a></li>", "<li><a href=\"#android\">{{ trouble_toc_13 }}</a></li>"),
    ("<li><a href=\"#tips\">14. General Tips</a></li>", "<li><a href=\"#tips\">{{ trouble_toc_14 }}</a></li>"),

    ("<h2>1. SMS Sending Issues</h2>", "<h2>{{ trouble_h2_1 }}</h2>"),
    ("<h3>1.1 <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> Not Sending ({{ android_table_th2 }})</h3>", "<h3>{{ trouble_h3_1_1 }}</h3>"),
    ("<p><strong>Symptom:</strong> You tap \"Send Alert\" but the SMS fails. The alert history shows an error\n                    for one or more recipients.</p>", "<p>{{ trouble_p_1_1 }}</p>"),
    ("<li><strong>No cellular signal:</strong> Check the status bar. The Status page in the app shows your\n                        current cellular status.</li>", "<li>{{ trouble_li_1_1_1 }}</li>"),
    ("<li><strong>No SIM card:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> requires a working SIM card. Check SIM status on the\n                        Status page.</li>", "<li>{{ trouble_li_1_1_2 }}</li>"),
    ("<li><strong>Permissions:</strong> {{ sms_and_li6 }} <strong>SMS</strong> permission is allowed in phone\n                        settings.</li>", "<li>{{ trouble_li_1_1_3 }}</li>"),
    ("<li><strong>Invalid format:</strong> Use international format with country code (e.g.,\n                        +34600123456).</li>", "<li>{{ trouble_li_1_1_4 }}</li>"),

    ("<h3>1.2 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS Not Sending</h3>", "<h3>{{ trouble_h3_1_2 }}</h3>"),
    ("<p><strong>Symptom:</strong> Alert fails with a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> error message.</p>", "<p>{{ trouble_p_1_2 }}</p>"),
    ("<li><strong>Internet required:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> needs Wi-Fi or cellular data.</li>", "<li>{{ trouble_li_1_2_1 }}</li>"),
    ("<li><strong>Credentials:</strong> Verify Account SID, Auth Token, and <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> phone number in\n                        Settings.</li>", "<li>{{ trouble_li_1_2_2 }}</li>"),
    ("<li><strong>Trial limitations:</strong> Trial {{ qa_step3_p4 }}s can only send to {{ ts_tw_li7 }} phone numbers.</li>", "<li>{{ trouble_li_1_2_3 }}</li>"),
    ("<li><strong>Balance:</strong> Check your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} balance.</li>", "<li>{{ trouble_li_1_2_4 }}</li>"),

    ("<h3>1.3 iOS SMS Composer Issues</h3>", "<h3>{{ trouble_h3_1_3 }}</h3>"),
    ("<p><strong>Symptom:</strong> On iPhone, the SMS composer opens but the message doesn't get delivered.\n                </p>", "<p>{{ trouble_p_1_3 }}</p>"),
    ("<li><strong>Signal:</strong> The Messages app needs cellular signal (or WiFi Calling if active).\n                    </li>", "<li>{{ trouble_li_1_3_1 }}</li>"),
    ("<li><strong>Cancellation:</strong> If you tap Cancel in the composer, the alert is cancelled.</li>", "<li>{{ trouble_li_1_3_2 }}</li>"),
    ("<li><strong>Invalid number:</strong> iOS will queue the message and fail silently. Check the\n                        Messages app for red exclamation marks.</li>", "<li>{{ trouble_li_1_3_3 }}</li>"),

    ("<h2>2. Email Redundancy Issues</h2>", "<h2>{{ trouble_h2_2 }}</h2>"),
    ("<h3>2.1 Email Test Fails</h3>", "<h3>{{ trouble_h3_2_1 }}</h3>"),
    ("<li><strong>SMTP Settings:</strong> Verify host and port (Gmail/iCloud use 587).</li>", "<li>{{ trouble_li_2_1_1 }}</li>"),
    ("<li><strong>App Password:</strong> Most providers require an <strong>App Password</strong> if 2FA is\n                        enabled.</li>", "<li>{{ trouble_li_2_1_2 }}</li>"),
    ("<li><strong>Internet:</strong> Email requires an active data connection.</li>", "<li>{{ trouble_li_2_1_3 }}</li>"),

    ("<h2>3. {{ ts_li1_5 }} Issues</h2>", "<h2>{{ trouble_h2_3 }}</h2>"),
    ("<h3>3.1 {{ ts_li1_5 }} Missing in Alert</h3>", "<h3>{{ trouble_h3_3_1 }}</h3>"),
    ("<li><strong>Permissions:</strong> {{ sms_and_li6 }} {{ ts_li1_5 }} permission is set to \"While Using\" or \"Always\".\n                    </li>", "<li>{{ trouble_li_3_1_1 }}</li>"),
    ("<li><strong>GPS Disabled:</strong> Verify phone location services are turned on.</li>", "<li>{{ trouble_li_3_1_2 }}</li>"),
    ("<li><strong>Reception:</strong> Indoors or dense areas may cause a GPS timeout.</li>", "<li>{{ trouble_li_3_1_3 }}</li>"),

    ("<h2>4. Connectivity and Status</h2>", "<h2>{{ trouble_h2_4 }}</h2>"),
    ("<h3>4.2 Shield Icon Meanings</h3>", "<h3>{{ trouble_h3_4_2 }}</h3>"),
    ("<li><strong>Green:</strong> Ready for reliable SMS/<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> delivery.</li>", "<li>{{ trouble_li_4_2_1 }}</li>"),
    ("<li><strong>Orange:</strong> Uncertain. WiFi only, no <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. WiFi Calling might work.</li>", "<li>{{ trouble_li_4_2_2 }}</li>"),
    ("<li><strong>Red:</strong> Disconnected. Both cellular and WiFi are off.</li>", "<li>{{ trouble_li_4_2_3 }}</li>"),

    ("<h2>5. Check-in Timer Issues</h2>", "<h2>{{ trouble_h2_5 }}</h2>"),
    ("<h3>5.1 Timer Doesn't Fire</h3>", "<h3>{{ trouble_h3_5_1 }}</h3>"),
    ("<li><strong>App Closed:</strong> Avoid force-closing the app. On iOS, you {{ ts_em_li5 }} tap the notification\n                        to trigger.</li>", "<li>{{ trouble_li_5_1_1 }}</li>"),
    ("<li><strong>Battery Optimization:</strong> Set <span class=\"notranslate\" translate=\"no\">TapAlert</span> to \"Unrestricted\" in {{ android_table_th2 }} battery\n                        settings.</li>", "<li>{{ trouble_li_5_1_2 }}</li>"),
    ("<li><strong>{{ sms_and_li2 }}:</strong> {{ sms_and_li6 }} notification permissions are granted.</li>", "<li>{{ trouble_li_5_1_3 }}</li>"),

    ("<h2>6. Voice-to-Text Issues</h2>", "<h2>{{ trouble_h2_6 }}</h2>"),
    ("<h3>6.1 Voice Recognition Not Working</h3>", "<h3>{{ trouble_h3_6_1 }}</h3>"),
    ("<li><strong>Permissions:</strong> {{ sms_and_li6 }} <strong>Microphone</strong> and <strong>Speech\n                            Recognition</strong> (iOS) permissions are granted.</li>", "<li>{{ trouble_li_6_1_1 }}</li>"),
    ("<li><strong>Internet:</strong> Most recognition engines require an active connection for processing.\n                    </li>", "<li>{{ trouble_li_6_1_2 }}</li>"),
    ("<li><strong>Wrong {{ guide_lang }}:</strong> The recognition uses the app's current language setting. Check\n                        **Settings > {{ guide_lang }}**.</li>", "<li>{{ trouble_li_6_1_3 }}</li>"),

    ("<h2>7. {{ sms_so_li1_2 }} and Recipients Issues</h2>", "<h2>{{ trouble_h2_7 }}</h2>"),
    ("<h3>7.1 Cannot See {{ sms_so_li1_2 }}</h3>", "<h3>{{ trouble_h3_7_1 }}</h3>"),
    ("<li><strong>iOS Limited Access:</strong> If you previously chose \"{{ ts_loc_li2 }} {{ sms_so_li1_2 }}...\", go to\n                        **Settings > {{ table_r2c1 }} & Security > {{ sms_so_li1_2 }} > <span class=\"notranslate\" translate=\"no\">TapAlert</span>** and change to **\"All {{ sms_so_li1_2 }}\"**.</li>", "<li>{{ trouble_li_7_1_1 }}</li>"),
    ("<li><strong>{{ android_table_th2 }} Permissions:</strong> {{ sms_and_li6 }} **{{ sms_so_li1_2 }}** permission is set to \"Allow\" in system\n                        settings.</li>", "<li>{{ trouble_li_7_1_2 }}</li>"),
    ("<li><strong>Format:</strong> {{ sms_and_li6 }} numbers include the country code with a **+** prefix.</li>", "<li>{{ trouble_li_7_1_3 }}</li>"),

    ("<h2>8. In-App Purchase Issues</h2>", "<h2>{{ trouble_h2_8 }}</h2>"),
    ("<h3>8.2 Purchased But Still Shows {{ price_free_title }}</h3>", "<h3>{{ trouble_h3_8_2 }}</h3>"),
    ("<li><strong>Restore Purchases:</strong> In the Upgrade screen, tap the **Restore**{{ phil_sen_li2 }} to\n                        re-validate your purchase with the store.</li>", "<li>{{ trouble_li_8_2_1 }}</li>"),
    ("<li><strong>Same Account:</strong> {{ sms_and_li6 }} you're signed in with the same store {{ qa_step3_p4 }} used for the\n                        original purchase.</li>", "<li>{{ trouble_li_8_2_2 }}</li>"),

    ("<h2>9. Widget Issues ({{ android_table_th2 }})</h2>", "<h2>{{ trouble_h2_9 }}</h2>"),
    ("<h3>9.1 Widget Not Appearing</h3>", "<h3>{{ trouble_h3_9_1 }}</h3>"),
    ("<li><strong>Manual Add:</strong> Try adding the widget from **Settings > Widget > Add** within the\n                        app if it doesn't appear in the system widget picker.</li>", "<li>{{ trouble_li_9_1_1 }}</li>"),
    ("<li><strong>Battery Optimization:</strong> Aggressive optimization may prevent the widget from\n                        launching the app correctly.</li>", "<li>{{ trouble_li_9_1_2 }}</li>"),

    ("<h2>10. Notification Issues</h2>", "<h2>{{ trouble_h2_10 }}</h2>"),
    ("<h3>10.2 Recipients Not Noticing Calls/SMS</h3>", "<h3>{{ trouble_h3_10_2 }}</h3>"),
    ("<li><strong>iPhone:</strong> Have recipients enable **{{ sms_so_bypass }}** for your contact number.\n                    </li>", "<li>{{ trouble_li_10_2_1 }}</li>"),
    ("<li><strong>{{ android_table_th2 }}:</strong> Have recipients set notification priority to **{{ sms_and_li4 }}** or\n                        **{{ sms_and_li5 }}** for your messages.</li>", "<li>{{ trouble_li_10_2_2 }}</li>"),

    ("<h2>11. App Behavior Issues</h2>", "<h2>{{ trouble_h2_11 }}</h2>"),
    ("<h3>11.1 Alert Fires Immediately on Open</h3>", "<h3>{{ trouble_h3_11_1 }}</h3>"),
    ("<p>Go to **Settings** and disable **\"Auto-Start on Launch\"**. This feature is intended for physical\n                    panic{{ phil_sen_li2 }}s.</p>", "<p>{{ trouble_p_11_1 }}</p>"),

    ("<h2>12. iOS-Specific Issues</h2>", "<h2>{{ trouble_h2_12 }}</h2>"),
    ("<h3>12.1 <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> vs. {{ term_ios_messages }}</h3>", "<h3>{{ trouble_h3_12_1 }}</h3>"),
    ("<li><strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Automatic):</strong> Silent background sending, requires internet.</li>", "<li>{{ trouble_li_12_1_1 }}</li>"),
    ("<li><strong>{{ term_ios_messages }} (Manual):</strong> Requires you to tap Send in the composer, works via\n                        cellular.</li>", "<li>{{ trouble_li_12_1_2 }}</li>"),

    ("<h2>13. {{ android_table_th2 }}-Specific Issues</h2>", "<h2>{{ trouble_h2_13 }}</h2>"),
    ("<h3>13.1 Battery Optimization</h3>", "<h3>{{ trouble_h3_13_1 }}</h3>"),
    ("<p>Some manufacturers (Xiaomi, Samsung, Huawei) require manual steps to prevent the app from being\n                    killed in the background. Check your phone's battery settings for **\"No restrictions\"**.</p>", "<p>{{ trouble_p_13_1 }}</p>"),

    ("<h2>14. General Tips</h2>", "<h2>{{ trouble_h2_14 }}</h2>"),
    ("<h4>✅ Before an Emergency</h4>", "<h4>{{ trouble_h4_14_1 }}</h4>"),
    ("<li>Send a test alert to verify setup.</li>", "<li>{{ trouble_li_14_1 }}</li>"),
    ("<li>Check the Status page for connectivity.</li>", "<li>{{ trouble_li_14_2 }}</li>"),
    ("<li>{{ sms_and_li6 }} all permissions are granted.</li>", "<li>{{ trouble_li_14_3 }}</li>")
]

replace_in_file('src/troubleshooting.html', replacements)
print("Updated troubleshooting.html")
