import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        en[k] = v
    for k, v in new_es.items():
        es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "ota_title": "One-Tap Alert Guide",
    "ota_h1": "One-Tap Alert: All the Ways to Trigger <span class=\"notranslate\" translate=\"no\">TapAlert</span> Instantly",
    "ota_intro": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> can be configured for instant, one-tap emergency alerts using several different methods. This guide covers every option, from home screen widgets to physical{{ phil_sen_li2 }}s and automated timers.",
    "ota_widget_p1": "The fastest way to trigger an alert. A dedicated widget sits on your home screen \u2014 one tap and the countdown starts immediately.",
    "ota_h3_setup": "How to Set Up",
    "ota_setup_li1": "Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 tap the <strong>\u2699\ufe0f Settings</strong> icon.",
    "ota_setup_li2": "Scroll to the <strong>Widget</strong> section.",
    "ota_setup_li3": "Tap <strong>\"Add\"</strong> \u2192 the system will prompt you to place the widget on your home screen.",
    "ota_setup_li4": "Drag it to your preferred spot (ideally on your main screen for quick access).",
    "ota_h3_how_works": "How It Works",
    "ota_works_li1": "<strong>Single tap</strong> on the widget \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span> opens and the <strong>countdown begins immediately</strong>.",
    "ota_works_li2": "You see the countdown dialog and can <strong>cancel</strong> if it w{{ qa_step3_p5 }}ccidental.",
    "ota_works_li3": "After the countdown, the alert is sent and the app auto-closes.",
    "ota_tip_h4": "\ud83d\udca1 TIP",
    "ota_tip_p1": "Place the widget on your lock screen (if supported by your {{ android_table_th2 }} version) or on the very first home screen page for the quickest access.",
    "ota_h2_2": "2. \ud83d\udd18 Physical Button / Hardware Gesture",
    "ota_p_phys_1": "Map a <strong>physical{{ phil_sen_li2 }}</strong> on your phone (power{{ phil_sen_li2 }}, volume key, or back-tap gesture) to launch <span class=\"notranslate\" translate=\"no\">TapAlert</span>. Combined with <strong>Auto-Start on Launch</strong>, this creates a true one-tap panic {{ phil_sen_li2 }}.",
    "ota_h3_phys_s1": "Step 1: Enable Auto-Start in <span class=\"notranslate\" translate=\"no\">TapAlert</span>",
    "ota_phys_s1_li1": "Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 <strong>\u2699\ufe0f Settings</strong>.",
    "ota_phys_s1_li2": "Enable <strong>\"Auto-Start on Launch\"</strong>.",
    "ota_warning_h4": "\u26a0\ufe0f WARNING",
    "ota_warning_p": "When Auto-Start is enabled, the countdown will trigger <strong>every time</strong> you open the app \u2014 including when you open it normally from the app drawer. Only enable this if you primarily launch via a physical{{ phil_sen_li2 }} shortcut.",
    "ota_h3_phys_s2": "Step 2: Configure Your Phone's Button",
    "ota_h4_samsung": "Samsung Galaxy (Side Key)",
    "ota_samsung_li1": "<strong>Settings</strong> \u2192 <strong>Advanced {{ price_features }}</strong> \u2192 <strong>Side key</strong>.",
    "ota_samsung_li2": "Enable <strong>Double press</strong> \u2192 <strong>Open app</strong> \u2192 select <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_samsung_li3": "Double-press the power{{ phil_sen_li2 }} to trigger.",
    "ota_h4_pixel": "Google Pixel (Quick Tap)",
    "ota_pixel_li1": "<strong>Settings</strong> \u2192 <strong>System</strong> \u2192 <strong>Gestures</strong> \u2192 <strong>Quick Tap to start actions</strong>.",
    "ota_pixel_li2": "Enable <strong>Use Quick Tap</strong> \u2192 <strong>Open app</strong> \u2192 select <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_pixel_li3": "Double-tap the back of your phone to trigger.",
    "ota_h4_iphone_ab": "iPhone 15 Pro+ (Action Button)",
    "ota_iphone_ab_li1": "<strong>Settings</strong> \u2192 <strong>Action Button</strong> \u2192 swipe to <strong>Shortcut</strong>.",
    "ota_iphone_ab_li2": "Tap selector \u2192 <strong>Open App</strong> \u2192 choose <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_iphone_ab_li3": "Hold the Action Button to trigger.",
    "ota_h4_iphone_bt": "iPhone \u2014 All Models (Back Tap)",
    "ota_iphone_bt_li1": "<strong>Settings</strong> \u2192 <strong>Accessibility</strong> \u2192 <strong>Touch</strong> \u2192 <strong>Back Tap</strong>.",
    "ota_iphone_bt_li2": "Choose <strong>Double Tap</strong> or <strong>Triple Tap</strong>.",
    "ota_iphone_bt_li3": "To link to <span class=\"notranslate\" translate=\"no\">TapAlert</span>, first create a Shortcut:",
    "ota_iphone_bt_li3a": "Open <strong>Shortcuts</strong> app \u2192 <strong>+</strong> \u2192 <strong>Add Action</strong> \u2192 <strong>Open App</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_iphone_bt_li3b": "Name it \"Open <span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ota_iphone_bt_li4": "Go back to <strong>Back Tap</strong> settings \u2192 select your \"Open <span class=\"notranslate\" translate=\"no\">TapAlert</span>\" shortcut.",
    "ota_h4_android_apps": "Any {{ android_table_th2 }} (Button Mapper Apps)",
    "ota_android_apps_p": "If your device lacks {{ phil_priv_li2 }}{{ phil_sen_li2 }} remapping, install <strong>\"Button Mapper\"</strong> or <strong>\"MacroDroid\"</strong> from the Play Store:",
    "ota_android_apps_li1": "Remap any hardware key (volume{{ phil_sen_li2 }}s, etc.) to <strong>Open Application</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_phys_work_li1": "Press your configured{{ phil_sen_li2 }}/gesture.",
    "ota_phys_work_li2": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> opens \u2192 the countdown starts <strong>automatically</strong> (if Auto-Start is enabled).",
    "ota_phys_work_li3": "The alert is sent and the app auto-closes.",
    "ota_phys_work_li4": "Works even from a locked screen (with proper battery optimization \u2014 see below).",
    "ota_h2_3": "3. \ud83c\udd98 <span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\" translate=\"no\">SOS</span> / OK)",
    "ota_panic_p": "<span class=\"notranslate\" translate=\"no\">Panic Mode</span> transforms the entire screen into two giant {{ phil_sen_li2 }}s \u2014 <strong><span class=\"notranslate\" translate=\"no\">SOS</span></strong> and <strong>I'm OK</strong> \u2014 making it virtually impossible to miss.",
    "ota_h3_enable": "How to Enable",
    "ota_enable_li1": "Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> and it will open by default in <span class=\"notranslate\" translate=\"no\">Panic Mode</span>.",
    "ota_enable_li2": "Remember: you can switch from Configured message Alerts to <span class=\"notranslate\" translate=\"no\">Panic mode</span> swiping left/right on the home screen or tap the mode icon in the top bar.",
    "ota_panic_work_li1": "<strong>Tap the large red <span class=\"notranslate\" translate=\"no\">SOS</span>{{ phil_sen_li2 }}</strong> \u2192 countdown starts for an emergency alert.",
    "ota_panic_work_li2": "<strong>Tap the green I'm OK{{ phil_sen_li2 }}</strong> \u2192 sends a reassurance message.",
    "ota_panic_work_li3": "<strong>Emergency Call{{ phil_sen_li2 }}</strong> at the bottom dials your local emergency number (112, 911, etc.).",
    "ota_h3_trigger": "Trigger Method: Tap vs. Hold",
    "ota_trigger_p": "For added safety, you can require a <strong>5-second press-and-hold</strong> instead of a single tap:",
    "ota_trigger_li1": "<strong>Settings</strong> \u2192 <strong>Trigger Method</strong> \u2192 <strong>Press & Hold (5s)</strong>.",
    "ota_trigger_li2": "This prevents accidental triggers while still being fast enough in emergencies.",
    "ota_h2_4": "4. \ud83c\udf99\ufe0f Voice Quick Alert",
    "ota_voice_p": "In <span class=\"notranslate\" translate=\"no\">Panic mode</span> you can also send an alert with a <strong>voice-dictated message</strong> in one action \u2014 ideal when you can't type.",
    "ota_voice_li1": "Tap the <strong>\ud83c\udf99\ufe0f Microphone</strong>{{ phil_sen_li2 }} next to <span class=\"notranslate\" translate=\"no\">SOS</span> or I'm OK.",
    "ota_voice_li2": "Speak your message.",
    "ota_voice_li3": "After speaking the countdown starts automatically with your transcribed voice message attached.",
    "ota_h2_5": "5. \u23f3 Check-in Timer (Dead Man's Switch)",
    "ota_timer_p": "The timer sends an alert <strong>automatically</strong> if you don't check in \u2014 no tap required at all.",
    "ota_timer_li1": "Tap the <strong>\u23f1\ufe0f Timer icon</strong> in the top bar.",
    "ota_timer_li3": "Optionally add a custom message.",
    "ota_timer_li4": "Start the timer.",
    "ota_timer_work_li1": "A persistent notification counts down the remaining time.",
    "ota_timer_work_li2": "If you check in (tap <strong>\"I'm OK / Reset\"</strong>) \u2192 timer resets, no alert sent.",
    "ota_timer_work_li3": "If you don't check in \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span> automatically sends your alert with location to all recipients.",
    "ota_tip_p2": "Perfect for solo activities: hiking, walking home at night, meeting strangers, or traveling alone.",
    "ota_h2_6": "6. \ud83d\udd0b Critical: Battery Optimization ({{ android_table_th2 }})",
    "ota_battery_p1": "For <strong>physical{{ phil_sen_li2 }}</strong> and <strong>widget</strong> triggers to work reliably \u2014 especially from a locked/sleeping screen \u2014 you {{ ts_em_li5 }} disable battery optimization for <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ota_h3_why": "Why?",
    "ota_why_p": "{{ android_table_th2 }} manufacturers aggressively kill background apps to save battery. This can prevent <span class=\"notranslate\" translate=\"no\">TapAlert</span> from waking your phone when the screen is off.",
    "ota_h3_quick": "Quick Steps (All Devices)",
    "ota_quick_li1": "<strong>Settings</strong> \u2192 <strong>Apps</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 <strong>Battery</strong>.",
    "ota_quick_li2": "{{ ts_loc_li2 }} <strong>\"Don't optimize\"</strong> or <strong>\"Unrestricted\"</strong>.",
    "ota_quick_li3": "Enable <strong>\"Allow background activity\"</strong>.",
    "ota_h3_test": "Test It",
    "ota_test_li1": "Lock your phone and wait 1\u20132 minutes (screen fully off).",
    "ota_test_li2": "Press your configured physical{{ phil_sen_li2 }} or tap the widget.",
    "ota_test_li3": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> should open and start the countdown instantly.",
    "ota_h2_comp": "Quick Comparison",
    "ota_th_method": "Method",
    "ota_th_taps": "Taps to Alert",
    "ota_th_lock": "Works From Lock Screen",
    "ota_th_setup": "Requires Setup",
    "ota_td_widget": "{{ android_table_th2 }} Widget",
    "ota_td_partial": "Partial*",
    "ota_td_minimal": "Minimal",
    "ota_td_phys": "Physical Button + Auto-Start",
    "ota_td_yes": "\u2705 Yes",
    "ota_td_mod": "Moderate",
    "ota_td_panic": "<span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\" translate=\"no\">SOS</span>{{ phil_sen_li2 }})",
    "ota_td_2taps": "2 (open app + tap)",
    "ota_td_dash": "\u2014",
    "ota_td_voice": "Voice Quick Alert",
    "ota_td_2taps_mic": "2 (open app + tap mic)",
    "ota_td_none": "None",
    "ota_td_timer": "Check-in Timer",
    "ota_td_0taps": "0 (automatic)",
    "ota_comp_footnote": "<small>*Widget lock screen support varies by {{ android_table_th2 }} version and manufacturer.</small>",
    "ota_h2_recom": "Recommended Configurations",
    "ota_h3_recom_senior": "\ud83d\udc74 For Senior Users",
    "ota_recom_senior_li1": "Use <strong><span class=\"notranslate\" translate=\"no\">Panic Mode</span></strong> (big <span class=\"notranslate\" translate=\"no\">SOS</span> / I'm OK{{ phil_sen_li2 }}s).",
    "ota_recom_senior_li2": "Set <strong>Trigger Method</strong> to <strong>Tap</strong> (simplest interaction).",
    "ota_recom_senior_li3": "Add the <strong>{{ android_table_th2 }} widget</strong> to the home screen.",
    "ota_recom_senior_li4": "Set countdown to <strong>10 - 15 seconds</strong> (time to cancel mistakes).",
    "ota_h3_recom_active": "\ud83c\udfc3 For Active / Solo Users",
    "ota_recom_active_li1": "Set up the <strong>Check-in Timer</strong> before activities.",
    "ota_recom_active_li2": "Configure a <strong>physical{{ phil_sen_li2 }}</strong> for instant <span class=\"notranslate\" translate=\"no\">SOS</span>.",
    "ota_recom_active_li3": "Enable <strong><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span></strong> (auto-<span class=\"notranslate\" translate=\"no\">fallback</span> between SMS methods).",
    "ota_recom_active_li4": "Enable <strong>Email Redundancy</strong> for areas with Wi-Fi only.",
    "ota_h3_recom_secure": "\ud83d\udd12 For Maximum Security",
    "ota_recom_secure_li1": "Configure <strong>physical{{ phil_sen_li2 }}</strong> with <strong>Auto-Start</strong>.",
    "ota_recom_secure_li2": "Set <strong>Trigger Method</strong> to <strong>Press & Hold (5s)</strong> to prevent accidental triggers.",
    "ota_recom_secure_li3": "Enable <strong>both</strong> <span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> and Email Redundancy.",
    "ota_recom_secure_li4": "Disable battery optimization and test from locked screen."
}

es_keys = {
    "ota_title": "Guía de Alerta con un Toque",
    "ota_h1": "Alerta de un Solo Toque: Todas las Formas de Activar <span class=\"notranslate\" translate=\"no\">TapAlert</span> al Instante",
    "ota_intro": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> se puede configurar para enviar alertas de emergencia con un solo toque utilizando varios métodos diferentes. Esta guía cubre todas las opciones, desde widgets en la pantalla de inicio hasta {{ phil_sen_li2 }}s físicos y temporizadores automáticos.",
    "ota_widget_p1": "La forma más rápida de activar una alerta. Un widget dedicado en tu pantalla de inicio \u2014 con un solo toque, la cuenta regresiva comienza inmediatamente.",
    "ota_h3_setup": "Cómo Configurar",
    "ota_setup_li1": "Abre <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 toca el icono de <strong>\u2699\ufe0f Ajustes</strong>.",
    "ota_setup_li2": "Desplázate hasta la sección <strong>Widget</strong>.",
    "ota_setup_li3": "Toca <strong>\"Agregar\"</strong> \u2192 el sistema te pedirá que coloques el widget en tu pantalla de inicio.",
    "ota_setup_li4": "Arrástralo al lugar de tu preferencia (idealmente en tu pantalla principal para acceso rápido).",
    "ota_h3_how_works": "Cómo Funciona",
    "ota_works_li1": "Un <strong>solo toque</strong> en el widget \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span> se abre y <strong>la cuenta regresiva comienza inmediatamente</strong>.",
    "ota_works_li2": "Verás el cuadro de diálogo de la cuenta regresiva y puedes <strong>cancelarla</strong> si fue{{ qa_step3_p5 }}ccidental.",
    "ota_works_li3": "Después de la cuenta regresiva, se envía la alerta y la aplicación se cierra sola.",
    "ota_tip_h4": "\ud83d\udca1 CONSEJO",
    "ota_tip_p1": "Coloca el widget en tu pantalla de bloqueo (si tu versión de {{ android_table_th2 }} lo permite) o en la primera página de tu pantalla de inicio para un acceso lo más rápido posible.",
    "ota_h2_2": "2. \ud83d\udd18 Botón Físico / Gesto",
    "ota_p_phys_1": "Asigna un <strong>{{ phil_sen_li2 }} físico</strong> en tu teléfono (botón de encendido, tecla de volumen o un gesto de toque en la parte trasera) para iniciar <span class=\"notranslate\" translate=\"no\">TapAlert</span>. Combinado con <strong>Inicio Automático</strong>, esto crea un verdadero {{ phil_sen_li2 }} de pánico de un solo toque.",
    "ota_h3_phys_s1": "Paso 1: Habilitar el Inicio Automático en <span class=\"notranslate\" translate=\"no\">TapAlert</span>",
    "ota_phys_s1_li1": "Abre <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 <strong>\u2699\ufe0f Ajustes</strong>.",
    "ota_phys_s1_li2": "Activa <strong>\"Inicio Automático\"</strong>.",
    "ota_warning_h4": "\u26a0\ufe0f ADVERTENCIA",
    "ota_warning_p": "Cuando el Inicio Automático está habilitado, la cuenta regresiva se activará <strong>siempre</strong> que abras la aplicación \u2014 incluso cuando la abras normalmente desde el cajón de aplicaciones. Solo habilita esto si principalmente abres la app mediante un acceso directo por {{ phil_sen_li2 }} físico.",
    "ota_h3_phys_s2": "Paso 2: Configurar el Botón de tu Teléfono",
    "ota_h4_samsung": "Samsung Galaxy (Tecla Lateral)",
    "ota_samsung_li1": "<strong>Ajustes</strong> \u2192 <strong>{{ price_features }} Avanzadas</strong> \u2192 <strong>Tecla lateral</strong>.",
    "ota_samsung_li2": "Habilita <strong>Doble pulsación</strong> \u2192 <strong>Abrir aplicación</strong> \u2192 selecciona <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_samsung_li3": "Pulsa dos veces el {{ phil_sen_li2 }} de encendido para activar.",
    "ota_h4_pixel": "Google Pixel (Toque Rápido)",
    "ota_pixel_li1": "<strong>Ajustes</strong> \u2192 <strong>Sistema</strong> \u2192 <strong>Gestos</strong> \u2192 <strong>Toque rápido para iniciar acciones</strong>.",
    "ota_pixel_li2": "Habilita <strong>Usar Toque Rápido</strong> \u2192 <strong>Abrir aplicación</strong> \u2192 selecciona <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_pixel_li3": "Toca dos veces la parte trasera de tu teléfono para activar.",
    "ota_h4_iphone_ab": "iPhone 15 Pro+ (Botón de Acción)",
    "ota_iphone_ab_li1": "<strong>Ajustes</strong> \u2192 <strong>Botón de Acción</strong> \u2192 desliza hasta <strong>Atajo</strong>.",
    "ota_iphone_ab_li2": "Toca el selector \u2192 <strong>Abrir App</strong> \u2192 elige <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_iphone_ab_li3": "Mantén presionado el Botón de Acción para activar.",
    "ota_h4_iphone_bt": "iPhone \u2014 Todos los Modelos (Toque Posterior)",
    "ota_iphone_bt_li1": "<strong>Ajustes</strong> \u2192 <strong>Accesibilidad</strong> \u2192 <strong>Tocar</strong> \u2192 <strong>Toque Posterior</strong>.",
    "ota_iphone_bt_li2": "Elige <strong>Doble Toque</strong> o <strong>Triple Toque</strong>.",
    "ota_iphone_bt_li3": "Para vincular con <span class=\"notranslate\" translate=\"no\">TapAlert</span>, primero crea un Atajo:",
    "ota_iphone_bt_li3a": "Abre la aplicación <strong>Atajos</strong> \u2192 <strong>+</strong> \u2192 <strong>Agregar Acción</strong> \u2192 <strong>Abrir App</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_iphone_bt_li3b": "Nómbralo \"Abrir <span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ota_iphone_bt_li4": "Vuelve a la configuración de <strong>Toque Posterior</strong> \u2192 selecciona tu atajo \"Abrir <span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ota_h4_android_apps": "Cualquier {{ android_table_th2 }} (Aplicaciones para Mapear Botones)",
    "ota_android_apps_p": "Si tu dispositivo carece de reasignación de botones nativa, instala <strong>\"Button Mapper\"</strong> o <strong>\"MacroDroid\"</strong> desde la Play Store:",
    "ota_android_apps_li1": "Reasigna cualquier tecla de hardware ({{ phil_sen_li2 }}es de volumen, etc.) a <strong>Abrir Aplicación</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.",
    "ota_phys_work_li1": "Presiona el {{ phil_sen_li2 }} o gesto configurado.",
    "ota_phys_work_li2": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> se abrirá \u2192 la cuenta regresiva comenzará <strong>automáticamente</strong> (si el Inicio Automático está activado).",
    "ota_phys_work_li3": "La alerta se enviará y la app se cerrará sola.",
    "ota_phys_work_li4": "Funciona incluso con la pantalla bloqueada (con la optimización de batería adecuada \u2014 ver abajo).",
    "ota_h2_3": "3. \ud83c\udd98 <span class=\"notranslate\" translate=\"no\">Modo Pánico</span> (<span class=\"notranslate\" translate=\"no\">SOS</span> / OK)",
    "ota_panic_p": "El <span class=\"notranslate\" translate=\"no\">Modo Pánico</span> transforma toda la pantalla en dos {{ phil_sen_li2 }}es gigantes \u2014 <strong><span class=\"notranslate\" translate=\"no\">SOS</span></strong> y <strong>Estoy Bien</strong> \u2014 lo que lo hace casi imposible de pasar por alto.",
    "ota_h3_enable": "Cómo Activar",
    "ota_enable_li1": "Abre <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> y se abrirá por defecto en el <span class=\"notranslate\" translate=\"no\">Modo Pánico</span>.",
    "ota_enable_li2": "Recuerda: puedes cambiar de las Alertas con mensajes configurados al <span class=\"notranslate\" translate=\"no\">Modo Pánico</span> deslizando a la izquierda o derecha en la pantalla de inicio, o tocando el icono de modo en la barra superior.",
    "ota_panic_work_li1": "<strong>Tocar el gran {{ phil_sen_li2 }} rojo <span class=\"notranslate\" translate=\"no\">SOS</span></strong> \u2192 inicia la cuenta regresiva para una alerta de emergencia.",
    "ota_panic_work_li2": "<strong>Tocar el {{ phil_sen_li2 }} verde Estoy Bien</strong> \u2192 envía un mensaje para tranquilizar a tus contactos.",
    "ota_panic_work_li3": "El <strong>{{ phil_sen_li2 }} de Llamada a Emergencias</strong> en la parte inferior marca tu número local de emergencias (112, 911, etc.).",
    "ota_h3_trigger": "Método de Activación: Tocar o Mantener",
    "ota_trigger_p": "Para mayor seguridad, puedes requerir <strong>mantener presionado durante 5 segundos</strong> en lugar de un solo toque:",
    "ota_trigger_li1": "<strong>Ajustes</strong> \u2192 <strong>Método de Activación</strong> \u2192 <strong>Mantener Presionado (5s)</strong>.",
    "ota_trigger_li2": "Esto previene activaciones accidentales a la vez que sigue siendo rápido en emergencias.",
    "ota_h2_4": "4. \ud83c\udf99\ufe0f Alerta Rápida de Voz",
    "ota_voice_p": "En el <span class=\"notranslate\" translate=\"no\">Modo Pánico</span>, también puedes enviar una alerta dictando un mensaje con la <strong>voz</strong> en una sola acción \u2014 ideal cuando no puedes escribir.",
    "ota_voice_li1": "Toca el {{ phil_sen_li2 }} del <strong>\ud83c\udf99\ufe0f Micrófono</strong> al lado de <span class=\"notranslate\" translate=\"no\">SOS</span> o Estoy Bien.",
    "ota_voice_li2": "Dicta tu mensaje.",
    "ota_voice_li3": "Después de hablar, la cuenta regresiva comenzará automáticamente adjuntando tu mensaje de voz transcrito.",
    "ota_h2_5": "5. \u23f3 Temporizador (Dead Man's Switch)",
    "ota_timer_p": "El temporizador envía una alerta <strong>automáticamente</strong> si no confirmas que estás bien \u2014 no requiere tocar la pantalla.",
    "ota_timer_li1": "Toca el <strong>\u23f1\ufe0f Icono del Temporizador</strong> en la barra superior.",
    "ota_timer_li3": "Opcionalmente, añade un mensaje personalizado.",
    "ota_timer_li4": "Inicia el temporizador.",
    "ota_timer_work_li1": "Una notificación constante marcará la cuenta regresiva.",
    "ota_timer_work_li2": "Si confirmas tu estado (tocas <strong>\"Estoy Bien / Reiniciar\"</strong>) \u2192 el temporizador se reinicia y no se envía ninguna alerta.",
    "ota_timer_work_li3": "Si no confirmas tu estado \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span> automáticamente enviará tu alerta y tu ubicación a todos los destinatarios.",
    "ota_tip_p2": "Perfecto para actividades en solitario: hacer senderismo, caminar a casa de noche, reunirte con desconocidos o viajar en solitario.",
    "ota_h2_6": "6. \ud83d\udd0b Crítico: Optimización de Batería ({{ android_table_th2 }})",
    "ota_battery_p1": "Para que la activación mediante <strong>{{ phil_sen_li2 }}es físicos</strong> o <strong>widgets</strong> funcione fiablemente \u2014 especialmente con la pantalla apagada o bloqueada \u2014 tú {{ ts_em_li5 }} deshabilitar la optimización de batería para <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ota_h3_why": "¿Por qué?",
    "ota_why_p": "Los fabricantes de {{ android_table_th2 }} cierran de manera agresiva las aplicaciones en segundo plano para ahorrar batería. Esto puede prevenir que <span class=\"notranslate\" translate=\"no\">TapAlert</span> despierte tu teléfono cuando la pantalla está apagada.",
    "ota_h3_quick": "Pasos Rápidos (Todos los dispositivos)",
    "ota_quick_li1": "<strong>Ajustes</strong> \u2192 <strong>Aplicaciones</strong> \u2192 <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 <strong>Batería</strong>.",
    "ota_quick_li2": "{{ ts_loc_li2 }} <strong>\"No optimizar\"</strong> o <strong>\"Sin restricciones\"</strong>.",
    "ota_quick_li3": "Habilita <strong>\"Permitir actividad en segundo plano\"</strong>.",
    "ota_h3_test": "Compruébalo",
    "ota_test_li1": "Bloquea tu teléfono y espera 1–2 minutos (pantalla totalmente apagada).",
    "ota_test_li2": "Pulsa el {{ phil_sen_li2 }} físico configurado o toca el widget.",
    "ota_test_li3": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> debería abrirse e iniciar la cuenta regresiva al instante.",
    "ota_h2_comp": "Comparación Rápida",
    "ota_th_method": "Método",
    "ota_th_taps": "Toques para Alertar",
    "ota_th_lock": "Funciona Desde la Pantalla de Bloqueo",
    "ota_th_setup": "Requiere Configuración",
    "ota_td_widget": "Widget de {{ android_table_th2 }}",
    "ota_td_partial": "Parcial*",
    "ota_td_minimal": "Mínima",
    "ota_td_phys": "Botón Físico + Inicio Automático",
    "ota_td_yes": "\u2705 Sí",
    "ota_td_mod": "Moderada",
    "ota_td_panic": "<span class=\"notranslate\" translate=\"no\">Modo Pánico</span> (Botón <span class=\"notranslate\" translate=\"no\">SOS</span>)",
    "ota_td_2taps": "2 (abrir app + tocar)",
    "ota_td_dash": "\u2014",
    "ota_td_voice": "Alerta Rápida de Voz",
    "ota_td_2taps_mic": "2 (abrir app + tocar micrófono)",
    "ota_td_none": "Ninguna",
    "ota_td_timer": "Temporizador",
    "ota_td_0taps": "0 (automático)",
    "ota_comp_footnote": "<small>*El soporte de los widgets en la pantalla de bloqueo varía según la versión y fabricante de {{ android_table_th2 }}.</small>",
    "ota_h2_recom": "Configuraciones Recomendadas",
    "ota_h3_recom_senior": "\ud83d\udc74 Para Usuarios Mayores",
    "ota_recom_senior_li1": "Usa el <strong><span class=\"notranslate\" translate=\"no\">Modo Pánico</span></strong> (Botones grandes de <span class=\"notranslate\" translate=\"no\">SOS</span> / Estoy Bien).",
    "ota_recom_senior_li2": "Configura el <strong>Método de Activación</strong> a <strong>Tocar</strong> (la interacción más simple).",
    "ota_recom_senior_li3": "Agrega el <strong>widget de {{ android_table_th2 }}</strong> a tu pantalla de inicio.",
    "ota_recom_senior_li4": "Establece la cuenta regresiva en <strong>10 - 15 segundos</strong> (tiempo para cancelar errores).",
    "ota_h3_recom_active": "\ud83c\udfc3 Para Usuarios Activos / En Solitario",
    "ota_recom_active_li1": "Configura el <strong>Temporizador</strong> antes de realizar actividades.",
    "ota_recom_active_li2": "Configura un <strong>{{ phil_sen_li2 }} físico</strong> para un <span class=\"notranslate\" translate=\"no\">SOS</span> al instante.",
    "ota_recom_active_li3": "Activa <strong><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span></strong> (para alternar automáticamente entre métodos de envío por SMS).",
    "ota_recom_active_li4": "Activa la <strong>Redundancia de Correo</strong> para áreas que solo dispongan de Wi-Fi.",
    "ota_h3_recom_secure": "\ud83d\udd12 Para Máxima Seguridad",
    "ota_recom_secure_li1": "Configura un <strong>{{ phil_sen_li2 }} físico</strong> con <strong>Inicio Automático</strong>.",
    "ota_recom_secure_li2": "Establece el <strong>Método de Activación</strong> en <strong>Mantener Presionado (5s)</strong> para prevenir alertas accidentales.",
    "ota_recom_secure_li3": "Habilita <strong>tanto</strong> <span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> como la Redundancia de Correo.",
    "ota_recom_secure_li4": "Deshabilita la optimización de batería y pruébalo con la pantalla bloqueada."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<title>One-Tap Alert Guide - TapAlert</title>", "<title>{{ ota_title }} - TapAlert</title>"),
    ("<h1 class=\"guide-title\">One-Tap Alert: All the Ways to Trigger <span class=\"notranslate\"\n                translate=\"no\">TapAlert</span> Instantly</h1>", "<h1 class=\"guide-title\">{{ ota_h1 }}</h1>"),
    ("<p><span class=\"notranslate\" translate=\"no\">TapAlert</span> can be configured for instant, one-tap emergency\n            alerts using several different methods. This guide\n            covers every option, from home screen widgets to physical{{ phil_sen_li2 }}s and automated timers.</p>", "<p>{{ ota_intro }}</p>"),
    ("<h2>1. \ud83d\udcf1 {{ android_table_th2 }} {{ feat_widget_title }}</h2>", "<h2>1. \ud83d\udcf1 {{ android_table_th2 }} {{ feat_widget_title }}</h2>"),
    ("<p>The fastest way to trigger an alert. A dedicated widget sits on your home screen \u2014 one tap and the\n                countdown starts immediately.</p>", "<p>{{ ota_widget_p1 }}</p>"),
    ("<h3>How to Set Up</h3>", "<h3>{{ ota_h3_setup }}</h3>"),
    ("<li>Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 tap the <strong>\u2699\ufe0f\n                        Settings</strong> icon.</li>", "<li>{{ ota_setup_li1 }}</li>"),
    ("<li>Scroll to the <strong>Widget</strong> section.</li>", "<li>{{ ota_setup_li2 }}</li>"),
    ("<li>Tap <strong>\"Add\"</strong> \u2192 the system will prompt you to place the widget on your home screen.\n                </li>", "<li>{{ ota_setup_li3 }}</li>"),
    ("<li>Drag it to your preferred spot (ideally on your main screen for quick access).</li>", "<li>{{ ota_setup_li4 }}</li>"),
    ("<h3>How It Works</h3>", "<h3>{{ ota_h3_how_works }}</h3>"),
    ("<li><strong>Single tap</strong> on the widget \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span>\n                    opens and the <strong>countdown begins\n                        immediately</strong>.</li>", "<li>{{ ota_works_li1 }}</li>"),
    ("<li>You see the countdown dialog and can <strong>cancel</strong> if it w{{ qa_step3_p5 }}ccidental.</li>", "<li>{{ ota_works_li2 }}</li>"),
    ("<li>After the countdown, the alert is sent and the app auto-closes.</li>", "<li>{{ ota_works_li3 }}</li>"),
    ("<h4>\ud83d\udca1 TIP</h4>", "<h4>{{ ota_tip_h4 }}</h4>"),
    ("<p>Place the widget on your lock screen (if supported by your {{ android_table_th2 }} version) or on the very first home\n                    screen page for the quickest access.</p>", "<p>{{ ota_tip_p1 }}</p>"),
    ("<h2>2. \ud83d\udd18 Physical Button / Hardware Gesture</h2>", "<h2>{{ ota_h2_2 }}</h2>"),
    ("<p>Map a <strong>physical{{ phil_sen_li2 }}</strong> on your phone (power{{ phil_sen_li2 }}, volume key, or back-tap gesture) to\n                launch <span class=\"notranslate\" translate=\"no\">TapAlert</span>. Combined with <strong>Auto-Start on\n                    Launch</strong>, this creates a true one-tap panic\n               {{ phil_sen_li2 }}.</p>", "<p>{{ ota_p_phys_1 }}</p>"),
    ("<h3>Step 1: Enable Auto-Start in <span class=\"notranslate\" translate=\"no\">TapAlert</span></h3>", "<h3>{{ ota_h3_phys_s1 }}</h3>"),
    ("<li>Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> \u2192 <strong>\u2699\ufe0f\n                        Settings</strong>.</li>", "<li>{{ ota_phys_s1_li1 }}</li>"),
    ("<li>Enable <strong>\"Auto-Start on Launch\"</strong>.</li>", "<li>{{ ota_phys_s1_li2 }}</li>"),
    ("<h4>\u26a0\ufe0f WARNING</h4>", "<h4>{{ ota_warning_h4 }}</h4>"),
    ("<p>When Auto-Start is enabled, the countdown will trigger <strong>every time</strong> you open the app \u2014\n                    including when you open it normally from the app drawer. Only enable this if you primarily launch\n                    via a physical{{ phil_sen_li2 }} shortcut.</p>", "<p>{{ ota_warning_p }}</p>"),
    ("<h3>Step 2: Configure Your Phone's Button</h3>", "<h3>{{ ota_h3_phys_s2 }}</h3>"),
    ("<h4>Samsung Galaxy (Side Key)</h4>", "<h4>{{ ota_h4_samsung }}</h4>"),
    ("<li><strong>Settings</strong> \u2192 <strong>Advanced {{ price_features }}</strong> \u2192 <strong>Side key</strong>.</li>", "<li>{{ ota_samsung_li1 }}</li>"),
    ("<li>Enable <strong>Double press</strong> \u2192 <strong>Open app</strong> \u2192 select <strong><span\n                            class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.\n                </li>", "<li>{{ ota_samsung_li2 }}</li>"),
    ("<li>Double-press the power{{ phil_sen_li2 }} to trigger.</li>", "<li>{{ ota_samsung_li3 }}</li>"),
    ("<h4>Google Pixel (Quick Tap)</h4>", "<h4>{{ ota_h4_pixel }}</h4>"),
    ("<li><strong>Settings</strong> \u2192 <strong>System</strong> \u2192 <strong>Gestures</strong> \u2192 <strong>Quick Tap\n                        to start actions</strong>.</li>", "<li>{{ ota_pixel_li1 }}</li>"),
    ("<li>Enable <strong>Use Quick Tap</strong> \u2192 <strong>Open app</strong> \u2192 select\n                    <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.\n                </li>", "<li>{{ ota_pixel_li2 }}</li>"),
    ("<li>Double-tap the back of your phone to trigger.</li>", "<li>{{ ota_pixel_li3 }}</li>"),
    ("<h4>iPhone 15 Pro+ (Action Button)</h4>", "<h4>{{ ota_h4_iphone_ab }}</h4>"),
    ("<li><strong>Settings</strong> \u2192 <strong>Action Button</strong> \u2192 swipe to <strong>Shortcut</strong>.\n                </li>", "<li>{{ ota_iphone_ab_li1 }}</li>"),
    ("<li>Tap selector \u2192 <strong>Open App</strong> \u2192 choose <strong><span class=\"notranslate\"\n                            translate=\"no\">TapAlert</span></strong>.</li>", "<li>{{ ota_iphone_ab_li2 }}</li>"),
    ("<li>Hold the Action Button to trigger.</li>", "<li>{{ ota_iphone_ab_li3 }}</li>"),
    ("<h4>iPhone \u2014 All Models (Back Tap)</h4>", "<h4>{{ ota_h4_iphone_bt }}</h4>"),
    ("<li><strong>Settings</strong> \u2192 <strong>Accessibility</strong> \u2192 <strong>Touch</strong> \u2192 <strong>Back\n                        Tap</strong>.</li>", "<li>{{ ota_iphone_bt_li1 }}</li>"),
    ("<li>Choose <strong>Double Tap</strong> or <strong>Triple Tap</strong>.</li>", "<li>{{ ota_iphone_bt_li2 }}</li>"),
    ("<li>To link to <span class=\"notranslate\" translate=\"no\">TapAlert</span>, first create a Shortcut:\n                    <ul>\n                        <li>Open <strong>Shortcuts</strong> app \u2192 <strong>+</strong> \u2192 <strong>Add Action</strong> \u2192\n                            <strong>Open App</strong> \u2192 <strong><span class=\"notranslate\"\n                                    translate=\"no\">TapAlert</span></strong>.\n                        </li>\n                        <li>Name it \"Open <span class=\"notranslate\" translate=\"no\">TapAlert</span>\".</li>\n                    </ul>\n                </li>", "<li>{{ ota_iphone_bt_li3 }}\n                    <ul>\n                        <li>{{ ota_iphone_bt_li3a }}</li>\n                        <li>{{ ota_iphone_bt_li3b }}</li>\n                    </ul>\n                </li>"),
    ("<li>Go back to <strong>Back Tap</strong> settings \u2192 select your \"Open <span class=\"notranslate\"\n                        translate=\"no\">TapAlert</span>\" shortcut.</li>", "<li>{{ ota_iphone_bt_li4 }}</li>"),
    ("<h4>Any {{ android_table_th2 }} (Button Mapper Apps)</h4>", "<h4>{{ ota_h4_android_apps }}</h4>"),
    ("<p>If your device lacks {{ phil_priv_li2 }}{{ phil_sen_li2 }} remapping, install <strong>\"Button Mapper\"</strong> or\n                <strong>\"MacroDroid\"</strong> from the Play Store:\n            </p>", "<p>{{ ota_android_apps_p }}</p>"),
    ("<li>Remap any hardware key (volume{{ phil_sen_li2 }}s, etc.) to <strong>Open Application</strong> \u2192\n                    <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>.\n                </li>", "<li>{{ ota_android_apps_li1 }}</li>"),
    ("<li>Press your configured{{ phil_sen_li2 }}/gesture.</li>", "<li>{{ ota_phys_work_li1 }}</li>"),
    ("<li><span class=\"notranslate\" translate=\"no\">TapAlert</span> opens \u2192 the countdown starts\n                    <strong>automatically</strong> (if Auto-Start is enabled).\n                </li>", "<li>{{ ota_phys_work_li2 }}</li>"),
    ("<li>The alert is sent and the app auto-closes.</li>", "<li>{{ ota_phys_work_li3 }}</li>"),
    ("<li>Works even from a locked screen (with proper battery optimization \u2014 see below).</li>", "<li>{{ ota_phys_work_li4 }}</li>"),
    ("<h2>3. \ud83c\udd98 <span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\"\n                    translate=\"no\">SOS</span> / OK)</h2>", "<h2>{{ ota_h2_3 }}</h2>"),
    ("<p><span class=\"notranslate\" translate=\"no\">Panic Mode</span> transforms the entire screen into two giant\n               {{ phil_sen_li2 }}s \u2014 <strong><span class=\"notranslate\" translate=\"no\">SOS</span></strong> and <strong>I'm\n                    OK</strong> \u2014 making it virtually impossible to miss.</p>", "<p>{{ ota_panic_p }}</p>"),
    ("<h3>How to Enable</h3>", "<h3>{{ ota_h3_enable }}</h3>"),
    ("<li>Open <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> and it will open by\n                    default in <span class=\"notranslate\" translate=\"no\">Panic Mode</span>.</li>", "<li>{{ ota_enable_li1 }}</li>"),
    ("<li>Remember: you can switch from Configured message Alerts to <span class=\"notranslate\"\n                        translate=\"no\">Panic mode</span> swiping left/right on the home\n                    screen or tap the mode icon in the top bar.</li>", "<li>{{ ota_enable_li2 }}</li>"),
    ("<li><strong>Tap the large red <span class=\"notranslate\" translate=\"no\">SOS</span>{{ phil_sen_li2 }}</strong> \u2192\n                    countdown starts for an emergency alert.</li>", "<li>{{ ota_panic_work_li1 }}</li>"),
    ("<li><strong>Tap the green I'm OK{{ phil_sen_li2 }}</strong> \u2192 sends a reassurance message.</li>", "<li>{{ ota_panic_work_li2 }}</li>"),
    ("<li><strong>Emergency Call{{ phil_sen_li2 }}</strong> at the bottom dials your local emergency number (112, 911,\n                    etc.).</li>", "<li>{{ ota_panic_work_li3 }}</li>"),
    ("<h3>Trigger Method: Tap vs. Hold</h3>", "<h3>{{ ota_h3_trigger }}</h3>"),
    ("<p>For added safety, you can require a <strong>5-second press-and-hold</strong> instead of a single tap:</p>", "<p>{{ ota_trigger_p }}</p>"),
    ("<li><strong>Settings</strong> \u2192 <strong>Trigger Method</strong> \u2192 <strong>Press & Hold (5s)</strong>.\n                </li>", "<li>{{ ota_trigger_li1 }}</li>"),
    ("<li>This prevents accidental triggers while still being fast enough in emergencies.</li>", "<li>{{ ota_trigger_li2 }}</li>"),
    ("<h2>4. \ud83c\udf99\ufe0f Voice Quick Alert</h2>", "<h2>{{ ota_h2_4 }}</h2>"),
    ("<p>In <span class=\"notranslate\" translate=\"no\">Panic mode</span> you can also send an alert with a\n                <strong>voice-dictated message</strong> in one action \u2014\n                ideal when you can't type.</p>", "<p>{{ ota_voice_p }}</p>"),
    ("<li>Tap the <strong>\ud83c\udf99\ufe0f Microphone</strong>{{ phil_sen_li2 }} next to <span class=\"notranslate\"\n                        translate=\"no\">SOS</span> or I'm OK.</li>", "<li>{{ ota_voice_li1 }}</li>"),
    ("<li>Speak your message.</li>", "<li>{{ ota_voice_li2 }}</li>"),
    ("<li>After speaking the countdown starts automatically with your transcribed voice message attached.</li>", "<li>{{ ota_voice_li3 }}</li>"),
    ("<h2>5. \u23f3 Check-in Timer (Dead Man's Switch)</h2>", "<h2>{{ ota_h2_5 }}</h2>"),
    ("<p>The timer sends an alert <strong>automatically</strong> if you don't check in \u2014 no tap required at all.\n            </p>", "<p>{{ ota_timer_p }}</p>"),
    ("<li>Tap the <strong>\u23f1\ufe0f Timer icon</strong> in the top bar.</li>", "<li>{{ ota_timer_li1 }}</li>"),
    ("<li>Optionally add a custom message.</li>", "<li>{{ ota_timer_li3 }}</li>"),
    ("<li>Start the timer.</li>", "<li>{{ ota_timer_li4 }}</li>"),
    ("<li>A persistent notification counts down the remaining time.</li>", "<li>{{ ota_timer_work_li1 }}</li>"),
    ("<li>If you check in (tap <strong>\"I'm OK / Reset\"</strong>) \u2192 timer resets, no alert sent.</li>", "<li>{{ ota_timer_work_li2 }}</li>"),
    ("<li>If you don't check in \u2192 <span class=\"notranslate\" translate=\"no\">TapAlert</span> automatically sends\n                    your alert with location to all recipients.\n                </li>", "<li>{{ ota_timer_work_li3 }}</li>"),
    ("<p>Perfect for solo activities: hiking, walking home at night, meeting strangers, or traveling alone.\n                </p>", "<p>{{ ota_tip_p2 }}</p>"),
    ("<h2>6. \ud83d\udd0b Critical: Battery Optimization ({{ android_table_th2 }})</h2>", "<h2>{{ ota_h2_6 }}</h2>"),
    ("<p>For <strong>physical{{ phil_sen_li2 }}</strong> and <strong>widget</strong> triggers to work reliably \u2014 especially\n                from a locked/sleeping screen \u2014 you {{ ts_em_li5 }} disable battery optimization for <span class=\"notranslate\"\n                    translate=\"no\">TapAlert</span>.</p>", "<p>{{ ota_battery_p1 }}</p>"),
    ("<h3>Why?</h3>", "<h3>{{ ota_h3_why }}</h3>"),
    ("<p>{{ android_table_th2 }} manufacturers aggressively kill background apps to save battery. This can prevent <span\n                    class=\"notranslate\" translate=\"no\">TapAlert</span> from\n                waking your phone when the screen is off.</p>", "<p>{{ ota_why_p }}</p>"),
    ("<h3>Quick Steps (All Devices)</h3>", "<h3>{{ ota_h3_quick }}</h3>"),
    ("<li><strong>Settings</strong> \u2192 <strong>Apps</strong> \u2192 <strong><span class=\"notranslate\"\n                            translate=\"no\">TapAlert</span></strong> \u2192\n                    <strong>Battery</strong>.\n                </li>", "<li>{{ ota_quick_li1 }}</li>"),
    ("<li>{{ ts_loc_li2 }} <strong>\"Don't optimize\"</strong> or <strong>\"Unrestricted\"</strong>.</li>", "<li>{{ ota_quick_li2 }}</li>"),
    ("<li>Enable <strong>\"Allow background activity\"</strong>.</li>", "<li>{{ ota_quick_li3 }}</li>"),
    ("<h3>Test It</h3>", "<h3>{{ ota_h3_test }}</h3>"),
    ("<li>Lock your phone and wait 1\u20132 minutes (screen fully off).</li>", "<li>{{ ota_test_li1 }}</li>"),
    ("<li>Press your configured physical{{ phil_sen_li2 }} or tap the widget.</li>", "<li>{{ ota_test_li2 }}</li>"),
    ("<li><span class=\"notranslate\" translate=\"no\">TapAlert</span> should open and start the countdown\n                    instantly.</li>", "<li>{{ ota_test_li3 }}</li>"),
    ("<h2>Quick Comparison</h2>", "<h2>{{ ota_h2_comp }}</h2>"),
    ("<th>Method</th>", "<th>{{ ota_th_method }}</th>"),
    ("<th>{{ nav_platform }}</th>", "<th>{{ nav_platform }}</th>"),
    ("<th>Taps to Alert</th>", "<th>{{ ota_th_taps }}</th>"),
    ("<th>Works From Lock Screen</th>", "<th>{{ ota_th_lock }}</th>"),
    ("<th>Requires Setup</th>", "<th>{{ ota_th_setup }}</th>"),
    ("<td>{{ android_table_th2 }} Widget</td>", "<td>{{ ota_td_widget }}</td>"),
    ("<td>Partial*</td>", "<td>{{ ota_td_partial }}</td>"),
    ("<td>Minimal</td>", "<td>{{ ota_td_minimal }}</td>"),
    ("<td>Physical Button + Auto-Start</td>", "<td>{{ ota_td_phys }}</td>"),
    ("<td>\u2705 Yes</td>", "<td>{{ ota_td_yes }}</td>"),
    ("<td>Moderate</td>", "<td>{{ ota_td_mod }}</td>"),
    ("<td><span class=\"notranslate\" translate=\"no\">Panic Mode</span> (<span class=\"notranslate\"\n                                translate=\"no\">SOS</span>{{ phil_sen_li2 }})</td>", "<td>{{ ota_td_panic }}</td>"),
    ("<td>2 (open app + tap)</td>", "<td>{{ ota_td_2taps }}</td>"),
    ("<td>\u2014</td>", "<td>{{ ota_td_dash }}</td>"),
    ("<td>Voice Quick Alert</td>", "<td>{{ ota_td_voice }}</td>"),
    ("<td>2 (open app + tap mic)</td>", "<td>{{ ota_td_2taps_mic }}</td>"),
    ("<td>None</td>", "<td>{{ ota_td_none }}</td>"),
    ("<td>Check-in Timer</td>", "<td>{{ ota_td_timer }}</td>"),
    ("<td>0 (automatic)</td>", "<td>{{ ota_td_0taps }}</td>"),
    ("<p><small>*Widget lock screen support varies by {{ android_table_th2 }} version and manufacturer.</small></p>", "<p>{{ ota_comp_footnote }}</p>"),
    ("<h2>Recommended Configurations</h2>", "<h2>{{ ota_h2_recom }}</h2>"),
    ("<h3>\ud83d\udc74 For Senior Users</h3>", "<h3>{{ ota_h3_recom_senior }}</h3>"),
    ("<li>Use <strong><span class=\"notranslate\" translate=\"no\">Panic Mode</span></strong> (big <span\n                        class=\"notranslate\" translate=\"no\">SOS</span> / I'm OK{{ phil_sen_li2 }}s).</li>", "<li>{{ ota_recom_senior_li1 }}</li>"),
    ("<li>Set <strong>Trigger Method</strong> to <strong>Tap</strong> (simplest interaction).</li>", "<li>{{ ota_recom_senior_li2 }}</li>"),
    ("<li>Add the <strong>{{ android_table_th2 }} widget</strong> to the home screen.</li>", "<li>{{ ota_recom_senior_li3 }}</li>"),
    ("<li>Set countdown to <strong>10 - 15 seconds</strong> (time to cancel mistakes).</li>", "<li>{{ ota_recom_senior_li4 }}</li>"),
    ("<h3>\ud83c\udfc3 For Active / Solo Users</h3>", "<h3>{{ ota_h3_recom_active }}</h3>"),
    ("<li>Set up the <strong>Check-in Timer</strong> before activities.</li>", "<li>{{ ota_recom_active_li1 }}</li>"),
    ("<li>Configure a <strong>physical{{ phil_sen_li2 }}</strong> for instant <span class=\"notranslate\"\n                        translate=\"no\">SOS</span>.</li>", "<li>{{ ota_recom_active_li2 }}</li>"),
    ("<li>Enable <strong><span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span></strong> (auto-<span\n                        class=\"notranslate\" translate=\"no\">fallback</span> between SMS methods).</li>", "<li>{{ ota_recom_active_li3 }}</li>"),
    ("<li>Enable <strong>Email Redundancy</strong> for areas with Wi-Fi only.</li>", "<li>{{ ota_recom_active_li4 }}</li>"),
    ("<h3>\ud83d\udd12 For Maximum Security</h3>", "<h3>{{ ota_h3_recom_secure }}</h3>"),
    ("<li>Configure <strong>physical{{ phil_sen_li2 }}</strong> with <strong>Auto-Start</strong>.</li>", "<li>{{ ota_recom_secure_li1 }}</li>"),
    ("<li>Set <strong>Trigger Method</strong> to <strong>Press & Hold (5s)</strong> to prevent accidental\n                    triggers.</li>", "<li>{{ ota_recom_secure_li2 }}</li>"),
    ("<li>Enable <strong>both</strong> <span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span> and\n                    Email Redundancy.</li>", "<li>{{ ota_recom_secure_li3 }}</li>"),
    ("<li>Disable battery optimization and test from locked screen.</li>", "<li>{{ ota_recom_secure_li4 }}</li>")
]

replace_in_file('src/one_tap_alert.html', replacements)
print("Updated one_tap_alert.html")

