import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        if k not in en:
            en[k] = v
    for k, v in new_es.items():
        if k not in es:
            es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "ug_h2_6": "6. 📧 Configuring Email Redundancy",
    "ug_p15": "If you have no cellular signal but are connected to Wi-Fi, <span class=\"notranslate\" translate=\"no\">TapAlert</span> can send your alert via email.",
    "ug_h3_12": "Setup Instructions",
    "ug_li14_1": "<strong>Open Settings:</strong> Tap the gear icon ⚙️ and select <strong>Email Redundancy</strong>.",
    "ug_li14_2": "<strong>Enable the feature:</strong> Toggle <strong>Enable Email Redundancy</strong> to ON.",
    "ug_li14_3_1": "<strong>SMTP Configuration:</strong> Enter your email provider's SMTP details:",
    "ug_li14_3_2": "<strong>SMTP Host:</strong> (e.g., <code>smtp.gmail.com</code> for Gmail, <code>smtp-mail.outlook.com</code> for Outlook).",
    "ug_li14_3_3": "<strong>SMTP Port:</strong> (e.g., <code>587</code> or <code>465</code>).",
    "ug_li14_3_4": "<strong>Username / Email:</strong> Your full email address.",
    "ug_li14_3_5": "<strong>Password / App Password:</strong> Your email password or a dedicated App Password.",
    "ug_h3_13": "⚡ Quick Setup (Common Providers)",
    "ug_p16": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> includes preset{{ phil_sen_li2 }}s for popular email providers. Simply tap a preset{{ phil_sen_li2 }} to auto-fill the SMTP host and port settings:",
    "ug_p17": "After tapping a preset, you only need to enter your email address and app password (see below).",
    "ug_note_3": "<strong>IMPORTANT: App Passwords Are Provider-Specific</strong><br> Each email provider has its own app password system. You cannot use a Gmail app password with Outlook, or vice versa. You {{ ts_em_li5 }} generate an app password specific to the provider you're using.",
    "ug_h3_14": "🔒 Using App Passwords (Recommended)",
    "ug_p18": "For security and reliability, we strongly recommend using an <strong>App Password</strong> instead of your primary password.",
    "ug_li15_1": "<strong>Why?</strong> It bypasses 2-Factor Authentication and keeps your main {{ qa_step3_p4 }} secure.",
    "ug_h4_1": "Gmail",
    "ug_li16_1": "Go to your <strong>Google Account > Security</strong> or <a href=\"https://my{{ qa_step3_p4 }}.google.com/apppasswords\" target=\"_blank\">https://my{{ qa_step3_p4 }}.google.com/apppasswords</a>",
    "ug_li16_2": "Search for <strong>\"App passwords\"</strong> (requires 2-step verification enabled).",
    "ug_li16_3": "Generate a new password for \"Other\" and call it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li16_4": "Use the 16-character code provided in <span class=\"notranslate\" translate=\"no\">TapAlert</span> (blanks included).",
    "ug_h4_2": "Outlook / Hotmail / Live",
    "ug_li17_1": "Go to <strong>Microsoft Account > Security > Advanced security options</strong> or <a href=\"https://{{ qa_step3_p4 }}.live.com/names/manage\" target=\"_blank\">https://{{ qa_step3_p4 }}.live.com/names/manage</a>.",
    "ug_li17_2": "Under <strong>\"App passwords\"</strong>, create a new app password.",
    "ug_li17_3": "{{ ts_loc_li2 }} \"Other\" and name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li17_4": "Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h4_3": "Yahoo",
    "ug_li18_1": "Go to <strong>Yahoo Account Security</strong> or <a href=\"https://login.yahoo.com/{{ qa_step3_p4 }}/security\" target=\"_blank\">https://login.yahoo.com/{{ qa_step3_p4 }}/security</a>.",
    "ug_li18_2": "{{ ts_loc_li2 }} <strong>\"Generate app password\"</strong>.",
    "ug_li18_3": "Choose \"Other App\" and name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li18_4": "Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h4_4": "iCloud",
    "ug_li19_1": "Go to <strong>appleid.apple.com > Sign-In and Security > App-Specific Passwords</strong> or <a href=\"https://appleid.apple.com/{{ qa_step3_p4 }}/manage\" target=\"_blank\">https://appleid.apple.com/{{ qa_step3_p4 }}/manage</a>.",
    "ug_li19_2": "Click the <strong>+</strong>{{ phil_sen_li2 }} to generate a new password.",
    "ug_li19_3": "Name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li19_4": "Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h3_15": "Recipients",
    "ug_p19": "Emails will be sent to all contacts in your <strong>Recipients</strong> list who have an email address saved. To add an email to a contact:",
    "ug_li20_1": "Go to the <strong>Recipients</strong> screen.",
    "ug_li20_2": "{{ sms_ios_li1 }} a contact and ensure the email field is filled.",
    "ug_h3_16": "🧪 Testing",
    "ug_p20": "Before relying on it, tap <strong>Test Connection</strong>. Enter an email address to receive a test message. If successful, your setup is correct.",
    "ug_h2_7": "7. 📱 {{ feat_widget_title }} ({{ android_table_th2 }} Only)",
    "ug_p21": "For even faster emergency alerts, you can add a widget to your {{ android_table_th2 }} home screen:",
    "ug_h3_17": "Adding the Widget",
    "ug_li21_1": "<strong>Open Settings:</strong> Tap the gear icon ⚙️ in the app.",
    "ug_li21_2": "<strong>Find Widget Section:</strong> Scroll down to the \"Widget\" section.",
    "ug_li21_3": "<strong>Tap \"Add\":</strong> The system will prompt you to place the widget on your home screen.",
    "ug_li21_4": "<strong>Position the Widget:</strong> Drag it to your preferred location and release.",
    "ug_note_4": "<strong>NOTE:</strong> If you already have a widget on your home screen, you'll need to remove the old one before adding a new one.",
    "ug_h3_18": "Using the Widget",
    "ug_li22_1": "<strong>Tap the Widget:</strong> Opens the app and starts the <strong>Countdown</strong> immediately.",
    "ug_li22_2": "<strong>App Experience:</strong> You will see the countdown dialog, ensuring the alert is intentional. You can cancel it if pressed by mistake.",
    "ug_li22_3": "<strong>Sound:</strong> The app plays an audible alert tone while counting down.",
    "ug_tip_2": "<strong>TIP:</strong> The widget is perfect for true emergencies when you need to send an alert with a single tap, {{ ts_loc_li7 }} finding the app in your drawer.",
    "ug_h2_8": "8. 🚀 Sending an Alert",
    "ug_li23_1": "<strong>{{ sms_so_li1_1 }} App.</strong>",
    "ug_li23_2_1": "<strong>Trigger the Alert:</strong>",
    "ug_li23_2_2": "<strong>In Report Mode:</strong> Tap the large red <strong>SEND ALERT</strong>{{ phil_sen_li2 }}. The message selected in the tabs (1-4) will be sent.",
    "ug_li23_2_3": "<strong>In <span class=\"notranslate\" translate=\"no\">Panic Mode</span>:</strong>",
    "ug_li23_2_4": "Tap the big red <strong><span class=\"notranslate\" translate=\"no\">SOS</span></strong> {{ phil_sen_li2 }} to send a \"Help needed\" alert.",
    "ug_li23_2_5": "Tap the <strong>Microphone icon</strong> (bottom-right of <span class=\"notranslate\" translate=\"no\">SOS</span>) to record and send a specific voice message with your <span class=\"notranslate\" translate=\"no\">SOS</span> alert.",
    "ug_li23_2_6": "Tap the green <strong>I'm OK</strong>{{ phil_sen_li2 }} to send a reassuring \"I'm OK\" status.",
    "ug_li23_2_7": "Tap the <strong>Microphone icon</strong> (bottom-right of I'm OK) to record and send a voice message with your OK status.",
    "ug_li23_2_8": "Tap the <strong>Emergency Call</strong>{{ phil_sen_li2 }} to dial local emergency services immediately.",
    "ug_li23_3_1": "<strong>The app will:</strong>",
    "ug_li23_3_2": "Fetch your current location (if configured).",
    "ug_li23_3_3": "Show a <strong>Countdown Dialog</strong> (see \"Countdown Dialog\" below).",
    "ug_li23_3_4": "Send the alert message to all recipients.",
    "ug_h2_9": "9. ⏱️ Countdown Dialog",
    "ug_p22": "To prevent accidental alerts, <span class=\"notranslate\" translate=\"no\">TapAlert</span> shows a countdown before sending.",
    "ug_li24_1": "<strong>Countdown Duration:</strong> By default, the app waits <strong>10 seconds</strong>. You can customize this in <strong>Settings</strong> (from <strong>0s</strong> for immediate sending up to <strong>30s</strong>).",
    "ug_li24_2": "<strong>Cancelling:</strong> You can tap <strong>CANCEL</strong> during the countdown to stop the alert.",
    "ug_h2_10": "10. 🔔 Making Alert SMS Stand Out",
    "ug_p23": "To ensure your emergency contacts don't miss your alert message among other notifications, we recommend configuring their phones to treat messages from your <span class=\"notranslate\" translate=\"no\">TapAlert</span> number differently.",
    "ug_h3_19": "{{ sms_so_h2_1b }}",
    "ug_li25_1": "<strong>Open {{ sms_so_li1_2 }}:</strong> {{ sms_so_step1 }}",
    "ug_li25_2": "<strong>{{ sms_so_step2 }}</strong> Tap <strong>{{ sms_ios_li1 }}</strong> > <strong>{{ sms_ios_li2 }}</strong> (or Text Tone) and toggle <strong>{{ sms_so_bypass }}</strong> ON. This allows sounds/vibrations even if their phone is on Silent or Do Not Disturb.",
    "ug_li25_3": "<strong>{{ sms_so_tone }}</strong> Choose a loud, distinct sound for your messages.",
    "ug_h3_20": "For {{ android_table_th2 }} Recipients",
    "ug_li26_1": "<strong>{{ sms_so_and_1 }}</strong> {{ sms_so_and_2 }}",
    "ug_li26_2": "<strong>{{ sms_so_and_3 }}</strong> Tap <strong>{{ sms_and_li1 }}</strong> > <strong>{{ sms_and_li2 }}</strong>.",
    "ug_li26_3": "<strong>Set as {{ sms_and_li5 }}:</strong> {{ sms_and_li3 }} <strong>{{ sms_and_li4 }}</strong> or <strong>{{ sms_and_li5 }}</strong>.",
    "ug_li26_4": "<strong>{{ sms_so_and_4 }}</strong> {{ sms_and_li6 }} <strong>{{ sms_and_li7 }}</strong> is enabled for this conversation.",
    "ug_li26_5": "<strong>{{ sms_so_and_5 }}</strong> {{ sms_so_and_6 }}",
    "ug_note_5": "<strong>NOTE: Using <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong> If you send alerts via <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, your contacts will receive the message from your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> number or an Alphanumeric ID (e.g., \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\"). {{ sms_twilio_p3 }} <strong>{{ ts_em_li5 }}</strong> add this number/ID to their contacts list for the settings above to work correctly. Otherwise, the message will still be delivered but{{ price_disclaimer3 }}standard SMS {{ ts_loc_li7 }} any priority notifications.",
    "ug_h2_11": "11. 🕰️ Alert History",
    "ug_p24": "To keep track of your sent emergency alerts:",
    "ug_li27_1": "<strong>Tap the History Icon:</strong> The clock icon 🕰️ located in the top bar.",
    "ug_li27_2": "<strong>View Recent Alerts:</strong> The app maintains a log of the last <strong>50 alerts</strong> sent.",
    "ug_li27_3": "<strong>Check Status:</strong> Tap any entry to see exactly which recipients received the message successfully and which failed (with error details).",
    "ug_li27_4": "<strong>Clear History:</strong> You can delete all logs by tapping the trash icon 🗑️ inside the history screen.",
    "ug_h2_12": "12. ❓ {{ nav_troubleshooting }}",
    "ug_li28_1": "<strong>Message not sending (<span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span>):</strong> Check your mobile signal and carrier credit ({{ android_table_th2 }} only).",
    "ug_li28_2": "<strong>Message not sending (<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>):</strong> Verify your internet connection and double-check your credentials in the settings.",
    "ug_li28_3": "<strong>{{ ts_li1_5 }} missing:</strong> {{ sms_and_li6 }} GPS is enabled in your phone's system settings and the app has {{ ts_li1_5 }} permission.",
    "ug_li28_4": "<strong>{{ sms_so_li1_2 }} missing (iOS):</strong> Go to Settings > {{ table_r2c1 }} > {{ sms_so_li1_2 }} > <span class=\"notranslate\" translate=\"no\">TapAlert</span> and ensure <strong>\"All {{ sms_so_li1_2 }}\"</strong> is checked.",
    "ug_li28_5": "<strong>{{ sms_so_li1_2 }} missing ({{ android_table_th2 }}):</strong> Go to Settings > Apps > <span class=\"notranslate\" translate=\"no\">TapAlert</span> > Permissions and ensure <strong>\"{{ sms_so_li1_2 }}\"</strong> is allowed.",
    "ug_h2_13": "13. ⏳ Check-in Timer",
    "ug_p25": "The <strong>Check-in Timer</strong> is an \"inactive\" safety feature. It allows you to set a timer when starting a potentially risky activity (e.g., walking home alone, going on a hike).",
    "ug_li29_1": "<strong>Start the Timer:</strong> {{ ts_loc_li2 }} a duration (from 5 minutes up to 24 hours) and an optional message.",
    "ug_li29_2": "<strong>The Countdown:</strong> A persistent notification will show you the remaining time.",
    "ug_li29_3": "<strong>The Check-in:</strong> You {{ ts_em_li5 }} return to the app and tap <strong>\"I'm OK (Reset)\"</strong> before the timer expires.",
    "ug_li29_4": "<strong>Automatic Alert:</strong> If you <em>don't</em> reset the timer before it hits zero, <span class=\"notranslate\" translate=\"no\">TapAlert</span> will automatically send your alert message and location to all recipients."
}


es_keys = {
    "ug_h2_6": "6. \ud83d\udce7 Configurando el Respaldo por Email",
    "ug_p15": "Si no tienes se\u00f1al celular pero est\u00e1s conectado a Wi-Fi, <span class=\"notranslate\" translate=\"no\">TapAlert</span> puede enviar tu alerta v\u00eda correo electr\u00f3nico.",
    "ug_h3_12": "Instrucciones de Configuraci\u00f3n",
    "ug_li14_1": "<strong>Abrir Ajustes:</strong> Toca el logo de engranaje \u2699\ufe0f y selecciona <strong>Respaldo por Email</strong>.",
    "ug_li14_2": "<strong>Habilitar la caracter\u00edstica:</strong> Activa el bot\u00f3n <strong>Habilitar Respaldo por Email</strong>.",
    "ug_li14_3_1": "<strong>Configuraci\u00f3n SMTP:</strong> Ingresa los datos del servidor de tu proveedor de correo:",
    "ug_li14_3_2": "<strong>Servidor SMTP:</strong> (ej., <code>smtp.gmail.com</code> para Google, <code>smtp-mail.outlook.com</code> para Outlook).",
    "ug_li14_3_3": "<strong>Puerto SMTP:</strong> (ej., <code>587</code> o <code>465</code>).",
    "ug_li14_3_4": "<strong>Usuario / Email:</strong> Tu direcci\u00f3n de correo completa.",
    "ug_li14_3_5": "<strong>Contrase\u00f1a / Contrase\u00f1a de Aplicaci\u00f3n:</strong> Tu contrase\u00f1a actual o una clave creada especialmente para Aplicaci\u00f3n.",
    "ug_h3_13": "\u26a1 Ajuste R\u00e1pido (Proveedores Comunes)",
    "ug_p16": "<span class=\"notranslate\" translate=\"no\">TapAlert</span> cuenta con atajos f\u00e1cilmente configurables. S\u00f3lo elige el tuyo para autocompletar la secci\u00f3n de Host y Puerto:",
    "ug_p17": "Luego de tocar un atajo, \u00fanicamente escribe tu direcci\u00f3n actual de correo y contrase\u00f1a para proceder.",
    "ug_note_3": "<strong>IMPORTANTE: Cada App necesita diferentes Contrase\u00f1as</strong><br> Cada proveedor requiere contrase\u00f1as con reglas y formatos \u00fanicos. No funciona copiar tu contrase\u00f1a de Gmail y colocar en otra categor\u00eda. T\u00fa {{ ts_em_li5 }} que generar tu clave especial.",
    "ug_h3_14": "\ud83d\udd12 Uso de las Contrase\u00f1as de Aplicaci\u00f3n (Recomendado)",
    "ug_p18": "Por mayor seguridad y rapidez, exhortamos el uso exclusivo de la <strong>Contrase\u00f1a Especial de Aplicaci\u00f3n</strong> y no tu acceso principal.",
    "ug_li15_1": "<strong>\u00bfPor qu\u00e9?</strong> Debido a no tener que introducir c\u00f3digos adicionales de 2 factor authentication cada mes.",
    "ug_h4_1": "Gmail",
    "ug_li16_1": "Navega a la p\u00e1gina de <strong>Google Account > Security</strong> o <a href=\"https://my{{ qa_step3_p4 }}.google.com/apppasswords\" target=\"_blank\">https://my{{ qa_step3_p4 }}.google.com/apppasswords</a>",
    "ug_li16_2": "Busca la secci\u00f3n de <strong>\"App passwords\"</strong> (2 passwords validation requerido).",
    "ug_li16_3": "Genera el nombre que se vincular\u00e1 \"Other\" con un cl\u00e1sico como \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li16_4": "Introduce esa mezcla en <span class=\"notranslate\" translate=\"no\">TapAlert</span> y ya (espacios no aceptados).",
    "ug_h4_2": "Outlook / Hotmail / Live",
    "ug_li17_1": "Navegue a la secci\u00f3n de Administraci\u00f3n de Seguriidad o <a href=\"https://{{ qa_step3_p4 }}.live.com/names/manage\" target=\"_blank\">https://{{ qa_step3_p4 }}.live.com/names/manage</a>.",
    "ug_li17_2": "Cree ahora ah\u00ed la nueva clave especial.",
    "ug_li17_3": "{{ ts_loc_li2 }} \"Others\" como t\u00edtulo y asign\u00e9 \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li17_4": "Procopiela al men\u00fa en app principal de <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h4_3": "Yahoo",
    "ug_li18_1": "Abre Yahoo Configura o <a href=\"https://login.yahoo.com/{{ qa_step3_p4 }}/security\" target=\"_blank\">https://login.yahoo.com/{{ qa_step3_p4 }}/security</a>.",
    "ug_li18_2": "{{ ts_loc_li2 }} <strong>\"Crear Contrase\u00f1a\"</strong>.",
    "ug_li18_3": "Para otro como \"Other App\" ingresen una menci\u00f3n visible a \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li18_4": "Colaborar la misma que otorgaron nuevamente pero ahora en <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h4_4": "iCloud",
    "ug_li19_1": "Ingresen aappleid.apple.com con normalidad, para entrar a las opciones y App-Specific Passwords o utilicen <a href=\"https://appleid.apple.com/{{ qa_step3_p4 }}/manage\" target=\"_blank\">https://appleid.apple.com/{{ qa_step3_p4 }}/manage</a>.",
    "ug_li19_2": "Ubicando su atenci\u00f3n toquen el gran s\u00edmbolo de <strong>+</strong> y gener\u00e9 nueva credencial.",
    "ug_li19_3": "Y llamando este de paso por identificaro \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".",
    "ug_li19_4": "El resultado escri\u00edba en <span class=\"notranslate\" translate=\"no\">TapAlert</span>.",
    "ug_h3_15": "Destinatarios",
    "ug_p19": "Los correos se enviar\u00e1n masivamente de esta manera s\u00f3lamente con las personas anotadas en correo electr\u00f3nico:",
    "ug_li20_1": "Mueva las pesta\u00f1as hacia la <strong>Librer\u00eda</strong> central.",
    "ug_li20_2": "Escoge a una persona particular, toca y valida llenar la informaci\u00f3n precisa.",
    "ug_h3_16": "\ud83e\uddea Testing",
    "ug_p20": "Asegura todos est\u00e9s funcionando correctamentee mediante pruebas de Conexi\u00f3n. Selecciona los correos para la autoayuda a todos env\u00edo validando que nada falte.",
    "ug_h2_7": "7. \ud83d\udcf1 {{ feat_widget_title }} (Solo {{ android_table_th2 }})",
    "ug_p21": "Un atajo siempre a la mano a manera m\u00e1s f\u00e1cill sin bloqueaar de las dem\u00e1s vistas:",
    "ug_h3_17": "Agreggando sus accesos",
    "ug_li21_1": "<strong>Ajustess:</strong> Dentro t\u00fa pulsa ⚙️ de vuelta al inicioo.",
    "ug_li21_2": "<strong>El apartado Widget:</strong> Mu\u00e9velo hacia el panel del apartado exacto.",
    "ug_li21_3": "<strong>Opci\u00f3n final \"Agregar\":</strong> Autom\u00e1ticamente confirmar\u00e1s su a\u00f1adido a su panel primarioo.",
    "ug_li21_4": "<strong>Un paso y soltarlo:</strong> Donde requieran su posici\u00f3n, al s\u00f3lo dejarlo caer tendr\u00e1s final.",
    "ug_note_4": "<strong>NOTA:</strong> Si t\u00fa deseas instalar repetidamente m\u00e1s, debes borrar una para habilitarl nuevamente.",
    "ug_h3_18": "Maniobrando sus ventajas",
    "ug_li22_1": "<strong>Pulsaci\u00f3n s\u00f3lo a un click:</strong> Abrir la aplicaci\u00f3n  e interrogar un reloj contador sin preguntar.",
    "ug_li22_2": "<strong>Resumen interno Visual:</strong> Entendiendo al usuario se otorga su momento si no quiso enviar la alerta final en el contador mostrado.",
    "ug_li22_3": "<strong>Reconocimiento:</strong> Avisar un volumen a su m\u00e1ximo notificaciones de la app.",
    "ug_tip_2": "<strong>CONSEJO:</strong>  Ideal para escenarios p\u00e9riidss debido estar cerca del bot\u00f3n de un panel inicial para no requerir busquedas innecesarias..",
    "ug_h2_8": "8. \ud83d\ude80 M\u00e9todo de Lanzamiento de su se\u00f1al",
    "ug_li23_1": "<strong>Abrir aplicaci\u00f3n.</strong>",
    "ug_li23_2_1": "<strong>Se\u00f1al a reacci\u00f3n:</strong>",
    "ug_li23_2_2": "<strong>Modos est\u00e1ndares con men\u00fas:</strong> Con t\u00fa pulso inicia todo este procedimiento veloz y autom\u00e1tico.",
    "ug_li23_2_3": "<strong>Al estar encendidos en modo  p\u00e1nicos </strong>",
    "ug_li23_2_4": "Alerta gigante roja en  en la mitad inicia el caos principal.",
    "ug_li23_2_5": "<strong>Acciones a usar sonido por micr\u00f3fono: </strong> Iniciar tus acciones y su interacci&oacue;n.",
    "ug_li23_2_6": "Acciones secundarias de luz Verde te indican <strong>Estoy Bien</strong>.",
    "ug_li23_2_7": "En la de luz verde tu podr\u00e1s mandar su acci\u00f3n respectiva.",
    "ug_li23_2_8": "Para pedir se\u00f1al de socorro hay botones extra que t\u00fa requieres local.",
    "ug_li23_3_1": "<strong>Sistema aut\u00f3nomamente de app :</strong>",
    "ug_li23_3_2": "Generen una extracci\u00f3n gps en tiempoo reale.",
    "ug_li23_3_3": "Ventana un peque\u00f1o relog final en pantalla retroactiva (visibles detalladas secci\u00f3nes extras)abajo).",
    "ug_li23_3_4": "Enviarlos ya y automa&iacute;tico para todos lo vincul\u00e1dos.",
    "ug_h2_9": "9. \u23f1\ufe0f Cuadro regresivorelojj",
    "ug_p22": "M\u00e1s seguro evitamos accionar a causa de equivocaciones sin aviso <span class=\"notranslate\" translate=\"no\">TapAlert</span> siempre generar\u00e1 protecciones previas.",
    "ug_li24_1": "<strong>Lapsos del retraso de cuenta :</strong> Empiezan del valor default usualmente 10 <strong> segundos</strong> y personalizable total a como t\u00fa los adecuees a t\u00fa vida m\u00edmino valor es sin restraso .",
    "ug_li24_2": "<strong>Evasi\u00f3n temporal:</strong> Sin la necesidad para de nada se de  CANCELAR a mitad interponte si en eso fallaste para que  se apague el env\u00edo autom\u00e1tico totalmente al final de esta.",
    "ug_h2_10": "10. \ud83d\udd14 Priorizando llamadas SMS m\u00e1s alta visibilidad",
    "ug_p23": "Grarantizamos sus notificaciones sin ning\u00fan peligro con la garant\u00eda de evitar perdida o mezclen de app m\u00e1viles extras ajustando su tel\u00e9fono m\u00f3til a favor a <span class=\"notranslate\" translate=\"no\">TapAlert</span>",
    "ug_h3_19": "Contactos usuarios en modelos y marca Apple",
    "ug_li25_1": "<strong>Pantalla del libretos :</strong> {{ sms_so_step1 }}.",
    "ug_li25_2": "<strong>{{ sms_so_step2 }}</strong> Presionar sobre  <strong>{{ sms_ios_li1 }}</strong> > <strong>{{ sms_ios_li2 }}</strong> o sonidos textos y dejarlo <strong>ENCENDIDO {{ sms_so_bypass }}</strong> . Que te evitar\u00e1n bloqueos en Modo sin Interrupciones",
    "ug_li25_3": "<strong>Tiempos: </strong> Puedes configurar para identificar  ruido extras del habitual",
    "ug_h3_20": "Destinatarios modeloss de SO en marca Google",
    "ug_li26_1": "<strong>Ir : </strong> App predeterminado  de {{ term_ios_messages }}.",
    "ug_li26_2": "<strong>Visualiza y selecciona tu : </strong> Tu charlla actual  luego > <strong>Opciones sobre este canal.</strong>  ",
    "ug_li26_3": "<strong>Reconfigura a M\u00e1xima prioridad  </strong> Ajustar a {{ sms_and_li4 }} las dem\u00e1s alertas y sonidos",
    "ug_li26_4": "<strong>El \u00fanico a no dudar  </strong> Que <strong>{{ sms_and_li7 }} </strong> est\u00e9 vigente activadamente por chat e im\u00e1genes",
    "ug_li26_5": "<strong>Ignonar  :  Modo descansando </strong>",
    "ug_note_5": "<strong>NOTA: Soportes o usos a tecnolog\u00edas ccomo la compa\u00f1ia l\u00edder en nube <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong> Asegurar al destinatario todos t\u00fa tel\u00e9fono y nomb\u00e9es a registrarte debido que los SMS saldr\u00e1  s\u00f3lo con un n\u00famero desconocido. Deben ellos grabarlo manualmente a contact  para ser considerados de M\u00e1s prioridad del Sistema general sino s\u00f3olo llegar\u00e1 sin atenci\u00f3n preeferencial del d\u00eda a d\u00edaa.",
    "ug_h2_11": "11. \ud83d\udd70\ufe0f Historial Completo sobre todas alertas emitidias ",
    "ug_p24": "Podr\u00e1n controlar o registrar el archivo as\u00ed:",
    "ug_li27_1": "<strong>Pulza y activa a icono final </strong> El famoso simbolo el \u23f2\ufe0f reloj y m\u00e1s ",
    "ug_li27_2": "<strong>Registros anteriores 50 enviaos:</strong> Y adem\u00e1ss est\u00e1n grabadas ah\u00ed .",
    "ug_li27_3": "<strong>Detallles d estado exactos:</strong> Con esto observareis envíos q han llogar bien sin problemas adem\u00e1ss detallae que sal&oacute;r\u00f3n m\u00e1l",
    "ug_li27_4": "<strong>Lavaado todo un hstoril m\u00e1sss allall de limpte  </strong>",
    "ug_h2_12": "12. \u2753 {{ nav_troubleshooting }} \u00bfDudas\u00bf\u00bf",
    "ug_li28_1": "<strong>No llega mensajes ( M\u00e9todo<span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ): </strong> Tu t\u00e9n y ten en cuentga aserctaar las se\u00f1ales celula\u00e9reas. ",
    "ug_li28_2": "<strong>Mnsj no mandados o retenido de ( M&eth;todo <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> ): </strong> Chequea internetes de WI\u00cd-FIE y conexi\u00f3nas de de a la internet local en red.",
    "ug_li28_3": "<strong>{{ ts_li1_5 }} Fallosa GPS no fujnciona  </strong> Sabe habilitado y permiso todo d\u00edas no temporalesl GPS .",
    "ug_li28_4": "<strong>Listados Contact\u00f3s mal configudos nulo iPhone :  </strong> Habil\u00edtado todoss lo qu te pide a {{ table_r2c1 }} por  <span class=\"notranslate\" translate=\"no\">TapAlert</span>",
    "ug_li28_5": "<strong>Listaos \u00e2 Contactos no vis\u00ednles de SO para Androdi  </strong> Chequea app permosos totales s\u00f3lo d\u00e1  Aceptar todos Contactoss <strong>todos accesos\u00bf",
    "ug_h2_13": "13. \u23f3 Cuantificador y  Conometro Checqueadsooorrs de Actividda",
    "ug_p25": "La mejor tecnolog\u00edaa pasiva e innnnovada segura para avisoo y emergencias del conmetro que sirve sin tocra un click cuando caminabas",
    "ug_li29_1": "<strong>Iniciar relogd Temporizaarodoor:</strong> Colocaa a dsu interrvalo o mensaje opcoiional .",
    "ug_li29_2": "<strong>En cuenta m\u00e1s atr&aacute;ss: </strong> Alarman persistented",
    "ug_li29_3": "<strong>Su chqueeoo:</strong> Entra de nuevo antes al expirarse de presionar boton \"Estoy ok reincicar \".",
    "ug_li29_4": "<strong>Automatizar lalert a t\u00fau favoorr : </strong> Llleer a  cero su tiemoo o de vida <span class=\"notranslate\" translate=\"no\">TapAlert</span> mandar\u00e2 su inforrmci\u00f3n autom\u00e1tica."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<h2>6. 📧 Configuring Email Redundancy</h2>", "<h2>{{ ug_h2_6 }}</h2>"),
    ("<p>If you have no cellular signal but are connected to Wi-Fi, <span class=\"notranslate\"\n                    translate=\"no\">TapAlert</span> can send your alert via email.</p>", "<p>{{ ug_p15 }}</p>"),
    ("<h3>Setup Instructions</h3>", "<h3>{{ ug_h3_12 }}</h3>"),
    ("<li><strong>Open Settings:</strong> Tap the gear icon ⚙️ and select <strong>Email Redundancy</strong>.\n                </li>", "<li>{{ ug_li14_1 }}</li>"),
    ("<li><strong>Enable the feature:</strong> Toggle <strong>Enable Email Redundancy</strong> to ON.</li>", "<li>{{ ug_li14_2 }}</li>"),
    ("<li><strong>SMTP Configuration:</strong> Enter your email provider's SMTP details:\n                    <ul>\n                        <li><strong>SMTP Host:</strong> (e.g., <code>smtp.gmail.com</code> for Gmail,\n                            <code>smtp-mail.outlook.com</code> for Outlook).\n                        </li>\n                        <li><strong>SMTP Port:</strong> (e.g., <code>587</code> or <code>465</code>).</li>\n                        <li><strong>Username / Email:</strong> Your full email address.</li>\n                        <li><strong>Password / App Password:</strong> Your email password or a dedicated App Password.\n                        </li>\n                    </ul>\n                </li>", "<li>{{ ug_li14_3_1 }}\n                    <ul>\n                        <li>{{ ug_li14_3_2 }}</li>\n                        <li>{{ ug_li14_3_3 }}</li>\n                        <li>{{ ug_li14_3_4 }}</li>\n                        <li>{{ ug_li14_3_5 }}</li>\n                    </ul>\n                </li>"),
    ("<h3>⚡ Quick Setup (Common Providers)</h3>", "<h3>{{ ug_h3_13 }}</h3>"),
    ("<p><span class=\"notranslate\" translate=\"no\">TapAlert</span> includes preset{{ phil_sen_li2 }}s for popular email\n                providers. Simply tap a preset{{ phil_sen_li2 }} to auto-fill the\n                SMTP host and port settings:</p>", "<p>{{ ug_p16 }}</p>"),
    ("<p>After tapping a preset, you only need to enter your email address and app password (see below).</p>", "<p>{{ ug_p17 }}</p>"),
    ("<strong>IMPORTANT: App Passwords Are Provider-Specific</strong><br>\n                Each email provider has its own app password system. You cannot use a Gmail app password with Outlook,\n                or vice versa. You {{ ts_em_li5 }} generate an app password specific to the provider you're using.", "{{ ug_note_3 }}"),
    ("<h3>🔒 Using App Passwords (Recommended)</h3>", "<h3>{{ ug_h3_14 }}</h3>"),
    ("<p>For security and reliability, we strongly recommend using an <strong>App Password</strong> instead of\n                your primary password.</p>", "<p>{{ ug_p18 }}</p>"),
    ("<li><strong>Why?</strong> It bypasses 2-Factor Authentication and keeps your main {{ qa_step3_p4 }} secure.</li>", "<li>{{ ug_li15_1 }}</li>"),
    ("<h4>Gmail</h4>", "<h4>{{ ug_h4_1 }}</h4>"),
    ("<li>Go to your <strong>Google Account > Security</strong> or <a\n                        href=\"https://my{{ qa_step3_p4 }}.google.com/apppasswords\"\n                        target=\"_blank\">https://my{{ qa_step3_p4 }}.google.com/apppasswords</a></li>", "<li>{{ ug_li16_1 }}</li>"),
    ("<li>Search for <strong>\"App passwords\"</strong> (requires 2-step verification enabled).</li>", "<li>{{ ug_li16_2 }}</li>"),
    ("<li>Generate a new password for \"Other\" and call it \"<span class=\"notranslate\"\n                        translate=\"no\">TapAlert</span>\".</li>", "<li>{{ ug_li16_3 }}</li>"),
    ("<li>Use the 16-character code provided in <span class=\"notranslate\" translate=\"no\">TapAlert</span>\n                    (blanks included).</li>", "<li>{{ ug_li16_4 }}</li>"),
    ("<h4>Outlook / Hotmail / Live</h4>", "<h4>{{ ug_h4_2 }}</h4>"),
    ("<li>Go to <strong>Microsoft Account > Security > Advanced security options</strong> or <a\n                        href=\"https://{{ qa_step3_p4 }}.live.com/names/manage\"\n                        target=\"_blank\">https://{{ qa_step3_p4 }}.live.com/names/manage</a>.</li>", "<li>{{ ug_li17_1 }}</li>"),
    ("<li>Under <strong>\"App passwords\"</strong>, create a new app password.</li>", "<li>{{ ug_li17_2 }}</li>"),
    ("<li>{{ ts_loc_li2 }} \"Other\" and name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".</li>", "<li>{{ ug_li17_3 }}</li>"),
    ("<li>Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.</li>", "<li>{{ ug_li17_4 }}</li>"),
    ("<h4>Yahoo</h4>", "<h4>{{ ug_h4_3 }}</h4>"),
    ("<li>Go to <strong>Yahoo Account Security</strong> or <a href=\"https://login.yahoo.com/{{ qa_step3_p4 }}/security\"\n                        target=\"_blank\">https://login.yahoo.com/{{ qa_step3_p4 }}/security</a>.</li>", "<li>{{ ug_li18_1 }}</li>"),
    ("<li>{{ ts_loc_li2 }} <strong>\"Generate app password\"</strong>.</li>", "<li>{{ ug_li18_2 }}</li>"),
    ("<li>Choose \"Other App\" and name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".</li>", "<li>{{ ug_li18_3 }}</li>"),
    ("<li>Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.</li>", "<li>{{ ug_li18_4 }}</li>"),
    ("<h4>iCloud</h4>", "<h4>{{ ug_h4_4 }}</h4>"),
    ("<li>Go to <strong>appleid.apple.com > Sign-In and Security > App-Specific Passwords</strong> or <a\n                        href=\"https://appleid.apple.com/{{ qa_step3_p4 }}/manage\"\n                        target=\"_blank\">https://appleid.apple.com/{{ qa_step3_p4 }}/manage</a>.</li>", "<li>{{ ug_li19_1 }}</li>"),
    ("<li>Click the <strong>+</strong>{{ phil_sen_li2 }} to generate a new password.</li>", "<li>{{ ug_li19_2 }}</li>"),
    ("<li>Name it \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\".</li>", "<li>{{ ug_li19_3 }}</li>"),
    ("<li>Use the generated password in <span class=\"notranslate\" translate=\"no\">TapAlert</span>.</li>", "<li>{{ ug_li19_4 }}</li>"),
    ("<h3>Recipients</h3>", "<h3>{{ ug_h3_15 }}</h3>"),
    ("<p>Emails will be sent to all contacts in your <strong>Recipients</strong> list who have an email address\n                saved. To add an email to a contact:</p>", "<p>{{ ug_p19 }}</p>"),
    ("<li>Go to the <strong>Recipients</strong> screen.</li>", "<li>{{ ug_li20_1 }}</li>"),
    ("<li>{{ sms_ios_li1 }} a contact and ensure the email field is filled.</li>", "<li>{{ ug_li20_2 }}</li>"),
    ("<h3>🧪 Testing</h3>", "<h3>{{ ug_h3_16 }}</h3>"),
    ("<p>Before relying on it, tap <strong>Test Connection</strong>. Enter an email address to receive a test\n                message. If successful, your setup is correct.</p>", "<p>{{ ug_p20 }}</p>"),

    ("<h2>7. 📱 {{ feat_widget_title }} ({{ android_table_th2 }} Only)</h2>", "<h2>{{ ug_h2_7 }}</h2>"),
    ("<p>For even faster emergency alerts, you can add a widget to your {{ android_table_th2 }} home screen:</p>", "<p>{{ ug_p21 }}</p>"),
    ("<h3>Adding the Widget</h3>", "<h3>{{ ug_h3_17 }}</h3>"),
    ("<li><strong>Open Settings:</strong> Tap the gear icon ⚙️ in the app.</li>", "<li>{{ ug_li21_1 }}</li>"),
    ("<li><strong>Find Widget Section:</strong> Scroll down to the \"Widget\" section.</li>", "<li>{{ ug_li21_2 }}</li>"),
    ("<li><strong>Tap \"Add\":</strong> The system will prompt you to place the widget on your home screen.</li>", "<li>{{ ug_li21_3 }}</li>"),
    ("<li><strong>Position the Widget:</strong> Drag it to your preferred location and release.</li>", "<li>{{ ug_li21_4 }}</li>"),
    ("<strong>NOTE:</strong> If you already have a widget on your home screen, you'll need to remove the old\n                one before adding a new one.", "{{ ug_note_4 }}"),
    ("<h3>Using the Widget</h3>", "<h3>{{ ug_h3_18 }}</h3>"),
    ("<li><strong>Tap the Widget:</strong> Opens the app and starts the <strong>Countdown</strong>\n                    immediately.</li>", "<li>{{ ug_li22_1 }}</li>"),
    ("<li><strong>App Experience:</strong> You will see the countdown dialog, ensuring the alert is\n                    intentional. You can cancel it if pressed by mistake.</li>", "<li>{{ ug_li22_2 }}</li>"),
    ("<li><strong>Sound:</strong> The app plays an audible alert tone while counting down.</li>", "<li>{{ ug_li22_3 }}</li>"),
    ("<strong>TIP:</strong> The widget is perfect for true emergencies when you need to send an alert with a\n                single tap, {{ ts_loc_li7 }} finding the app in your drawer.", "{{ ug_tip_2 }}"),

    ("<h2>8. 🚀 Sending an Alert</h2>", "<h2>{{ ug_h2_8 }}</h2>"),
    ("<li><strong>{{ sms_so_li1_1 }} App.</strong></li>", "<li>{{ ug_li23_1 }}</li>"),
    ("<li><strong>Trigger the Alert:</strong>\n                    <ul>\n                        <li><strong>In Report Mode:</strong> Tap the large red <strong>SEND ALERT</strong>{{ phil_sen_li2 }}. The\n                            message selected in the tabs (1-4) will be sent.</li>\n                        <li><strong>In <span class=\"notranslate\" translate=\"no\">Panic Mode</span>:</strong>\n                            <ul>\n                                <li>Tap the big red <strong><span class=\"notranslate\" translate=\"no\">SOS</span></strong>\n                                   {{ phil_sen_li2 }} to send a \"Help needed\" alert.</li>\n                                <li>Tap the <strong>Microphone icon</strong> (bottom-right of <span class=\"notranslate\"\n                                        translate=\"no\">SOS</span>) to record and send a\n                                    specific voice message with your <span class=\"notranslate\" translate=\"no\">SOS</span>\n                                    alert.</li>\n                                <li>Tap the green <strong>I'm OK</strong>{{ phil_sen_li2 }} to send a reassuring \"I'm OK\" status.\n                                </li>\n                                <li>Tap the <strong>Microphone icon</strong> (bottom-right of I'm OK) to record and send\n                                    a voice message with your OK status.</li>\n                                <li>Tap the <strong>Emergency Call</strong>{{ phil_sen_li2 }} to dial local emergency services\n                                    immediately.</li>\n                            </ul>\n                        </li>\n                    </ul>\n                </li>", "<li>{{ ug_li23_2_1 }}\n                    <ul>\n                        <li>{{ ug_li23_2_2 }}</li>\n                        <li>{{ ug_li23_2_3 }}\n                            <ul>\n                                <li>{{ ug_li23_2_4 }}</li>\n                                <li>{{ ug_li23_2_5 }}</li>\n                                <li>{{ ug_li23_2_6 }}</li>\n                                <li>{{ ug_li23_2_7 }}</li>\n                                <li>{{ ug_li23_2_8 }}</li>\n                            </ul>\n                        </li>\n                    </ul>\n                </li>"),
    ("<li><strong>The app will:</strong>\n                    <ul>\n                        <li>Fetch your current location (if configured).</li>\n                        <li>Show a <strong>Countdown Dialog</strong> (see \"Countdown Dialog\" below).</li>\n                        <li>Send the alert message to all recipients.</li>\n                    </ul>\n                </li>", "<li>{{ ug_li23_3_1 }}\n                    <ul>\n                        <li>{{ ug_li23_3_2 }}</li>\n                        <li>{{ ug_li23_3_3 }}</li>\n                        <li>{{ ug_li23_3_4 }}</li>\n                    </ul>\n                </li>"),

    ("<h2>9. ⏱️ Countdown Dialog</h2>", "<h2>{{ ug_h2_9 }}</h2>"),
    ("<p>To prevent accidental alerts, <span class=\"notranslate\" translate=\"no\">TapAlert</span> shows a countdown\n                before sending.</p>", "<p>{{ ug_p22 }}</p>"),
    ("<li><strong>Countdown Duration:</strong> By default, the app waits <strong>10 seconds</strong>. You can\n                    customize this in <strong>Settings</strong> (from <strong>0s</strong> for immediate sending up to\n                    <strong>30s</strong>).\n                </li>", "<li>{{ ug_li24_1 }}</li>"),
    ("<li><strong>Cancelling:</strong> You can tap <strong>CANCEL</strong> during the countdown to stop the\n                    alert.</li>", "<li>{{ ug_li24_2 }}</li>"),

    ("<h2>10. 🔔 Making Alert SMS Stand Out</h2>", "<h2>{{ ug_h2_10 }}</h2>"),
    ("<p>To ensure your emergency contacts don't miss your alert message among other notifications, we recommend\n                configuring their phones to treat messages from your <span class=\"notranslate\"\n                    translate=\"no\">TapAlert</span> number differently.</p>", "<p>{{ ug_p23 }}</p>"),
    ("<h3>{{ sms_so_h2_1b }}</h3>", "<h3>{{ ug_h3_19 }}</h3>"),
    ("<li><strong>Open {{ sms_so_li1_2 }}:</strong> {{ sms_so_step1 }}</li>", "<li>{{ ug_li25_1 }}</li>"),
    ("<li><strong>{{ sms_so_step2 }}</strong> Tap <strong>{{ sms_ios_li1 }}</strong> > <strong>{{ sms_ios_li2 }}</strong> (or\n                    Text Tone) and toggle <strong>{{ sms_so_bypass }}</strong> ON. This allows sounds/vibrations even if\n                    their phone is on Silent or Do Not Disturb.</li>", "<li>{{ ug_li25_2 }}</li>"),
    ("<li><strong>{{ sms_so_tone }}</strong> Choose a loud, distinct sound for your messages.</li>", "<li>{{ ug_li25_3 }}</li>"),
    ("<h3>For {{ android_table_th2 }} Recipients</h3>", "<h3>{{ ug_h3_20 }}</h3>"),
    ("<li><strong>{{ sms_so_and_1 }}</strong> {{ sms_so_and_2 }}</li>", "<li>{{ ug_li26_1 }}</li>"),
    ("<li><strong>{{ sms_so_and_3 }}</strong> Tap <strong>{{ sms_and_li1 }}</strong> >\n                    <strong>{{ sms_and_li2 }}</strong>.\n                </li>", "<li>{{ ug_li26_2 }}</li>"),
    ("<li><strong>Set as {{ sms_and_li5 }}:</strong> {{ sms_and_li3 }} <strong>{{ sms_and_li4 }}</strong> or\n                    <strong>{{ sms_and_li5 }}</strong>.\n                </li>", "<li>{{ ug_li26_3 }}</li>"),
    ("<li><strong>{{ sms_so_and_4 }}</strong> {{ sms_and_li6 }} <strong>{{ sms_and_li7 }}</strong> is enabled for this\n                    conversation.</li>", "<li>{{ ug_li26_4 }}</li>"),
    ("<li><strong>{{ sms_so_and_5 }}</strong> {{ sms_so_and_6 }}</li>", "<li>{{ ug_li26_5 }}</li>"),
    ("<strong>NOTE: Using <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong> If you send alerts\n                via <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, your contacts will receive the\n                message from your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> number or an Alphanumeric ID\n                (e.g., \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\"). {{ sms_twilio_p3 }} <strong>{{ ts_em_li5 }}</strong> add\n                this number/ID to their contacts list for the settings above to work correctly. Otherwise, the message\n                will still be delivered but{{ price_disclaimer3 }}standard SMS {{ ts_loc_li7 }} any priority notifications.", "{{ ug_note_5 }}"),

    ("<h2>11. 🕰️ Alert History</h2>", "<h2>{{ ug_h2_11 }}</h2>"),
    ("<p>To keep track of your sent emergency alerts:</p>", "<p>{{ ug_p24 }}</p>"),
    ("<li><strong>Tap the History Icon:</strong> The clock icon 🕰️ located in the top bar.</li>", "<li>{{ ug_li27_1 }}</li>"),
    ("<li><strong>View Recent Alerts:</strong> The app maintains a log of the last <strong>50 alerts</strong>\n                    sent.</li>", "<li>{{ ug_li27_2 }}</li>"),
    ("<li><strong>Check Status:</strong> Tap any entry to see exactly which recipients received the message\n                    successfully and which failed (with error details).</li>", "<li>{{ ug_li27_3 }}</li>"),
    ("<li><strong>Clear History:</strong> You can delete all logs by tapping the trash icon 🗑️ inside the\n                    history screen.</li>", "<li>{{ ug_li27_4 }}</li>"),

    ("<h2>12. ❓ {{ nav_troubleshooting }}</h2>", "<h2>{{ ug_h2_12 }}</h2>"),
    ("<li><strong>Message not sending (<span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span>):</strong>\n                    Check your mobile signal and carrier credit\n                    ({{ android_table_th2 }} only).</li>", "<li>{{ ug_li28_1 }}</li>"),
    ("<li><strong>Message not sending (<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>):</strong>\n                    Verify your internet connection and double-check your\n                    credentials in the settings.</li>", "<li>{{ ug_li28_2 }}</li>"),
    ("<li><strong>{{ ts_li1_5 }} missing:</strong> {{ sms_and_li6 }} GPS is enabled in your phone's system settings and the app\n                    has {{ ts_li1_5 }} permission.</li>", "<li>{{ ug_li28_3 }}</li>"),
    ("<li><strong>{{ sms_so_li1_2 }} missing (iOS):</strong> Go to Settings > {{ table_r2c1 }} > {{ sms_so_li1_2 }} > <span\n                        class=\"notranslate\" translate=\"no\">TapAlert</span> and ensure\n                    <strong>\"All {{ sms_so_li1_2 }}\"</strong> is checked.\n                </li>", "<li>{{ ug_li28_4 }}</li>"),
    ("<li><strong>{{ sms_so_li1_2 }} missing ({{ android_table_th2 }}):</strong> Go to Settings > Apps > <span class=\"notranslate\"\n                        translate=\"no\">TapAlert</span> > Permissions and\n                    ensure <strong>\"{{ sms_so_li1_2 }}\"</strong> is allowed.</li>", "<li>{{ ug_li28_5 }}</li>"),

    ("<h2>13. ⏳ Check-in Timer</h2>", "<h2>{{ ug_h2_13 }}</h2>"),
    ("<p>The <strong>Check-in Timer</strong> is an \"inactive\" safety feature. It allows you to set a timer when\n                starting a potentially risky activity (e.g., walking home alone, going on a hike).</p>", "<p>{{ ug_p25 }}</p>"),
    ("<li><strong>Start the Timer:</strong> {{ ts_loc_li2 }} a duration (from 5 minutes up to 24 hours) and an optional\n                    message.</li>", "<li>{{ ug_li29_1 }}</li>"),
    ("<li><strong>The Countdown:</strong> A persistent notification will show you the remaining time.</li>", "<li>{{ ug_li29_2 }}</li>"),
    ("<li><strong>The Check-in:</strong> You {{ ts_em_li5 }} return to the app and tap <strong>\"I'm OK (Reset)\"</strong>\n                    before the timer expires.</li>", "<li>{{ ug_li29_3 }}</li>"),
    ("<li><strong>Automatic Alert:</strong> If you <em>don't</em> reset the timer before it hits zero,\n                    <span class=\"notranslate\" translate=\"no\">TapAlert</span> will automatically send your alert message\n                    and location to all recipients.\n                </li>", "<li>{{ ug_li29_4 }}</li>")
]

replace_in_file('src/user_guide.html', replacements)
print("Updated user_guide.html (part 2)")
