import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        en[k] = v
    for k, v in new_es.items():
        es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "privacy_last_updated": "Last Updated: February 11, 2026",
    "privacy_p1": "This {{ footer_privacy }} describes how <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> (the \"App\") handles your information. Your privacy is a priority, and the App is designed to minimize data collection and maximize user control. The App operates on a <strong>local-first</strong> principle: all personal data stays on your device.",
    "privacy_h2_1": "1. Information the App Processes",
    "privacy_p_info": "To provide its core functionality (sending emergency alerts via SMS and/or email), the App processes the following information:",
    "privacy_info_li1": "<strong>{{ ts_li1_5 }} Data:</strong> When you trigger an alert, the App accesses your device's GPS coordinates and may resolve them into a physical address. This information is included in the alert message sent to your chosen recipients via a Google Maps link. {{ ts_li1_5 }} is only fetched at the moment of sending and is not tracked continuously.",
    "privacy_info_li2": "<strong>Recipient {{ nav_contact }} Information:</strong> You provide the phone numbers and optionally email addresses of your trusted contacts. These are stored locally on your device.",
    "privacy_info_li3": "<strong>Alert Messages:</strong> You may create and customise predefined alert messages. These are stored locally on your device.",
    "privacy_info_li4": "<strong>Voice Recordings:</strong> The App uses speech-to-text to transcribe voice messages. Audio is processed on-device for transcription and is not stored or transmitted beyond the transcription result, which becomes part of the alert message.",
    "privacy_info_li5": "<strong>Alert History:</strong> The App maintains a local log of alerts sent, including timestamps, recipients, and delivery status. This history is stored on your device only.",
    "privacy_h2_2": "2. Permissions",
    "privacy_p_perm": "The App requests specific system permissions to function. Each permission is requested at runtime with a clear explanation, and you may deny any permission (though some {{ price_features }} will be unavailable).",
    "privacy_h3_and_perm": "{{ android_table_th2 }} Permissions",
    "privacy_and_perm_li1": "<strong>Fine &amp; Coarse {{ ts_li1_5 }} (ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION):</strong> To determine your geographic coordinates when sending an emergency alert.",
    "privacy_and_perm_li2": "<strong>Send SMS (SEND_SMS):</strong> To send alert messages directly via your device's SIM card {{ ts_loc_li7 }} requiring a third-party service.",
    "privacy_and_perm_li3": "<strong>Read Phone State (READ_PHONE_STATE):</strong> To check SIM card availability and cellular network registration status, ensuring the App can accurately report whether SMS sending is possible.",
    "privacy_and_perm_li4": "<strong>Record Audio (RECORD_AUDIO):</strong> To capture voice input for speech-to-text transcription of alert messages.",
    "privacy_and_perm_li5": "<strong>Read {{ sms_so_li1_2 }} (READ_CONTACTS):</strong> To allow you to select emergency recipients from your existing contacts.",
    "privacy_and_perm_li6": "<strong>Post {{ sms_and_li2 }} (POST_NOTIFICATIONS):</strong> To display notifications about alert delivery status and dead man's switch timer events.",
    "privacy_and_perm_li7": "<strong>Internet &amp; Network State (INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE):</strong> To communicate with the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS API (if configured), send email alerts via SMTP, perform address lookups from GPS coordinates, and verify connectivity status.",
    "privacy_and_perm_li8": "<strong>Wake Lock (WAKE_LOCK):</strong> To prevent the device from sleeping during the alert sending process, ensuring delivery completes.",
    "privacy_and_perm_li9": "<strong>Disable Keyguard (DISABLE_KEYGUARD):</strong> To allow alerts triggered from home screen widgets or external automation (e.g., Bluetooth{{ phil_sen_li2 }}s) to proceed {{ ts_loc_li7 }} requiring the device to be unlocked.",
    "privacy_and_perm_li10": "<strong>Battery Optimisation Exemption (REQUEST_IGNORE_BATTERY_OPTIMIZATIONS):</strong> To ensure the dead man's switch timer and widget-triggered alerts work reliably in the background.",
    "privacy_and_perm_li11": "<strong>Billing (com.android.vending.BILLING):</strong> To process in-app purchases for unlocking the unlimited recipients feature via Google Play.",
    "privacy_h3_ios_perm": "iOS Permissions",
    "privacy_ios_perm_li1": "<strong>{{ ts_li1_5 }} (When In Use / Always):</strong> To determine your geographic coordinates when sending an emergency alert.",
    "privacy_ios_perm_li2": "<strong>Microphone:</strong> To capture voice input for speech-to-text transcription.",
    "privacy_ios_perm_li3": "<strong>Speech Recognition:</strong> To transcribe recorded voice into text for alert messages.",
    "privacy_ios_perm_li4": "<strong>{{ sms_so_li1_2 }}:</strong> To allow you to select emergency recipients from your existing contacts.",
    "privacy_ios_perm_li5": "<strong>{{ sms_and_li2 }}:</strong> To display delivery status and timer notifications.",
    "privacy_h2_3": "3. SMS and Email Delivery Methods",
    "privacy_p_methods": "The App supports multiple methods for sending alerts:",
    "privacy_method_li1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ({{ android_table_th2 }} only):</strong> Messages are sent directly through your device's SIM card and carrier. The App uses the {{ android_table_th2 }} SMS Manager API. Standard carrier messaging rates may apply.",
    "privacy_method_li2": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API (iOS &amp; {{ android_table_th2 }}):</strong> If you choose to configure <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, the App uses your personal <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} credentials to send SMS via the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> REST API. Your credentials are stored locally on your device using encrypted storage (flutter_secure_storage). <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> processes the message according to <a href=\"https://www.twilio.com/legal/privacy\" target=\"_blank\"><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s {{ footer_privacy }}</a>.",
    "privacy_method_li3": "<strong>iOS SMS Composer:</strong> On iOS, the App may present the native SMS composer interface, which requires manual confirmation before sending.",
    "privacy_method_li4": "<strong>Email (SMTP):</strong> If you configure email redundancy, the App sends alert emails using your SMTP credentials. These credentials are stored locally on your device. The email is transmitted through your configured SMTP provider.",
    "privacy_h2_4": "4. Data Storage and Security",
    "privacy_storage_li1": "<strong>Local Storage Only:</strong> All configuration data, including recipient information, message templates, alert history, and app preferences, is stored locally on your device using SharedPreferences and encrypted storage.",
    "privacy_storage_li2": "<strong>Sensitive Credentials:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API credentials (Account SID, Auth Token) are stored using flutter_secure_storage, which uses the {{ android_table_th2 }} Keystore system and iOS Keychain for hardware-backed encryption.",
    "privacy_storage_li3": "<strong>No Cloud Storage:</strong> The Developer does not operate any server to collect, store, or monitor your location data, contacts, messages, or usage patterns.",
    "privacy_storage_li4": "<strong>No Analytics or Tracking:</strong> The App does not include any analytics SDKs, crash reporting tools, or advertising frameworks. No usage data is transmitted to the Developer or any third party.",
    "privacy_h2_5": "5. Data Sharing",
    "privacy_p_sharing": "The App <strong>does not sell, trade, or share</strong> your personal data with any third parties. Data is only transmitted in the following circumstances, all initiated by your explicit action of pressing the alert {{ phil_sen_li2 }}:",
    "privacy_sharing_li1": "To the <strong>recipients you explicitly configured</strong> when you trigger an alert (via SMS and/or email).",
    "privacy_sharing_li2": "To your <strong>mobile carrier</strong> when sending <span class=\"notranslate\" translate=\"no\">Direct SMS</span> on {{ android_table_th2 }}.",
    "privacy_sharing_li3": "To <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong> when using the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API for SMS delivery (only if you have configured it).",
    "privacy_sharing_li4": "To your <strong>SMTP email provider</strong> when sending email alerts (only if you have configured it).",
    "privacy_sharing_li5": "To <strong>Google Maps</strong> via a URL link included in the alert message (the recipient opens this link; no data is sent to Google by the App itself).",
    "privacy_sharing_li6": "To <strong>Apple/Google</strong> for in-app purchase verification (purchase status only, no personal data).",
    "privacy_h2_6": "6. In-App Purchases",
    "privacy_p_purchases": "The App offers an optional in-app purchase to unlock unlimited recipients. This purchase is processed entirely through the Apple App Store or Google Play Store. The Developer does not receive or store any payment information. Purchase status is cached locally on your device.",
    "privacy_h2_7": "7. {{ feat_widget_title }}s ({{ android_table_th2 }})",
    "privacy_p_widgets": "The App provides optional home screen widgets for quick alert access. Widget configuration (custom message) is stored locally via SharedPreferences. Tapping a widget launches the App to send an alert and does not transmit any data independently.",
    "privacy_h2_8": "8. Dead Man's Switch",
    "privacy_p_timer": "The App includes a countdown timer feature that can automatically send an alert if not dismissed within a configured period. This operates entirely on-device. No data is transmitted until an alert is actually triggered.",
    "privacy_h2_9": "9. Data Retention and Deletion",
    "privacy_retention_li1": "All data is stored locally on your device and persists until you clear the App's data, uninstall the App, or manually delete entries (e.g., alert history, recipients).",
    "privacy_retention_li2": "Uninstalling the App removes all locally stored data.",
    "privacy_retention_li3": "The Developer has no access to your data and therefore cannot delete it on your behalf.",
    "privacy_h2_10": "10. Children's {{ table_r2c1 }}",
    "privacy_p_children": "The App is not directed at children under 13. It does not knowingly collect any personal information from children. Since all data remains on the user's device and is never transmitted to the Developer, no child data is collected or processed by the Developer.",
    "privacy_h2_11": "11. Your Rights",
    "privacy_p_rights": "Because all data is stored locally on your device and the Developer does not collect or have access to any personal data:",
    "privacy_rights_li1": "You have <strong>full control</strong> over all your data at all times.",
    "privacy_rights_li2": "You can <strong>view, modify, or delete</strong> any data through the App's settings and history screens.",
    "privacy_rights_li3": "You can <strong>revoke any permission</strong> at any time through your device's system settings.",
    "privacy_rights_li4": "You can <strong>remove all data</strong> by uninstalling the App.",
    "privacy_h2_12": "12. Changes to This Policy",
    "privacy_p_changes": "The Developer may update this {{ footer_privacy }} from time to time. Any changes will be reflected by a new \"Last Updated\" date at the top of this document. Continued use of the App after changes constitutes acceptance of the updated policy.",
    "privacy_h2_13": "13. {{ nav_contact }}",
    "privacy_p_contact": "If you have any questions about this {{ footer_privacy }}, please contact the developer through the official App Store or Google Play support channels."
}

es_keys = {
    "privacy_last_updated": "Última Actualización: 11 de Febrero, 2026",
    "privacy_p1": "Esta {{ footer_privacy }} describe cómo <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong> (la \"App\") maneja tu información. Tu privacidad es una prioridad, y la App está diseñada para minimizar la recolección de datos y maximizar el control del usuario. La App opera bajo un principio <strong>local-first</strong>: todos los datos personales permanecen en tu dispositivo.",
    "privacy_h2_1": "1. Información que la App Procesa",
    "privacy_p_info": "Para proporcionar su funcionalidad principal (enviar alertas de emergencia vía SMS y/o correo electrónico), la App procesa la siguiente información:",
    "privacy_info_li1": "<strong>Datos de {{ ts_li1_5 }}:</strong> Cuando activas una alerta, la App accede a las coordenadas GPS de tu dispositivo y puede resolverlas en una dirección física. Esta información se incluye en el mensaje de alerta enviado a tus destinatarios elegidos a través de un enlace de Google Maps. La {{ ts_li1_5 }} solo se obtiene en el momento del envío y no se rastrea de forma continua.",
    "privacy_info_li2": "<strong>Información de {{ nav_contact }} de Destinatarios:</strong> Tú proporcionas los números de teléfono y opcionalmente direcciones de correo electrónico de tus contactos de confianza. Estos se almacenan localmente en tu dispositivo.",
    "privacy_info_li3": "<strong>Mensajes de Alerta:</strong> Puedes crear y personalizar mensajes de alerta predefinidos. Estos se almacenan localmente en tu dispositivo.",
    "privacy_info_li4": "<strong>Grabaciones de Voz:</strong> La App utiliza síntesis de voz a texto para transcribir mensajes de voz. El audio se procesa en el dispositivo para la transcripción y no se almacena ni transmite más allá del resultado de la transcripción, que se convierte en parte del mensaje de alerta.",
    "privacy_info_li5": "<strong>Historial de Alertas:</strong> La App mantiene un registro local de las alertas enviadas, incluyendo marcas de tiempo, destinatarios y estado de entrega. Este historial se almacena solo en tu dispositivo.",
    "privacy_h2_2": "2. Permisos",
    "privacy_p_perm": "La App solicita permisos específicos del sistema para funcionar. Cada permiso se solicita en tiempo de ejecución con una explicación clara, y tú puedes denegar cualquier permiso (aunque algunas {{ price_features }} no estarán disponibles).",
    "privacy_h3_and_perm": "Permisos de {{ android_table_th2 }}",
    "privacy_and_perm_li1": "<strong>{{ ts_li1_5 }} Precisa y Aproximada (ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION):</strong> Para determinar tus coordenadas geográficas al enviar una alerta de emergencia.",
    "privacy_and_perm_li2": "<strong>Enviar SMS (SEND_SMS):</strong> Para enviar mensajes de alerta directamente a través de la tarjeta SIM de tu dispositivo {{ ts_loc_li7 }} requerir un servicio de terceros.",
    "privacy_and_perm_li3": "<strong>Leer Estado del Teléfono (READ_PHONE_STATE):</strong> Para verificar la disponibilidad de la tarjeta SIM y el estado de registro en la red celular, asegurando que la App pueda reportar con precisión si es posible enviar SMS.",
    "privacy_and_perm_li4": "<strong>Grabar Audio (RECORD_AUDIO):</strong> Para capturar entrada de voz para la transcripción de voz a texto de los mensajes de alerta.",
    "privacy_and_perm_li5": "<strong>Leer {{ sms_so_li1_2 }} (READ_CONTACTS):</strong> Para permitirte seleccionar destinatarios de emergencia de tus contactos existentes.",
    "privacy_and_perm_li6": "<strong>Publicar {{ sms_and_li2 }} (POST_NOTIFICATIONS):</strong> Para mostrar notificaciones sobre el estado de entrega de las alertas y eventos del temporizador del interruptor de hombre muerto.",
    "privacy_and_perm_li7": "<strong>Estado de Internet y Red (INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE):</strong> Para comunicarse con la API de SMS de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (si está configurada), enviar alertas por correo electrónico vía SMTP, realizar búsquedas de dirección a partir de coordenadas GPS, y verificar el estado de conectividad.",
    "privacy_and_perm_li8": "<strong>Bloqueo de Estela (WAKE_LOCK):</strong> Para evitar que el dispositivo se duerma durante el proceso de envío de alerta, asegurando que la entrega se complete.",
    "privacy_and_perm_li9": "<strong>Deshabilitar Guardallaves (DISABLE_KEYGUARD):</strong> Para permitir que las alertas activadas desde widgets de la pantalla de inicio o automatización externa (ej., {{ phil_sen_li2 }}es Bluetooth) procedan {{ ts_loc_li7 }} que el dispositivo necesite ser desbloqueado.",
    "privacy_and_perm_li10": "<strong>Exención de Optimización de Batería (REQUEST_IGNORE_BATTERY_OPTIMIZATIONS):</strong> Para asegurar que el temporizador del interruptor de hombre muerto y las alertas activadas por widget funcionen de manera confiable en segundo plano.",
    "privacy_and_perm_li11": "<strong>Facturación (com.android.vending.BILLING):</strong> Para procesar compras en la aplicación para desbloquear la función de destinatarios ilimitados a través de Google Play.",
    "privacy_h3_ios_perm": "Permisos de iOS",
    "privacy_ios_perm_li1": "<strong>{{ ts_li1_5 }} (Al usar o Siempre):</strong> Para determinar tus coordenadas geográficas al enviar una alerta de emergencia.",
    "privacy_ios_perm_li2": "<strong>Micrófono:</strong> Para capturar entrada de voz para transcripción de voz a texto.",
    "privacy_ios_perm_li3": "<strong>Reconocimiento de Voz:</strong> Para transcribir voz grabada a texto para mensajes de alerta.",
    "privacy_ios_perm_li4": "<strong>{{ sms_so_li1_2 }}:</strong> Para permitirte seleccionar destinatarios de emergencia de tus contactos existentes.",
    "privacy_ios_perm_li5": "<strong>{{ sms_and_li2 }}:</strong> Para mostrar el estado de entrega y notificaciones del temporizador.",
    "privacy_h2_3": "3. Métodos de Entrega de SMS y Correo Electrónico",
    "privacy_p_methods": "La App soporta múltiples métodos para el envío de alertas:",
    "privacy_method_li1": "<strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> (Solo {{ android_table_th2 }}):</strong> Los mensajes se envían directamente a través de la tarjeta SIM y el operador de tu dispositivo. La App utiliza la API SMS Manager de {{ android_table_th2 }}. Pueden aplicarse cargos estándar por mensajería del operador.",
    "privacy_method_li2": "<strong>API de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (iOS y {{ android_table_th2 }}):</strong> Si eliges configurar <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, la App utiliza tus credenciales personales de cuentas <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> para enviar SMS a través de la API REST de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. Tus credenciales se almacenan localmente en tu dispositivo mediante almacenamiento cifrado (flutter_secure_storage). <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> procesa el mensaje de acuerdo con <a href=\"https://www.twilio.com/legal/privacy\" target=\"_blank\">la {{ footer_privacy }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></a>.",
    "privacy_method_li3": "<strong>Redactor de SMS de iOS:</strong> En iOS, la App puede presentar la interfaz nativa del redactor de SMS, la cual requiere confirmación manual antes de enviar.",
    "privacy_method_li4": "<strong>Correo electrónico (SMTP):</strong> Si configuras la redundancia de correo electrónico, la App envía correos de alerta utilizando tus credenciales SMTP. Estas credenciales se almacenan localmente en tu dispositivo. El correo electrónico se transmite a través de tu proveedor SMTP configurado.",
    "privacy_h2_4": "4. Almacenamiento de Datos y Seguridad",
    "privacy_storage_li1": "<strong>Solo Almacenamiento Local:</strong> Todos los datos de configuración, incluida la información del destinatario, las plantillas de mensajes, el historial de alertas y las preferencias de la aplicación, se almacenan localmente en tu dispositivo utilizando SharedPreferences y almacenamiento cifrado.",
    "privacy_storage_li2": "<strong>Credenciales Sensibles:</strong> Las credenciales de la API de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (Account SID, Auth Token) se almacenan utilizando flutter_secure_storage, que usa el sistema Keystore de {{ android_table_th2 }} y el Keychain de iOS para el cifrado por hardware.",
    "privacy_storage_li3": "<strong>Sin Almacenamiento en la Nube:</strong> El Desarrollador no opera ningún servidor para recolectar, almacenar o monitorear tus datos de ubicación, contactos, mensajes o patrones de uso.",
    "privacy_storage_li4": "<strong>Sin Análisis de Datos o Rastreo:</strong> La App no incluye ningún SDK de análisis de datos, herramientas de informes de errores, o entornos publicitarios. Ningún dato de uso se transmite al Desarrollador ni a ningún tercero.",
    "privacy_h2_5": "5. Intercambio de Datos",
    "privacy_p_sharing": "La App <strong>no vende, ni intercambia, ni comparte</strong> tus datos personales con ningún tercero. Los datos solo se transmiten en las siguientes circunstancias, todas iniciadas por tu acción explícita de presionar el {{ phil_sen_li2 }} de alerta:",
    "privacy_sharing_li1": "A los <strong>destinatarios que configuraste explícitamente</strong> cuando activas una alerta (vía SMS y/o correo electrónico).",
    "privacy_sharing_li2": "A tu <strong>operador móvil</strong> al enviar un <span class=\"notranslate\" translate=\"no\">SMS Directo</span> en {{ android_table_th2 }}.",
    "privacy_sharing_li3": "A <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong> al usar la API de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> para entrega de SMS (solo si lo has configurado).",
    "privacy_sharing_li4": "A tu <strong>proveedor de correo electrónico SMTP</strong> al enviar alertas de correo electrónico (solo si lo has configurado).",
    "privacy_sharing_li5": "A <strong>Google Maps</strong> mediante un enlace URL incluido en el mensaje de alerta (el destinatario abre este enlace; ningún dato es enviado a Google por la App en sí).",
    "privacy_sharing_li6": "A <strong>Apple/Google</strong> para la verificación de compras dentro de la aplicación (solo estado de compra, no datos personales).",
    "privacy_h2_6": "6. Compras Dentro de la Aplicación",
    "privacy_p_purchases": "La App ofrece una compra opcional dentro de la aplicación para desbloquear destinatarios ilimitados. Esta compra se procesa completamente a través de la Apple App Store o la Google Play Store. El Desarrollador no recibe ni almacena ninguna información de pago. El estado de la compra se guarda localmente en la caché de tu dispositivo.",
    "privacy_h2_7": "7. Widgets ({{ android_table_th2 }})",
    "privacy_p_widgets": "La App proporciona widgets opcionales para la pantalla de inicio para un acceso rápido a alertas. La configuración del widget (mensaje personalizado) se almacena localmente mediante SharedPreferences. Al tocar un widget se inicia la App para enviar una alerta, y no transmite ningún dato de manera independiente.",
    "privacy_h2_8": "8. Interruptor de Hombre Muerto",
    "privacy_p_timer": "La App incluye un temporizador de cuenta regresiva que puede enviar automáticamente una alerta si no se desestima dentro de un periodo configurado. Esto opera en su totalidad en tu dispositivo. Ningún dato es transmitido hasta que se activa realmente una alerta.",
    "privacy_h2_9": "9. Retención y Eliminación de Datos",
    "privacy_retention_li1": "Todos los datos se almacenan de manera local en tu dispositivo y persisten hasta que eliminas los datos de la aplicación, desinstalas la aplicación, o borras entradas manualmente (por ejemplo: historial de alertas o destinatarios).",
    "privacy_retention_li2": "Desinstalar la App remueve todas las informaciones guardadas.",
    "privacy_retention_li3": "El Desarrollador no tiene ningún acceso a tu información y por lo tanto, no te la puede borrar.",
    "privacy_h2_10": "10. {{ table_r2c1 }} de los Niños",
    "privacy_p_children": "La App no está dirigida a niños menores de 13 años. No recopila a sabiendas ninguna información personal de menores. Dado que todos los datos permanecen en el dispositivo del usuario y nunca se transmiten al Desarrollador, este último no recoge ni procesa datos infantiles.",
    "privacy_h2_11": "11. Tus Derechos",
    "privacy_p_rights": "Porque toda información almacenada descansa en el dispositivo de tú control y el Desarrollador jamás recopila tu dato personal:",
    "privacy_rights_li1": "Tú tienes <strong>total control</strong> sobre tu información en cada momento.",
    "privacy_rights_li2": "Tú puedes <strong>ver, modificar o borrar</strong> cualquier dato a través de configuraciones de acceso en tu dispositivo.",
    "privacy_rights_li3": "Tú tienes la facultad de <strong>desautorizar todos permisos que te fueron otorgados</strong> a través de opciones del equipo.",
    "privacy_rights_li4": "Tú tienes el poder de <strong>borrar por completo  esos ajustes</strong> y descartar la aplicación.",
    "privacy_h2_12": "12. Cambios de Estas Normas",
    "privacy_p_changes": "El Desarrollador está al amparo legal para editar este documento. Cambios del mismo se mostrarán en la fecha “Última Actualización” al inicio de la directriz.",
    "privacy_h2_13": "13. {{ nav_contact }}",
    "privacy_p_contact": "Si experimentas dudas y consultas acerca de esta regla del buen uso de {{ footer_privacy }}, no te abstengas y contáctalo, él siempre está activo desde soporte oficial del App Store y Google Play."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<p><strong>Last Updated: February 11, 2026</strong></p>", "<p><strong>{{ privacy_last_updated }}</strong></p>"),
    ("<p>This {{ footer_privacy }} describes how <strong><span class=\"notranslate\" translate=\"no\">TapAlert</span></strong>\n            (the \"App\") handles your\n            information. Your privacy is a priority, and the App is designed to minimize data collection and\n            maximize user control. The App operates on a <strong>local-first</strong> principle: all personal data\n            stays on your device.</p>", "<p>{{ privacy_p1 }}</p>"),
    ("<h2>1. Information the App Processes</h2>", "<h2>{{ privacy_h2_1 }}</h2>"),
    ("<p>To provide its core functionality (sending emergency alerts via SMS and/or email), the App processes the\n            following information:</p>", "<p>{{ privacy_p_info }}</p>"),
    ("<li><strong>{{ ts_li1_5 }} Data:</strong> When you trigger an alert, the App accesses your device's GPS\n                coordinates and may resolve them into a physical address. This information is included in the\n                alert message sent to your chosen recipients via a Google Maps link. {{ ts_li1_5 }} is only fetched at\n                the moment of sending and is not tracked continuously.</li>", "<li>{{ privacy_info_li1 }}</li>"),
    ("<li><strong>Recipient {{ nav_contact }} Information:</strong> You provide the phone numbers and optionally email\n                addresses of your trusted contacts. These are stored locally on your device.</li>", "<li>{{ privacy_info_li2 }}</li>"),
    ("<li><strong>Alert Messages:</strong> You may create and customise predefined alert messages. These are\n                stored locally on your device.</li>", "<li>{{ privacy_info_li3 }}</li>"),
    ("<li><strong>Voice Recordings:</strong> The App uses speech-to-text to transcribe voice messages. Audio is\n                processed on-device for transcription and is not stored or transmitted beyond the transcription\n                result, which becomes part of the alert message.</li>", "<li>{{ privacy_info_li4 }}</li>"),
    ("<li><strong>Alert History:</strong> The App maintains a local log of alerts sent, including timestamps,\n                recipients, and delivery status. This history is stored on your device only.</li>", "<li>{{ privacy_info_li5 }}</li>"),
    ("<h2>2. Permissions</h2>", "<h2>{{ privacy_h2_2 }}</h2>"),
    ("<p>The App requests specific system permissions to function. Each permission is requested at runtime with a\n            clear explanation, and you may deny any permission (though some {{ price_features }} will be unavailable).</p>", "<p>{{ privacy_p_perm }}</p>"),
    ("<h3>{{ android_table_th2 }} Permissions</h3>", "<h3>{{ privacy_h3_and_perm }}</h3>"),
    ("<li><strong>Fine &amp; Coarse {{ ts_li1_5 }} (ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION):</strong> To determine\n                your geographic coordinates when sending an emergency alert.</li>", "<li>{{ privacy_and_perm_li1 }}</li>"),
    ("<li><strong>Send SMS (SEND_SMS):</strong> To send alert messages directly via your device's SIM card\n                {{ ts_loc_li7 }} requiring a third-party service.</li>", "<li>{{ privacy_and_perm_li2 }}</li>"),
    ("<li><strong>Read Phone State (READ_PHONE_STATE):</strong> To check SIM card availability and cellular\n                network registration status, ensuring the App can accurately report whether SMS sending is\n                possible.</li>", "<li>{{ privacy_and_perm_li3 }}</li>"),
    ("<li><strong>Record Audio (RECORD_AUDIO):</strong> To capture voice input for speech-to-text transcription of\n                alert messages.</li>", "<li>{{ privacy_and_perm_li4 }}</li>"),
    ("<li><strong>Read {{ sms_so_li1_2 }} (READ_CONTACTS):</strong> To allow you to select emergency recipients from your\n                existing contacts.</li>", "<li>{{ privacy_and_perm_li5 }}</li>"),
    ("<li><strong>Post {{ sms_and_li2 }} (POST_NOTIFICATIONS):</strong> To display notifications about alert delivery\n                status and dead man's switch timer events.</li>", "<li>{{ privacy_and_perm_li6 }}</li>"),
    ("<li><strong>Internet &amp; Network State (INTERNET, ACCESS_NETWORK_STATE, ACCESS_WIFI_STATE):</strong> To\n                communicate with the <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> SMS API (if configured), send email\n                alerts via SMTP, perform address lookups from GPS coordinates, and verify connectivity status.</li>", "<li>{{ privacy_and_perm_li7 }}</li>"),
    ("<li><strong>Wake Lock (WAKE_LOCK):</strong> To prevent the device from sleeping during the alert sending\n                process, ensuring delivery completes.</li>", "<li>{{ privacy_and_perm_li8 }}</li>"),
    ("<li><strong>Disable Keyguard (DISABLE_KEYGUARD):</strong> To allow alerts triggered from home screen widgets\n                or external automation (e.g., Bluetooth{{ phil_sen_li2 }}s) to proceed {{ ts_loc_li7 }} requiring the device to be\n                unlocked.</li>", "<li>{{ privacy_and_perm_li9 }}</li>"),
    ("<li><strong>Battery Optimisation Exemption (REQUEST_IGNORE_BATTERY_OPTIMIZATIONS):</strong> To ensure the\n                dead man's switch timer and widget-triggered alerts work reliably in the background.</li>", "<li>{{ privacy_and_perm_li10 }}</li>"),
    ("<li><strong>Billing (com.android.vending.BILLING):</strong> To process in-app purchases for unlocking the\n                unlimited recipients feature via Google Play.</li>", "<li>{{ privacy_and_perm_li11 }}</li>"),
    ("<h3>iOS Permissions</h3>", "<h3>{{ privacy_h3_ios_perm }}</h3>"),
    ("<li><strong>{{ ts_li1_5 }} (When In Use / Always):</strong> To determine your geographic coordinates when\n                sending an emergency alert.</li>", "<li>{{ privacy_ios_perm_li1 }}</li>"),
    ("<li><strong>Microphone:</strong> To capture voice input for speech-to-text transcription.</li>", "<li>{{ privacy_ios_perm_li2 }}</li>"),
    ("<li><strong>Speech Recognition:</strong> To transcribe recorded voice into text for alert messages.</li>", "<li>{{ privacy_ios_perm_li3 }}</li>"),
    ("<li><strong>{{ sms_so_li1_2 }}:</strong> To allow you to select emergency recipients from your existing contacts.</li>", "<li>{{ privacy_ios_perm_li4 }}</li>"),
    ("<li><strong>{{ sms_and_li2 }}:</strong> To display delivery status and timer notifications.</li>", "<li>{{ privacy_ios_perm_li5 }}</li>"),
    ("<h2>3. SMS and Email Delivery Methods</h2>", "<h2>{{ privacy_h2_3 }}</h2>"),
    ("<p>The App supports multiple methods for sending alerts:</p>", "<p>{{ privacy_p_methods }}</p>"),
    ("<li><strong><span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> ({{ android_table_th2 }} only):</strong> Messages are sent\n                directly through your device's SIM card and carrier. The App uses the {{ android_table_th2 }} SMS Manager API.\n                Standard carrier messaging rates may apply.</li>", "<li>{{ privacy_method_li1 }}</li>"),
    ("<li><strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API (iOS &amp; {{ android_table_th2 }}):</strong> If you\n                choose to configure <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, the App uses your personal <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} credentials to send SMS via the <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> REST API. Your credentials are stored locally on your\n                device using encrypted storage (flutter_secure_storage). <span class=\"notranslate\"\n                    translate=\"no\">{{ term_twilio }}</span> processes the message according to <a\n                    href=\"https://www.twilio.com/legal/privacy\" target=\"_blank\"><span class=\"notranslate\"\n                        translate=\"no\">{{ term_twilio }}</span>'s {{ footer_privacy }}</a>.</li>", "<li>{{ privacy_method_li2 }}</li>"),
    ("<li><strong>iOS SMS Composer:</strong> On iOS, the App may present the native SMS composer interface, which\n                requires manual confirmation before sending.</li>", "<li>{{ privacy_method_li3 }}</li>"),
    ("<li><strong>Email (SMTP):</strong> If you configure email redundancy, the App sends alert emails using your\n                SMTP credentials. These credentials are stored locally on your device. The email is transmitted\n                through your configured SMTP provider.</li>", "<li>{{ privacy_method_li4 }}</li>"),
    ("<h2>4. Data Storage and Security</h2>", "<h2>{{ privacy_h2_4 }}</h2>"),
    ("<li><strong>Local Storage Only:</strong> All configuration data, including recipient information, message\n                templates, alert history, and app preferences, is stored locally on your device using\n                SharedPreferences and encrypted storage.</li>", "<li>{{ privacy_storage_li1 }}</li>"),
    ("<li><strong>Sensitive Credentials:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API\n                credentials (Account SID, Auth Token) are stored using flutter_secure_storage, which uses the\n                {{ android_table_th2 }} Keystore system and iOS Keychain for hardware-backed encryption.</li>", "<li>{{ privacy_storage_li2 }}</li>"),
    ("<li><strong>No Cloud Storage:</strong> The Developer does not operate any server to collect, store, or\n                monitor your location data, contacts, messages, or usage patterns.</li>", "<li>{{ privacy_storage_li3 }}</li>"),
    ("<li><strong>No Analytics or Tracking:</strong> The App does not include any analytics SDKs, crash reporting\n                tools, or advertising frameworks. No usage data is transmitted to the Developer or any third\n                party.</li>", "<li>{{ privacy_storage_li4 }}</li>"),
    ("<h2>5. Data Sharing</h2>", "<h2>{{ privacy_h2_5 }}</h2>"),
    ("<p>The App <strong>does not sell, trade, or share</strong> your personal data with any third parties. Data is\n            only transmitted in the following circumstances, all initiated by your explicit action of pressing the\n            alert {{ phil_sen_li2 }}:</p>", "<p>{{ privacy_p_sharing }}</p>"),
    ("<li>To the <strong>recipients you explicitly configured</strong> when you trigger an alert (via SMS and/or\n                email).</li>", "<li>{{ privacy_sharing_li1 }}</li>"),
    ("<li>To your <strong>mobile carrier</strong> when sending <span class=\"notranslate\" translate=\"no\">Direct\n                    SMS</span> on {{ android_table_th2 }}.</li>", "<li>{{ privacy_sharing_li2 }}</li>"),
    ("<li>To <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong> when using the <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> API for SMS delivery (only if you have configured it).\n            </li>", "<li>{{ privacy_sharing_li3 }}</li>"),
    ("<li>To your <strong>SMTP email provider</strong> when sending email alerts (only if you have configured\n                it).</li>", "<li>{{ privacy_sharing_li4 }}</li>"),
    ("<li>To <strong>Google Maps</strong> via a URL link included in the alert message (the recipient opens this\n                link; no data is sent to Google by the App itself).</li>", "<li>{{ privacy_sharing_li5 }}</li>"),
    ("<li>To <strong>Apple/Google</strong> for in-app purchase verification (purchase status only, no personal\n                data).</li>", "<li>{{ privacy_sharing_li6 }}</li>"),
    ("<h2>6. In-App Purchases</h2>", "<h2>{{ privacy_h2_6 }}</h2>"),
    ("<p>The App offers an optional in-app purchase to unlock unlimited recipients. This purchase is processed\n            entirely through the Apple App Store or Google Play Store. The Developer does not receive or store any\n            payment information. Purchase status is cached locally on your device.</p>", "<p>{{ privacy_p_purchases }}</p>"),
    ("<h2>7. {{ feat_widget_title }}s ({{ android_table_th2 }})</h2>", "<h2>{{ privacy_h2_7 }}</h2>"),
    ("<p>The App provides optional home screen widgets for quick alert access. Widget configuration (custom message)\n            is stored locally via SharedPreferences. Tapping a widget launches the App to send an alert and does not\n            transmit any data independently.</p>", "<p>{{ privacy_p_widgets }}</p>"),
    ("<h2>8. Dead Man's Switch</h2>", "<h2>{{ privacy_h2_8 }}</h2>"),
    ("<p>The App includes a countdown timer feature that can automatically send an alert if not dismissed within a\n            configured period. This operates entirely on-device. No data is transmitted until an alert is actually\n            triggered.</p>", "<p>{{ privacy_p_timer }}</p>"),
    ("<h2>9. Data Retention and Deletion</h2>", "<h2>{{ privacy_h2_9 }}</h2>"),
    ("<li>All data is stored locally on your device and persists until you clear the App's data, uninstall the\n                App, or manually delete entries (e.g., alert history, recipients).</li>", "<li>{{ privacy_retention_li1 }}</li>"),
    ("<li>Uninstalling the App removes all locally stored data.</li>", "<li>{{ privacy_retention_li2 }}</li>"),
    ("<li>The Developer has no access to your data and therefore cannot delete it on your behalf.</li>", "<li>{{ privacy_retention_li3 }}</li>"),
    ("<h2>10. Children's {{ table_r2c1 }}</h2>", "<h2>{{ privacy_h2_10 }}</h2>"),
    ("<p>The App is not directed at children under 13. It does not knowingly collect any personal information from\n            children. Since all data remains on the user's device and is never transmitted to the Developer, no\n            child data is collected or processed by the Developer.</p>", "<p>{{ privacy_p_children }}</p>"),
    ("<h2>11. Your Rights</h2>", "<h2>{{ privacy_h2_11 }}</h2>"),
    ("<p>Because all data is stored locally on your device and the Developer does not collect or have access to any\n            personal data:</p>", "<p>{{ privacy_p_rights }}</p>"),
    ("<li>You have <strong>full control</strong> over all your data at all times.</li>", "<li>{{ privacy_rights_li1 }}</li>"),
    ("<li>You can <strong>view, modify, or delete</strong> any data through the App's settings and history\n                screens.</li>", "<li>{{ privacy_rights_li2 }}</li>"),
    ("<li>You can <strong>revoke any permission</strong> at any time through your device's system settings.</li>", "<li>{{ privacy_rights_li3 }}</li>"),
    ("<li>You can <strong>remove all data</strong> by uninstalling the App.</li>", "<li>{{ privacy_rights_li4 }}</li>"),
    ("<h2>12. Changes to This Policy</h2>", "<h2>{{ privacy_h2_12 }}</h2>"),
    ("<p>The Developer may update this {{ footer_privacy }} from time to time. Any changes will be reflected by a new\n            \"Last Updated\" date at the top of this document. Continued use of the App after changes constitutes\n            acceptance of the updated policy.</p>", "<p>{{ privacy_p_changes }}</p>"),
    ("<h2>13. {{ nav_contact }}</h2>", "<h2>{{ privacy_h2_13 }}</h2>"),
    ("<p>If you have any questions about this {{ footer_privacy }}, please contact the developer through the official\n            App Store or Google Play support channels.</p>", "<p>{{ privacy_p_contact }}</p>")
]

replace_in_file('src/PRIVACY_POLICY.html', replacements)
print("Updated PRIVACY_POLICY.html")

