import json

def update_locales(new_en, new_es):
    with open('locales/en.json', 'r') as f:
        en = json.load(f)
    with open('locales/es.json', 'r') as f:
        es = json.load(f)
    for k, v in new_en.items():
        en[k] = v
    for k, v in new_es.items():
        es[k] = v
    with open('locales/en.json', 'w') as f:
        json.dump(en, f, indent=4)
    with open('locales/es.json', 'w') as f:
        json.dump(es, f, indent=4)

en_keys = {
    "tw_guide_title": "<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Setup Guide",
    "tw_h2_1": "💡 What is <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Configuration?",
    "tw_p1": "<strong>What you'll be setting up:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> configuration connects <span class=\"notranslate\" translate=\"no\">TapAlert</span> to <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s cloud SMS service, allowing the app to send SMS messages even when your phone's cellular service is unavailable (but you have Wi-Fi).",
    "tw_p2": "<strong>Why it matters:</strong> By configuring <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> credentials in the app, you enable a reliable <span class=\"notranslate\" translate=\"no\">fallback</span> method for sending alerts. This is especially important during international travel, in buildings with poor cellular reception, or{{ price_disclaimer3 }}mandatory option for iPhone users who cannot send SMS directly from apps.",
    "tw_p3": "<strong>Why <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong><br> <span class=\"notranslate\" translate=\"no\">TapAlert</span> uses <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> because it's the most widely used SMS service in the world — trusted by companies like Uber and Airbnb. There are no monthly fees: you only pay a few cents per message actually sent. For an emergency app that sends alerts rarely, this means near-zero cost. Setup requires copying just three values into the app, and thousands of online tutorials exist if you need help.",
    "tw_p4": "<strong>What you need:</strong> A <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} with authentication credentials (Account SID and Auth Token), and either an alphanumeric sender ID or a purchased <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> phone number.",
    "tw_li1": "✅ <strong>Trial {{ qa_step3_p4 }} sends real SMS:</strong> A family member can test the entire setup with <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s free trial (sends to {{ ts_tw_li7 }} numbers) before spending any money.",
    "tw_h2_2": "📖 About the Service",
    "tw_p5": "The option provided in <span class=\"notranslate\" translate=\"no\">TapAlert</span> of using <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (cloud){{ price_disclaimer3 }}mechanism to send SMS provides ultimate reliability in particular in international travel where roaming SMS often fails. <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> can send SMS to over 180 countries. However, the method you can use varies by country. Some countries support <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> phone numbers, others only support Alphanumeric Sender IDs, and some require specific local regulations to be met.",
    "tw_h3_1": "Why use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> on {{ android_table_th2 }}? (<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span>)",
    "tw_p6": "Even if you have a SIM card, setting up <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> is highly recommended for <strong>Redundancy</strong>:",
    "tw_li2": "<strong>Scenario:</strong> You are in a building with Wi-Fi but <strong>zero cellular signal</strong>.",
    "tw_li3": "<strong>Result:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> fails.",
    "tw_li4": "<strong>Solution:</strong> <span class=\"notranslate\" translate=\"no\">TapAlert</span> will automatically switch to <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> and send the alert via Wi-Fi.",
    "tw_p7": "Please note that to use this feature, which is mandatory for iPhone users, you'll need to have a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} ID. The cost of sending messages will be the same as if you were doing it manually from <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. No extra costs will be added by the app.",
    "tw_h3_2": "<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Sender Options",
    "tw_p8": "You can choose between 2 options to send SMS's with <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>:",
    "tw_p9": "<strong>OPTION A: Use Alphanumeric Sender ID (Recommended for Europe)</strong>",
    "tw_li5": "✅ <strong>Benefit:</strong> No need to buy a phone number (Save monthly costs! depending on the number of messages you send).",
    "tw_li6": "✅ <strong>Benefit:</strong> Recipients see a name (e.g., \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\" or your name) instead of a random number.",
    "tw_li7": "⚠️ <strong>Note:</strong> One-way only (no replies) and not supported in some countries (like USA).",
    "tw_li8": "ℹ️ <a href=\"https://help.twilio.com/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS\" target=\"_blank\">Learn more about Alphanumeric Sender ID</a>",
    "tw_p10": "<strong>OPTION B: Buy a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Phone Number</strong>",
    "tw_li9": "✅ <strong>Benefit:</strong> Works worldwide (including USA).",
    "tw_li10": "⚠️ <strong>Cost:</strong> Requires purchasing a number (approx. $1/mo).",
    "tw_h2_3": "💰 Potential Hidden Costs & {{ footer_price }} Factors",
    "tw_p11": "While <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> generally offers low-cost messaging, the final price per SMS can be higher than the base rate due to several factors. It is important to review these to avoid unexpected charges.",
    "tw_h3_3": "1. Destination Country {{ footer_price }}",
    "tw_p12": "<span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> pricing varies significantly depending on the <strong>destination country</strong> of the message.",
    "tw_li11": "The lowest advertised rates (e.g., around $0.0075) often apply to messages sent to the <strong>USA</strong>.",
    "tw_li12": "Sending to other countries (e.g., in Europe or Asia) can be significantly more expensive.",
    "tw_li13": "<strong>Action:</strong> Always check the specific pricing for the country you intend to send alerts to.",
    "tw_h3_4": "2. Carrier & Regulatory Fees",
    "tw_p13": "In addition to <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s base price, many countries and local carriers impose <strong>surcharges</strong> or \"pass-through fees.\"",
    "tw_li14": "These are unavoidable fees added by the telecom providers, not <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.",
    "tw_li15": "{{ sms_twilio_p3 }} can sometimes double the effective cost per message in certain regions.",
    "tw_h3_5": "3. Message Segmentation (Long Messages)",
    "tw_p14": "SMS billing is based on \"segments.\"",
    "tw_li16": "A standard SMS segment is <strong>160 characters</strong>.",
    "tw_li17": "If your message exceeds this limit, it is split into multiple parts, and you are charged for <strong>each segment</strong>. <span class=\"notranslate\" translate=\"no\">TapAlert</span> SMS messages with <strong>{{ ts_li1_5 }} info</strong> exceed this limit. To minimize <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> costs, avoid enabling <strong>{{ ts_li1_5 }} Settings</strong> (or just disable the <strong>Include Address</strong> option in the settings). You can check the actual message length of each sent message in the <strong>Alert History</strong> screen.",
    "tw_li18": "<strong>Important:</strong> Using emojis or special non-Latin characters (Unicode) reduces the segment limit to just <strong>70 characters</strong>, potentially tripling the cost of a single alert.",
    "tw_h3_6": "4. Phone Number Rental Fees",
    "tw_p15": "If you choose to buy a phone number (Option B above):",
    "tw_li19": "You pay a <strong>monthly rental fee</strong> for the number itself (typically $1.00 - $4.00 USD/month depending on the country).",
    "tw_li20": "This is a recurring fixed cost, regardless of whether you send any messages.",
    "tw_li21": "Some specific numbers (like Spanish mobile numbers capable of SMS) are \"Exclusive\" and require a manual request process and higher fees.",
    "tw_h3_7": "5. Currency Conversion & Taxes",
    "tw_p16": "Your final bill may include local taxes (like VAT).",
    "tw_p17": "If your card is in a different currency than your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }}, your bank or <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> may apply currency conversion fees.",
    "tw_h4_1": "💡 Recommendation",
    "tw_p18": "We strongly advise checking the <a href=\"https://www.twilio.com/sms/pricing\" target=\"_blank\">Official <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ footer_price }} Page</a> and selecting your target country to see the full breakdown of costs.",
    "tw_h2_4": "⚙️ Configuration Steps",
    "tw_p19": "To set up <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> in the app, follow these steps:",
    "tw_h3_8": "1️⃣ Step 1: Get your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Credentials",
    "tw_li22": "Create an {{ qa_step3_p4 }} at <a href=\"https://www.twilio.com/\" target=\"_blank\"><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.com</a>.",
    "tw_li23": "Go to the <a href=\"https://console.twilio.com/\" target=\"_blank\"><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Console</a> to find your <strong>Account SID</strong> and <strong>Auth Token</strong>.",
    "tw_li24": "<strong>Choose your sender method</strong> (Option A or B above).",
    "tw_h3_9": "2️⃣ Step 2: Enter Credentials in the App",
    "tw_li25": "{{ sms_so_li1_1 }} App <strong>Settings</strong>.",
    "tw_li26": "Enable the <strong>\"Use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\"</strong> switch.",
    "tw_li27": "Enter your <strong>Account SID</strong> and <strong>Auth Token</strong>.",
    "tw_li28_1": "<strong>Configure the sender:</strong>",
    "tw_li28_a": "<strong>If using Option A (Name):</strong> Enable <strong>\"Use Alphanumeric Sender ID\"</strong>, then type your desired name (max 11 chars) in the <strong>Sender Name</strong> field.",
    "tw_li28_b": "<strong>If using Option B (Number):</strong> Leave \"Use Alphanumeric Sender ID\" <strong>OFF</strong> and enter your purchased <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> number in the <strong><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Phone Number</strong> field.",
    "tw_h3_10": "3️⃣ Step 3: Summary of Alphanumeric Sender ID",
    "tw_li29": "<strong>What is it?</strong> It lets you use a name (like \"MyHomeAlert\") instead of a number.",
    "tw_li30": "<strong>Trust:</strong> Recipients see your name immediately, which ensures your alert stands out.",
    "tw_li31": "<strong>No Replies:</strong> Note that recipients cannot reply to a name."
}

es_keys = {
    "tw_guide_title": "Guía de Configuración de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>",
    "tw_h2_1": "💡 ¿Qué es la Configuración de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?",
    "tw_p1": "<strong>Qué estarás configurando:</strong> La configuración de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> conecta <span class=\"notranslate\" translate=\"no\">TapAlert</span> al servicio de SMS en la nube de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, permitiendo que la app envíe mensajes SMS incluso cuando el servicio celular de tu teléfono no esté disponible (pero tengas Wi-Fi).",
    "tw_p2": "<strong>Por qué es importante:</strong> Al configurar las credenciales de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> en la app, habilitas un método de <span class=\"notranslate\" translate=\"no\">respaldo</span> confiable para enviar alertas. Esto es especialmente importante durante viajes internacionales, en edificios con mala recepción celular, o{{ price_disclaimer3 }}una opción obligatoria para usuarios de iPhone que no pueden enviar SMS directamente desde las aplicaciones.",
    "tw_p3": "<strong>¿Por qué <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong><br> <span class=\"notranslate\" translate=\"no\">TapAlert</span> utiliza <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> porque es el servicio de SMS más utilizado en el mundo — confiado por empresas como Uber y Airbnb. No hay tarifas mensuales: solo pagas unos centavos por mensaje realmente enviado. Para una app de emergencia que envía alertas raramente, esto significa un costo casi cero. La configuración solo requiere copiar tres valores en la app, y existen miles de tutoriales en línea si necesitas ayuda.",
    "tw_p4": "<strong>Qué necesitas:</strong> Una {{ qa_step3_p4 }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> con credenciales de autenticación (Account SID y Auth Token), y ya sea un ID de remitente alfanumérico o un número de teléfono de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> comprado.",
    "tw_li1": "✅ <strong>La {{ qa_step3_p4 }} de prueba envía SMS reales:</strong> Un familiar puede probar toda la configuración con la prueba gratuita de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (envía a números {{ ts_tw_li7 }}) antes de gastar dinero.",
    "tw_h2_2": "📖 Acerca del Servicio",
    "tw_p5": "La opción proporcionada en <span class=\"notranslate\" translate=\"no\">TapAlert</span> de usar el mecanismo de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (en la nube){{ price_disclaimer3 }}para enviar SMS proporciona la máxima confiabilidad, en particular en viajes internacionales donde los SMS en roaming a menudo fallan. <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> puede enviar SMS a más de 180 países. Sin embargo, el método que puedes usar varía según el país. Algunos países admiten números de teléfono de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, otros solo ID de remitente alfanumérico, y algunos requieren cumplir con regulaciones locales específicas.",
    "tw_h3_1": "¿Por qué usar <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> en {{ android_table_th2 }}? (<span class=\"notranslate\" translate=\"no\">{{ phil_red_title }}</span>)",
    "tw_p6": "Incluso si tienes una tarjeta SIM, configurar <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> es muy recomendable por <strong>Redundancia</strong>:",
    "tw_li2": "<strong>Escenario:</strong> Estás en un edificio con Wi-Fi pero <strong>cero señal celular</strong>.",
    "tw_li3": "<strong>Resultado:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> falla.",
    "tw_li4": "<strong>Solución:</strong> <span class=\"notranslate\" translate=\"no\">TapAlert</span> cambiará automáticamente a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> y enviará la alerta a través de Wi-Fi.",
    "tw_p7": "Ten en cuenta que para usar esta función, que es obligatoria para usuarios de iPhone, necesitarás tener un ID de {{ qa_step3_p4 }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. El costo de enviar mensajes será el mismo que si lo hicieras manualmente desde <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>. La app no añadirá costos adicionales.",
    "tw_h3_2": "Opciones de Remitente de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>",
    "tw_p8": "Puedes elegir entre 2 opciones para enviar SMS con <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>:",
    "tw_p9": "<strong>OPCIÓN A: Usar ID de Remitente Alfanumérico (Recomendado para Europa)</strong>",
    "tw_li5": "✅ <strong>Beneficio:</strong> No es necesario comprar un número de teléfono (¡Ahorra costos mensuales! dependiendo de la cantidad de mensajes que envíes).",
    "tw_li6": "✅ <strong>Beneficio:</strong> Los destinatarios ven un nombre (ej., \"<span class=\"notranslate\" translate=\"no\">TapAlert</span>\" o tu nombre) en lugar de un número aleatorio.",
    "tw_li7": "⚠️ <strong>Nota:</strong> Solo unidireccional (sin respuestas) y no compatible en algunos países (como EE. UU.).",
    "tw_li8": "ℹ️ <a href=\"https://help.twilio.com/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS\" target=\"_blank\">Aprende más sobre el ID de Remitente Alfanumérico</a>",
    "tw_p10": "<strong>OPCIÓN B: Comprar un Número de Teléfono de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong>",
    "tw_li9": "✅ <strong>Beneficio:</strong> Funciona en todo el mundo (incluyendo EE. UU.).",
    "tw_li10": "⚠️ <strong>Costo:</strong> Requiere la compra de un número (aprox. $1/mes).",
    "tw_h2_3": "💰 Posibles Costos Ocultos y Factores de {{ footer_price }}",
    "tw_p11": "Aunque <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> generalmente ofrece mensajería de bajo costo, el precio final por SMS puede ser más alto que la tarifa base debido a varios factores. Es importante revisarlos para evitar cargos inesperados.",
    "tw_h3_3": "1. {{ footer_price }} en el País de Destino",
    "tw_p12": "El precio de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> varía significativamente dependiendo del <strong>país de destino</strong> del mensaje.",
    "tw_li11": "Las tarifas anunciadas más bajas (por ejemplo, alrededor de $0.0075) a menudo se aplican a los mensajes enviados a <strong>EE. UU.</strong>.",
    "tw_li12": "Enviar a otros países (por ejemplo, en Europa o Asia) puede ser significativamente más caro.",
    "tw_li13": "<strong>Acción:</strong> Siempre verifica el precio específico para el país al que intentas enviar alertas.",
    "tw_h3_4": "2. Tarifas del Operador y Regulatorias",
    "tw_p13": "Además del precio base de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, muchos países y operadores locales imponen <strong>recargos</strong> o \"tarifas de transferencia\".",
    "tw_li14": "Estos son cargos inevitables agregados por los proveedores de telecomunicaciones, no por <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.",
    "tw_li15": "{{ sms_twilio_p3 }} a veces puede duplicar el costo efectivo por mensaje en ciertas regiones.",
    "tw_h3_5": "3. Segmentación de Mensajes (Mensajes Largos)",
    "tw_p14": "La facturación de SMS se basa en \"segmentos\".",
    "tw_li16": "Un segmento de SMS estándar es de <strong>160 caracteres</strong>.",
    "tw_li17": "Si tu mensaje excede este límite, se divide en varias partes, y se te cobra por <strong>cada segmento</strong>. Los mensajes SMS de <span class=\"notranslate\" translate=\"no\">TapAlert</span> con <strong>información de {{ ts_li1_5 }}</strong> exceden este límite. Para minimizar los costos de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, evita habilitar la <strong>Configuración de {{ ts_li1_5 }}</strong> (o simplemente desactiva la opción <strong>Incluir Dirección</strong> en la configuración). Puedes verificar la longitud real del mensaje de cada mensaje enviado en la pantalla de <strong>Historial de Alertas</strong>.",
    "tw_li18": "<strong>Importante:</strong> El uso de emojis o caracteres especiales no latinos (Unicode) reduce el límite del segmento a solo <strong>70 caracteres</strong>, triplicando potencialmente el costo de una sola alerta.",
    "tw_h3_6": "4. Tarifas de Alquiler de Números de Teléfono",
    "tw_p15": "Si eliges comprar un número de teléfono (Opción B arriba):",
    "tw_li19": "Pagas una <strong>tarifa de alquiler mensual</strong> por el número en sí (típicamente $1.00 - $4.00 USD/mes dependiendo del país).",
    "tw_li20": "Este es un costo fijo recurrente, independientemente de si envías algún mensaje.",
    "tw_li21": "Algunos números específicos (como los números móviles españoles capaces de SMS) son \"Exclusivos\" y requieren un proceso de solicitud manual y tarifas más altas.",
    "tw_h3_7": "5. Conversión de Moneda y Ajustes",
    "tw_p16": "Tu factura final puede incluir impuestos locales (como el IVA).",
    "tw_p17": "Si tu tarjeta está en una moneda diferente a tu {{ qa_step3_p4 }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>, tu banco o <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> puede aplicar tarifas de conversión de moneda.",
    "tw_h4_1": "💡 Recomendación",
    "tw_p18": "Aconsejamos encarecidamente revisar la <a href=\"https://www.twilio.com/sms/pricing\" target=\"_blank\">Página Oficial de {{ footer_price }} de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></a> y seleccionar tu país de destino para ver el desglose completo de los costos.",
    "tw_h2_4": "⚙️ Pasos de Configuración",
    "tw_p19": "Para configurar <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> en la app, sigue estos pasos:",
    "tw_h3_8": "1️⃣ Paso 1: Obtén tus Credenciales de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>",
    "tw_li22": "Crea una {{ qa_step3_p4 }} en <a href=\"https://www.twilio.com/\" target=\"_blank\"><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.com</a>.",
    "tw_li23": "Ve a la <a href=\"https://console.twilio.com/\" target=\"_blank\">Consola de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></a> para encontrar tu <strong>Account SID</strong> y <strong>Auth Token</strong>.",
    "tw_li24": "<strong>Elige tu método de remitente</strong> (Opción A o B arriba).",
    "tw_h3_9": "2️⃣ Paso 2: Ingresa las Credenciales en la App",
    "tw_li25": "{{ sms_so_li1_1 }} <strong>Configuración</strong> de la app.",
    "tw_li26": "Habilita el interruptor <strong>\"Usar <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\"</strong>.",
    "tw_li27": "Ingresa tu <strong>Account SID</strong> y <strong>Auth Token</strong>.",
    "tw_li28_1": "<strong>Configura el remitente:</strong>",
    "tw_li28_a": "<strong>Si usas la Opción A (Nombre):</strong> Habilita <strong>\"Usar ID de Remitente Alfanumérico\"</strong>, luego escribe tu nombre deseado (máx. 11 caracteres) en el campo <strong>Nombre del Remitente</strong>.",
    "tw_li28_b": "<strong>Si usas la Opción B (Número):</strong> Deja \"Usar ID de Remitente Alfanumérico\" <strong>APAGADO</strong> e ingresa el número de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> comprado en el campo <strong>Número de Teléfono de <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span></strong>.",
    "tw_h3_10": "3️⃣ Paso 3: Resumen del ID de Remitente Alfanumérico",
    "tw_li29": "<strong>¿Qué es?</strong> Te permite usar un nombre (como \"MiAlertaHogar\") en lugar de un número.",
    "tw_li30": "<strong>Confianza:</strong> Los destinatarios ven tu nombre inmediatamente, lo que asegura que tu alerta resalte.",
    "tw_li31": "<strong>Sin Respuestas:</strong> Ten en cuenta que los destinatarios no pueden responder a un nombre."
}

update_locales(en_keys, es_keys)

def replace_in_file(filepath, replacements):
    with open(filepath, 'r') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w') as f:
        f.write(content)

replacements = [
    ("<title><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Setup Guide - TapAlert</title>", "<title>{{ tw_guide_title }} - TapAlert</title>"),
    ("<h1 class=\"guide-title\"><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Setup Guide</h1>", "<h1 class=\"guide-title\">{{ tw_guide_title }}</h1>"),
    ("<h2>💡 What is <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Configuration?</h2>", "<h2>{{ tw_h2_1 }}</h2>"),
    ("<p><strong>What you'll be setting up:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\n                configuration connects <span class=\"notranslate\" translate=\"no\">TapAlert</span> to <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s cloud SMS\n                service, allowing the app to send SMS messages even when your phone's cellular service is unavailable\n                (but you have Wi-Fi).</p>", "<p>{{ tw_p1 }}</p>"),
    ("<p><strong>Why it matters:</strong> By configuring <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\n                credentials in the app, you enable a reliable\n                <span class=\"notranslate\" translate=\"no\">fallback</span> method for sending alerts. This is especially\n                important during international travel, in\n                buildings with poor cellular reception, or{{ price_disclaimer3 }}mandatory option for iPhone users who cannot send SMS\n                directly from apps.\n            </p>", "<p>{{ tw_p2 }}</p>"),
    ("<p><strong>Why <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>?</strong><br>\n                <span class=\"notranslate\" translate=\"no\">TapAlert</span> uses <span class=\"notranslate\"\n                    translate=\"no\">{{ term_twilio }}</span> because it's the most widely used SMS service in the world — trusted by\n                companies\n                like Uber and Airbnb. There are no monthly fees: you only pay a few cents per message actually sent. For\n                an emergency app that sends alerts rarely, this means near-zero cost. Setup requires copying just three\n                values into the app, and thousands of online tutorials exist if you need help.\n            </p>", "<p>{{ tw_p3 }}</p>"),
    ("<p><strong>What you need:</strong> A <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ qa_step3_p4 }} with\n                authentication credentials (Account SID and Auth\n                Token), and either an alphanumeric sender ID or a purchased <span class=\"notranslate\"\n                    translate=\"no\">{{ term_twilio }}</span> phone number.</p>", "<p>{{ tw_p4 }}</p>"),
    ("<li>✅ <strong>Trial {{ qa_step3_p4 }} sends real SMS:</strong> A family member can test the entire setup with\n                    <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s free trial (sends to {{ ts_tw_li7 }} numbers)\n                    before spending any money.\n                </li>", "<li>{{ tw_li1 }}</li>"),
    ("<h2>📖 About the Service</h2>", "<h2>{{ tw_h2_2 }}</h2>"),
    ("<p>The option provided in <span class=\"notranslate\" translate=\"no\">TapAlert</span> of using <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> (cloud){{ price_disclaimer3 }}mechanism to send SMS provides\n                ultimate\n                reliability in particular in international travel where roaming SMS often fails. <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> can send SMS to\n                over 180 countries. However, the method you can use varies by country. Some countries support <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\n                phone numbers, others only support Alphanumeric Sender IDs, and some require specific local regulations\n                to be met.</p>", "<p>{{ tw_p5 }}</p>"),
    ("<h3>Why use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> on {{ android_table_th2 }}? (<span class=\"notranslate\"\n                    translate=\"no\">{{ phil_red_title }}</span>)</h3>", "<h3>{{ tw_h3_1 }}</h3>"),
    ("<p>Even if you have a SIM card, setting up <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> is highly\n                recommended for <strong>Redundancy</strong>:</p>", "<p>{{ tw_p6 }}</p>"),
    ("<li><strong>Scenario:</strong> You are in a building with Wi-Fi but <strong>zero cellular\n                        signal</strong>.</li>", "<li>{{ tw_li2 }}</li>"),
    ("<li><strong>Result:</strong> <span class=\"notranslate\" translate=\"no\">{{ term_direct_sms }}</span> fails.</li>", "<li>{{ tw_li3 }}</li>"),
    ("<li><strong>Solution:</strong> <span class=\"notranslate\" translate=\"no\">TapAlert</span> will\n                    automatically switch to <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> and send the alert\n                    via\n                    Wi-Fi.</li>", "<li>{{ tw_li4 }}</li>"),
    ("<p>Please note that to use this feature, which is mandatory for iPhone users, you'll need to have a <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\n                {{ qa_step3_p4 }} ID. The cost of sending messages will be the same as if you were doing it manually from <span\n                    class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>.\n                No extra costs will be added by the app.</p>", "<p>{{ tw_p7 }}</p>"),
    ("<h3><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Sender Options</h3>", "<h3>{{ tw_h3_2 }}</h3>"),
    ("<p>You can choose between 2 options to send SMS's with <span class=\"notranslate\"\n                    translate=\"no\">{{ term_twilio }}</span>:</p>", "<p>{{ tw_p8 }}</p>"),
    ("<p><strong>OPTION A: Use Alphanumeric Sender ID (Recommended for Europe)</strong></p>", "<p>{{ tw_p9 }}</p>"),
    ("<li>✅ <strong>Benefit:</strong> No need to buy a phone number (Save monthly costs! depending on the\n                    number of messages you send).</li>", "<li>{{ tw_li5 }}</li>"),
    ("<li>✅ <strong>Benefit:</strong> Recipients see a name (e.g., \"<span class=\"notranslate\"\n                        translate=\"no\">TapAlert</span>\" or your name) instead of a\n                    random number.</li>", "<li>{{ tw_li6 }}</li>"),
    ("<li>⚠️ <strong>Note:</strong> One-way only (no replies) and not supported in some countries (like USA).\n                </li>", "<li>{{ tw_li7 }}</li>"),
    ("<li><a href=\"https://help.twilio.com/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS\"\n                        target=\"_blank\">Learn more about Alphanumeric Sender ID</a></li>", "<li>{{ tw_li8 }}</li>"),
    ("<p><strong>OPTION B: Buy a <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Phone Number</strong></p>", "<p>{{ tw_p10 }}</p>"),
    ("<li>✅ <strong>Benefit:</strong> Works worldwide (including USA).</li>", "<li>{{ tw_li9 }}</li>"),
    ("<li>⚠️ <strong>Cost:</strong> Requires purchasing a number (approx. $1/mo).</li>", "<li>{{ tw_li10 }}</li>"),
    ("<h2>💰 Potential Hidden Costs & {{ footer_price }} Factors</h2>", "<h2>{{ tw_h2_3 }}</h2>"),
    ("<p>While <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> generally offers low-cost messaging, the\n                final price per SMS can be higher than the base\n                rate due to several factors. It is important to review these to avoid unexpected charges.</p>", "<p>{{ tw_p11 }}</p>"),
    ("<h3>1. Destination Country {{ footer_price }}</h3>", "<h3>{{ tw_h3_3 }}</h3>"),
    ("<p><span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> pricing varies significantly depending on the\n                <strong>destination country</strong> of the message.\n            </p>", "<p>{{ tw_p12 }}</p>"),
    ("<li>The lowest advertised rates (e.g., around $0.0075) often apply to messages sent to the\n                    <strong>USA</strong>.\n                </li>", "<li>{{ tw_li11 }}</li>"),
    ("<li>Sending to other countries (e.g., in Europe or Asia) can be significantly more expensive.</li>", "<li>{{ tw_li12 }}</li>"),
    ("<li><strong>Action:</strong> Always check the specific pricing for the country you intend to send alerts\n                    to.</li>", "<li>{{ tw_li13 }}</li>"),
    ("<h3>2. Carrier & Regulatory Fees</h3>", "<h3>{{ tw_h3_4 }}</h3>"),
    ("<p>In addition to <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>'s base price, many countries and\n                local carriers impose <strong>surcharges</strong>\n                or \"pass-through fees.\"</p>", "<p>{{ tw_p13 }}</p>"),
    ("<li>These are unavoidable fees added by the telecom providers, not <span class=\"notranslate\"\n                        translate=\"no\">{{ term_twilio }}</span>.</li>", "<li>{{ tw_li14 }}</li>"),
    ("<li>{{ sms_twilio_p3 }} can sometimes double the effective cost per message in certain regions.</li>", "<li>{{ tw_li15 }}</li>"),
    ("<h3>3. Message Segmentation (Long Messages)</h3>", "<h3>{{ tw_h3_5 }}</h3>"),
    ("<p>SMS billing is based on \"segments.\"</p>", "<p>{{ tw_p14 }}</p>"),
    ("<li>A standard SMS segment is <strong>160 characters</strong>.</li>", "<li>{{ tw_li16 }}</li>"),
    ("<li>If your message exceeds this limit, it is split into multiple parts, and you are charged for\n                    <strong>each segment</strong>. <span class=\"notranslate\" translate=\"no\">TapAlert</span> SMS messages\n                    with <strong>{{ ts_li1_5 }} info</strong> exceed this\n                    limit. To minimize <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> costs, avoid enabling\n                    <strong>{{ ts_li1_5 }} Settings</strong> (or just disable\n                    the <strong>Include Address</strong> option in the settings). You can check the actual message\n                    length of each sent message in the <strong>Alert History</strong> screen.\n                </li>", "<li>{{ tw_li17 }}</li>"),
    ("<li><strong>Important:</strong> Using emojis or special non-Latin characters (Unicode) reduces the\n                    segment limit to just <strong>70 characters</strong>, potentially tripling the cost of a single\n                    alert.</li>", "<li>{{ tw_li18 }}</li>"),
    ("<h3>4. Phone Number Rental Fees</h3>", "<h3>{{ tw_h3_6 }}</h3>"),
    ("<p>If you choose to buy a phone number (Option B above):</p>", "<p>{{ tw_p15 }}</p>"),
    ("<li>You pay a <strong>monthly rental fee</strong> for the number itself (typically $1.00 - $4.00\n                    USD/month depending on the country).</li>", "<li>{{ tw_li19 }}</li>"),
    ("<li>This is a recurring fixed cost, regardless of whether you send any messages.</li>", "<li>{{ tw_li20 }}</li>"),
    ("<li>Some specific numbers (like Spanish mobile numbers capable of SMS) are \"Exclusive\" and require a\n                    manual request process and higher fees.</li>", "<li>{{ tw_li21 }}</li>"),
    ("<h3>5. Currency Conversion & Taxes</h3>", "<h3>{{ tw_h3_7 }}</h3>"),
    ("<p>Your final bill may include local taxes (like VAT).</p>", "<p>{{ tw_p16 }}</p>"),
    ("<p>If your card is in a different currency than your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\n                {{ qa_step3_p4 }}, your bank or <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> may apply currency\n                conversion fees.</p>", "<p>{{ tw_p17 }}</p>"),
    ("<h4>💡 Recommendation</h4>", "<h4>{{ tw_h4_1 }}</h4>"),
    ("<p>We strongly advise checking the <a href=\"https://www.twilio.com/sms/pricing\" target=\"_blank\">Official\n                        <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> {{ footer_price }} Page</a> and selecting your\n                    target country to see the full breakdown of costs.\n                </p>", "<p>{{ tw_p18 }}</p>"),
    ("<h2>⚙️ Configuration Steps</h2>", "<h2>{{ tw_h2_4 }}</h2>"),
    ("<p>To set up <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> in the app, follow these steps:</p>", "<p>{{ tw_p19 }}</p>"),
    ("<h3>1️⃣ Step 1: Get your <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span> Credentials</h3>", "<h3>{{ tw_h3_8 }}</h3>"),
    ("<li>Create an {{ qa_step3_p4 }} at <a href=\"https://www.twilio.com/\" target=\"_blank\"><span class=\"notranslate\"\n                            translate=\"no\">{{ term_twilio }}</span>.com</a>.</li>", "<li>{{ tw_li22 }}</li>"),
    ("<li>Go to the <a href=\"https://console.twilio.com/\" target=\"_blank\"><span class=\"notranslate\"\n                            translate=\"no\">{{ term_twilio }}</span> Console</a> to find your\n                    <strong>Account SID</strong> and <strong>Auth Token</strong>.\n                </li>", "<li>{{ tw_li23 }}</li>"),
    ("<li><strong>Choose your sender method</strong> (Option A or B above).</li>", "<li>{{ tw_li24 }}</li>"),
    ("<h3>2️⃣ Step 2: Enter Credentials in the App</h3>", "<h3>{{ tw_h3_9 }}</h3>"),
    ("<li>{{ sms_so_li1_1 }} App <strong>Settings</strong>.</li>", "<li>{{ tw_li25 }}</li>"),
    ("<li>Enable the <strong>\"Use <span class=\"notranslate\" translate=\"no\">{{ term_twilio }}</span>\"</strong> switch.\n                </li>", "<li>{{ tw_li26 }}</li>"),
    ("<li>Enter your <strong>Account SID</strong> and <strong>Auth Token</strong>.</li>", "<li>{{ tw_li27 }}</li>"),
    ("<li><strong>Configure the sender:</strong>\n                    <ul>\n                        <li><strong>If using Option A (Name):</strong> Enable <strong>\"Use Alphanumeric Sender\n                                ID\"</strong>, then type your desired name (max 11 chars) in the <strong>Sender\n                                Name</strong> field.</li>\n                        <li><strong>If using Option B (Number):</strong> Leave \"Use Alphanumeric Sender ID\"\n                            <strong>OFF</strong> and enter your purchased <span class=\"notranslate\"\n                                translate=\"no\">{{ term_twilio }}</span> number in the <strong><span class=\"notranslate\"\n                                    translate=\"no\">{{ term_twilio }}</span> Phone\n                                Number</strong> field.\n                        </li>\n                    </ul>\n                </li>", "<li>{{ tw_li28_1 }}\n                    <ul>\n                        <li>{{ tw_li28_a }}</li>\n                        <li>{{ tw_li28_b }}</li>\n                    </ul>\n                </li>"),
    ("<h3>3️⃣ Step 3: Summary of Alphanumeric Sender ID</h3>", "<h3>{{ tw_h3_10 }}</h3>"),
    ("<li><strong>What is it?</strong> It lets you use a name (like \"MyHomeAlert\") instead of a number.</li>", "<li>{{ tw_li29 }}</li>"),
    ("<li><strong>Trust:</strong> Recipients see your name immediately, which ensures your alert stands out.\n                </li>", "<li>{{ tw_li30 }}</li>"),
    ("<li><strong>No Replies:</strong> Note that recipients cannot reply to a name.</li>", "<li>{{ tw_li31 }}</li>")
]

replace_in_file('src/twilio_guide.html', replacements)
print("Updated twilio_guide.html")
